//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

@interface _TtC5Tower25UserPreferencesThemesView : NSView
{
    // Error parsing type: , name: viewStylesObserver
    // Error parsing type: , name: themesScrollView
    // Error parsing type: , name: themeTableView
    // Error parsing type: , name: themeActionBar
    // Error parsing type: , name: addThemeButton
    // Error parsing type: , name: removeThemeButton
    // Error parsing type: , name: fontTextField
    // Error parsing type: , name: fontSelectorButton
    // Error parsing type: , name: fontColorSelectorButton
    // Error parsing type: , name: addedColorButton
    // Error parsing type: , name: addedColorLabel
    // Error parsing type: , name: deletedColorButton
    // Error parsing type: , name: deletedColorLabel
    // Error parsing type: , name: backgroundColorButton
    // Error parsing type: , name: backgroundColorLabel
    // Error parsing type: , name: separator
    // Error parsing type: , name: diffViewBox
    // Error parsing type: , name: diffPreviewScrollView
    // Error parsing type: , name: diffPreviewView
    // Error parsing type: , name: warningButton
}

- (void).cxx_destruct;
- (void)viewStylesDidChangeWithNotification:(id)arg1;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

