//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtCC5Tower10StringDiff7Element : NSObject
{
    // Error parsing type: , name: range
    // Error parsing type: , name: type
}

- (id)init;
@property(nonatomic, readonly) long long type; // @synthesize type;
@property(nonatomic, readonly) struct _NSRange range; // @synthesize range;

@end

