//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FNFoundation/FNObserver.h>

@class NSMetadataQuery, NSObject;
@protocol FNMetadataQueryObserving;

@interface FNMetadataQueryObserver : FNObserver
{
    NSMetadataQuery *_metadataQuery;
    NSObject<FNMetadataQueryObserving> *_observer;
}

+ (id)observerWithMetadataQuery:(id)arg1 observer:(id)arg2;
- (void).cxx_destruct;
@property(nonatomic) __weak NSObject<FNMetadataQueryObserving> *observer; // @synthesize observer=_observer;
@property(retain, nonatomic) NSMetadataQuery *metadataQuery; // @synthesize metadataQuery=_metadataQuery;
- (void)registerObservers;
- (id)invocationTarget;
- (id)initWithMetadataQuery:(id)arg1 observer:(id)arg2;

@end

