//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FNNavigationBar, FNNavigationItem;

@protocol FNNavigationBarDelegate <NSObject>

@optional
- (void)navigationBar:(FNNavigationBar *)arg1 didPopItem:(FNNavigationItem *)arg2;
- (BOOL)navigationBar:(FNNavigationBar *)arg1 shouldPopItem:(FNNavigationItem *)arg2;
- (void)navigationBar:(FNNavigationBar *)arg1 didPushItem:(FNNavigationItem *)arg2;
- (BOOL)navigationBar:(FNNavigationBar *)arg1 shouldPushItem:(FNNavigationItem *)arg2;
@end

