//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FNProductNewsletterAPIConfig, NSOperationQueue;

@interface FNProductNewsletterAPIClient : NSObject
{
    FNProductNewsletterAPIConfig *_config;
    NSOperationQueue *_queue;
}

+ (id)APIClientWithConfig:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) NSOperationQueue *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) FNProductNewsletterAPIConfig *config; // @synthesize config=_config;
- (id)subscribeWithEmailAddress:(id)arg1 options:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)cancel;
- (id)allRequests;
- (void)cancelAllRequests;
- (id)enqueueRequest:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (id)executeRequest:(id)arg1 error:(id *)arg2;
- (void)dealloc;
- (id)initWithConfig:(id)arg1;
- (id)init;

@end

