//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSToolbarDelegate-Protocol.h"

@class GTSearchController, NSSearchField, NSSegmentedControl;

@interface GTActivityWindowToolbarController : NSObject <NSToolbarDelegate>
{
    // Error parsing type: , name: searchController
    // Error parsing type: , name: searchField
    // Error parsing type: , name: $__lazy_storage_$_clearAllItem
    // Error parsing type: , name: $__lazy_storage_$_remoteActivityItem
    // Error parsing type: , name: $__lazy_storage_$_repositoryActivityItem
    // Error parsing type: , name: $__lazy_storage_$_serviceActivityItem
    // Error parsing type: , name: $__lazy_storage_$_activitySelectorItem
    // Error parsing type: , name: $__lazy_storage_$_searchItem
}

- (void).cxx_destruct;
- (id)init;
- (id)toolbar:(id)arg1 itemForItemIdentifier:(id)arg2 willBeInsertedIntoToolbar:(BOOL)arg3;
- (id)toolbarAllowedItemIdentifiers:(id)arg1;
- (id)toolbarDefaultItemIdentifiers:(id)arg1;
@property(nonatomic, readonly) NSSegmentedControl *activitySelectorSegmentedControl;
@property(nonatomic, readonly) NSSearchField *searchField; // @synthesize searchField;
@property(nonatomic, retain) GTSearchController *searchController; // @synthesize searchController;

@end

