//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, NSError, NSMutableString, NSString;
@protocol GTActionNotificationDelegate;

@interface GTAction : NSObject
{
    BOOL _autovalidates;
    BOOL _finished;
    NSString *_identifier;
    NSError *_error;
    id <GTActionNotificationDelegate> _notificationDelegate;
    CDUnknownBlockType _completionHandler;
    NSDate *_startedDate;
    NSMutableString *_logString;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableString *logString; // @synthesize logString=_logString;
@property(retain, nonatomic) NSDate *startedDate; // @synthesize startedDate=_startedDate;
@property(copy, nonatomic) CDUnknownBlockType completionHandler; // @synthesize completionHandler=_completionHandler;
@property(nonatomic) __weak id <GTActionNotificationDelegate> notificationDelegate; // @synthesize notificationDelegate=_notificationDelegate;
@property(getter=isFinished) BOOL finished; // @synthesize finished=_finished;
@property(nonatomic) BOOL autovalidates; // @synthesize autovalidates=_autovalidates;
@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
@property(retain, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void)appendToDetailedLog:(id)arg1;
- (void)appendToLog:(id)arg1;
- (void)logToConsole;
- (BOOL)validate:(id *)arg1;
- (void)finalizeAction;
- (void)actionDidFinish;
- (void)actionDidFailWithError:(id)arg1;
- (void)waitUntilFinished;
- (void)main;
- (void)performActionWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)performAction;
- (BOOL)performAction:(id *)arg1;
- (id)init;

@end

