//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSUserInterfaceValidations-Protocol.h"

@class NSMutableDictionary;

@interface GTActionSenderValidator : NSObject <NSUserInterfaceValidations>
{
    NSMutableDictionary *_registeredActions;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableDictionary *registeredActions; // @synthesize registeredActions=_registeredActions;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (BOOL)canValidateUserInterfaceItem:(id)arg1;
- (BOOL)validateToolbarItem:(id)arg1;
- (BOOL)canValidateToolbarItem:(id)arg1;
- (BOOL)validateMenuItem:(id)arg1;
- (BOOL)canValidateMenuItem:(id)arg1;
- (void)unregisterAction:(SEL)arg1;
- (void)registerAction:(SEL)arg1 withValidationAction:(SEL)arg2;
- (void)registerActions;
- (id)init;

@end

