//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FNProductStatus;

@interface GTApplicationStatus : NSObject
{
    BOOL _betaRelease;
    BOOL _gettingStartedCompleted;
    BOOL _validProductStatus;
    BOOL _wasInValidProductStatusDuringRuntime;
    BOOL _wasInValidTrialStatusDuringRuntime;
    BOOL _wasInValidBetaStatusDuringRuntime;
    FNProductStatus *_productStatus;
}

+ (id)keyPathsForValuesAffectingProductStatusInitialized;
+ (id)sharedInstance;
- (void).cxx_destruct;
@property(nonatomic) BOOL wasInValidBetaStatusDuringRuntime; // @synthesize wasInValidBetaStatusDuringRuntime=_wasInValidBetaStatusDuringRuntime;
@property(nonatomic) BOOL wasInValidTrialStatusDuringRuntime; // @synthesize wasInValidTrialStatusDuringRuntime=_wasInValidTrialStatusDuringRuntime;
@property(nonatomic) BOOL wasInValidProductStatusDuringRuntime; // @synthesize wasInValidProductStatusDuringRuntime=_wasInValidProductStatusDuringRuntime;
@property(nonatomic, getter=isValidProductStatus) BOOL validProductStatus; // @synthesize validProductStatus=_validProductStatus;
@property(retain, nonatomic) FNProductStatus *productStatus; // @synthesize productStatus=_productStatus;
@property(nonatomic, getter=isGettingStartedCompleted) BOOL gettingStartedCompleted; // @synthesize gettingStartedCompleted=_gettingStartedCompleted;
@property(nonatomic, getter=isBetaRelease) BOOL betaRelease; // @synthesize betaRelease=_betaRelease;
- (void)updateProductStatus:(id)arg1;
- (BOOL)isUserAllowedToRunApplicationUntilNextRestart;
- (BOOL)isUserAuthorizedToRunApplication;
@property(readonly, nonatomic) BOOL canUseEnterpriseServices;
@property(readonly, nonatomic) BOOL mustCheckFeatureAvailability;

@end

