//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class GTAppleEvent, NSURL;

@protocol GTAppleEventURLHandler <NSObject>
- (BOOL)canHandleEventAction:(long long)arg1;
- (GTAppleEvent *)eventFromURL:(NSURL *)arg1;
- (BOOL)canHandleURL:(NSURL *)arg1;

@optional
- (NSURL *)URLFromEvent:(GTAppleEvent *)arg1;
@end

