//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSButton.h>

@class GTAvatarImageButtonOverlayView, GTAvatarImageLoader, GTBackgroundSession, GTStateManager, NSImage, NSMutableArray, NSString, NSURL;

@interface GTAvatarImageButton : NSButton
{
    NSImage *_placeholderImage;
    NSString *_gravatarEmailAddress;
    NSURL *_customAvatarImageURL;
    NSString *_avatarName;
    GTAvatarImageLoader *_avatarImageLoader;
    GTAvatarImageButtonOverlayView *_overlay;
    NSMutableArray *_customConstraints;
    GTBackgroundSession *_backgroundSession;
    GTStateManager *_viewState;
}

+ (Class)cellClass;
- (void).cxx_destruct;
@property(retain, nonatomic) GTStateManager *viewState; // @synthesize viewState=_viewState;
@property(retain, nonatomic) GTBackgroundSession *backgroundSession; // @synthesize backgroundSession=_backgroundSession;
@property(retain, nonatomic) NSMutableArray *customConstraints; // @synthesize customConstraints=_customConstraints;
@property(retain, nonatomic) GTAvatarImageButtonOverlayView *overlay; // @synthesize overlay=_overlay;
@property(retain, nonatomic) GTAvatarImageLoader *avatarImageLoader; // @synthesize avatarImageLoader=_avatarImageLoader;
@property(retain, nonatomic) NSString *avatarName; // @synthesize avatarName=_avatarName;
@property(retain, nonatomic) NSURL *customAvatarImageURL; // @synthesize customAvatarImageURL=_customAvatarImageURL;
@property(copy, nonatomic) NSString *gravatarEmailAddress; // @synthesize gravatarEmailAddress=_gravatarEmailAddress;
@property(retain, nonatomic) NSImage *placeholderImage; // @synthesize placeholderImage=_placeholderImage;
- (void)showPlaceholder;
- (BOOL)validateGravatarImage;
- (void)viewDidLoadAvatarImage:(id)arg1 task:(id)arg2;
- (void)viewDidChangeBackingProperties;
- (void)showMenu:(id)arg1;
- (void)updateAvatarName;
- (void)updateAvatarImage;
- (BOOL)needsUpdateAvatarName;
- (BOOL)needsUpdateAvatarImage;
- (void)updateViewState;
- (void)update;
- (void)updateConstraints;
- (void)awakeFromNib;
- (void)setAction:(SEL)arg1;
- (double)currentBackingScaleFactor;
- (id)gravatarImageURL;
@property(readonly, nonatomic) NSURL *avatarImageURL;
- (BOOL)usesCustomAvatarImage;
- (BOOL)usesGravatarImage;
- (double)avatarImageSize;
- (void)configureSubviews;
- (void)configureOverlay;
- (void)configureButton;
- (void)configureMenu;
- (void)configureDefaultValues;
- (void)commonInit;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

