//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

@class NSColor;

@interface GTAvatarImageButtonOverlayView : NSView
{
    BOOL _highlighted;
    NSColor *_borderColor;
    NSColor *_overlayColor;
}

- (void).cxx_destruct;
@property(nonatomic, getter=isHighlighted) BOOL highlighted; // @synthesize highlighted=_highlighted;
@property(retain, nonatomic) NSColor *overlayColor; // @synthesize overlayColor=_overlayColor;
@property(retain, nonatomic) NSColor *borderColor; // @synthesize borderColor=_borderColor;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)updateTrackingAreas;

@end

