//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

@class NSObject, NSStackView;
@protocol GTBadgesViewDataSource;

@interface GTBadgesView : NSView
{
    NSObject<GTBadgesViewDataSource> *_dataSource;
    NSStackView *_stackView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSStackView *stackView; // @synthesize stackView=_stackView;
@property(nonatomic) __weak NSObject<GTBadgesViewDataSource> *dataSource; // @synthesize dataSource=_dataSource;
- (void)insertViewForItem:(id)arg1;
- (void)removeAllBadges;
- (void)reloadData;
- (void)setNeedsDisplay:(BOOL)arg1;
- (struct CGSize)intrinsicContentSize;
- (void)commonInit;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

