//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTableCellView.h>

#import "GTViewStylesObserving-Protocol.h"

@class GTAvatarImageView, GTGitBlameAnnotationGroup, GTGitCommit, GTViewStylesObserver, NSColor, NSString;

@interface GTBlameAnnotationCellView : NSTableCellView <GTViewStylesObserving>
{
    GTAvatarImageView *_authorImageView;
    NSColor *_textColor;
    NSColor *_secondaryTextColor;
    GTViewStylesObserver *_viewStylesObserver;
}

+ (id)keyPathsForValuesAffectingSubject;
+ (id)keyPathsForValuesAffectingDate;
+ (id)keyPathsForValuesAffectingAuthorName;
+ (id)keyPathsForValuesAffectingCommit;
+ (id)keyPathsForValuesAffectingBlameAnnotationGroup;
+ (double)height;
- (void).cxx_destruct;
@property(retain, nonatomic) GTViewStylesObserver *viewStylesObserver; // @synthesize viewStylesObserver=_viewStylesObserver;
@property(retain, nonatomic) NSColor *secondaryTextColor; // @synthesize secondaryTextColor=_secondaryTextColor;
@property(retain, nonatomic) NSColor *textColor; // @synthesize textColor=_textColor;
@property(nonatomic) __weak GTAvatarImageView *authorImageView; // @synthesize authorImageView=_authorImageView;
- (void)viewStylesDidChangeWithNotification:(id)arg1;
- (void)viewDidMoveToWindow;
- (void)setObjectValue:(id)arg1;
@property(readonly, nonatomic) NSString *date;
@property(readonly, nonatomic) NSString *subject;
@property(readonly, nonatomic) NSString *authorName;
@property(readonly, nonatomic) GTGitCommit *commit;
@property(readonly, nonatomic) GTGitBlameAnnotationGroup *blameAnnotationGroup;

@end

