//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTViewController.h"

#import "GTBookmarksActions-Protocol.h"
#import "GTBookmarksDropZoneViewDelegate-Protocol.h"
#import "GTCloneActions-Protocol.h"

@class GTBookmark, GTBookmarksController, GTBookmarksDropZoneView, GTGitCloneController, NSColor, NSImage, NSImageView, NSStackView, NSString, NSTextField;

@interface GTBookmarksEmptySelectionViewController : GTViewController <GTBookmarksDropZoneViewDelegate, GTBookmarksActions, GTCloneActions>
{
    GTBookmark *_parentBookmark;
    GTBookmarksDropZoneView *_dropZoneView;
    NSTextField *_titleLabel;
    NSStackView *_actionButtonsView;
    NSImageView *_imageView;
    NSString *_titleText;
    NSImage *_iconImage;
    GTBookmarksController *_bookmarkController;
    GTGitCloneController *_cloneController;
}

- (void).cxx_destruct;
@property(retain, nonatomic) GTGitCloneController *cloneController; // @synthesize cloneController=_cloneController;
@property(retain, nonatomic) GTBookmarksController *bookmarkController; // @synthesize bookmarkController=_bookmarkController;
@property(retain, nonatomic) NSImage *iconImage; // @synthesize iconImage=_iconImage;
@property(retain, nonatomic) NSString *titleText; // @synthesize titleText=_titleText;
@property(nonatomic) __weak NSImageView *imageView; // @synthesize imageView=_imageView;
@property(nonatomic) __weak NSStackView *actionButtonsView; // @synthesize actionButtonsView=_actionButtonsView;
@property(nonatomic) __weak NSTextField *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak GTBookmarksDropZoneView *dropZoneView; // @synthesize dropZoneView=_dropZoneView;
@property(retain, nonatomic) GTBookmark *parentBookmark; // @synthesize parentBookmark=_parentBookmark;
- (void)cloneGitRepository:(id)arg1;
- (void)createRepository:(id)arg1;
- (void)addBookmark:(id)arg1;
- (void)dropZoneView:(id)arg1 didReceiveRemoteURLString:(id)arg2;
- (void)dropZoneView:(id)arg1 didReceiveFileURLs:(id)arg2;
- (void)viewWillDisappear;
- (void)viewDidAppear;
- (void)awakeFromNib;
- (void)viewDidLoad;
- (void)configureActionButtonsView;
- (void)configureTitleLabel;
@property(readonly) NSColor *textColor;
- (void)commonInit;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

