//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTActionSenderValidator.h"

@class NSArray;

@interface GTBookmarkActionsValidator : GTActionSenderValidator
{
    NSArray *_bookmarks;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *bookmarks; // @synthesize bookmarks=_bookmarks;
- (BOOL)validateAddBookmarkWithItem:(id)arg1;
- (BOOL)validateCreateRepository:(id)arg1;
- (BOOL)validateRenameBookmarkWithItem:(id)arg1;
- (BOOL)validateSortBookmarksInParentFolderByName:(id)arg1;
- (BOOL)validateSortChildBookmarksByNameWithItem:(id)arg1;
- (BOOL)validateDeleteBookmarksWithItem:(id)arg1;
- (BOOL)validateDeleteBookmarkWithItem:(id)arg1;
- (BOOL)validateOpenBookmarkWithItem:(id)arg1;
- (BOOL)validateOpenBookmarkInExternalAppWithItem:(id)arg1;
- (void)registerActions;

@end

