//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreData/NSManagedObject.h>

@class GTGitRepository, NSArray, NSOrderedSet, NSString;

@interface GTBookmark : NSManagedObject
{
}

+ (void)enumerateBookmarksRecursive:(id)arg1 stop:(char *)arg2 usingBlock:(CDUnknownBlockType)arg3;
+ (id)bookmarkWithManagedObjectContext:(id)arg1;
+ (id)bookmarkWithID:(id)arg1 managedObjectContext:(id)arg2 error:(id *)arg3;
+ (id)bookmarkWithTitle:(id)arg1 repository:(id)arg2 managedObjectContext:(id)arg3;
+ (id)bookmarkFolderWithTitle:(id)arg1 managedObjectContext:(id)arg2;
+ (id)rootBookmarkWithManagedObjectContext:(id)arg1;
+ (id)fetchRootBookmarkWithManagedObjectContext:(id)arg1 error:(id *)arg2;
+ (id)fetchOrCreateRootBookmarkWithManagedObjectContext:(id)arg1 error:(id *)arg2;
+ (id)fetchAllBookmarksWithManagedObjectContext:(id)arg1 error:(id *)arg2;
+ (id)fetchBookmarkWithIdentifier:(id)arg1 managedObjectContext:(id)arg2 error:(id *)arg3;
+ (id)keyPathsForValuesAffectingChildBookmarks;
+ (id)keyPathsForValuesAffectingHasChildren;
+ (id)keyPathsForValuesAffectingBookmark;
+ (id)keyPathsForValuesAffectingBookmarkFolder;
+ (id)keyPathsForValuesAffectingRootBookmark;
- (BOOL)validateRepository:(id *)arg1 error:(id *)arg2;
- (void)awakeFromInsert;
- (void)sortChildBookmarksByName;
- (void)enumerateChildBookmarksRecursiveUsingBlock:(CDUnknownBlockType)arg1;
- (BOOL)isDescendantOfBookmark:(id)arg1;
@property(readonly, nonatomic) unsigned long long level;
@property(readonly, nonatomic) unsigned long long sortingOrder;
@property(readonly, nonatomic) NSArray *childBookmarks;
@property(readonly, nonatomic) BOOL hasChildren;
@property(nonatomic) long long type; // @dynamic type;
@property(readonly, nonatomic, getter=isBookmark) BOOL bookmark;
@property(readonly, nonatomic, getter=isBookmarkFolder) BOOL bookmarkFolder;
@property(readonly, nonatomic, getter=isRootBookmark) BOOL rootBookmark;
- (void)removeChildren:(id)arg1;
- (void)addChildren:(id)arg1;
- (void)removeChildrenObject:(id)arg1;
- (void)addChildrenObject:(id)arg1;
- (void)moveChildrenAtIndexes:(id)arg1 toIndex:(unsigned long long)arg2;
- (void)replaceChildrenAtIndexes:(id)arg1 withChildren:(id)arg2;
- (void)replaceObjectInChildrenAtIndex:(unsigned long long)arg1 withObject:(id)arg2;
- (void)removeChildrenAtIndexes:(id)arg1;
- (void)insertChildren:(id)arg1 atIndexes:(id)arg2;
- (void)removeObjectFromChildrenAtIndex:(unsigned long long)arg1;
- (void)insertObject:(id)arg1 inChildrenAtIndex:(unsigned long long)arg2;

// Remaining properties
@property(retain, nonatomic) NSOrderedSet *children; // @dynamic children;
@property(retain, nonatomic) NSString *identifier; // @dynamic identifier;
@property(retain, nonatomic) NSString *name; // @dynamic name;
@property(retain, nonatomic) GTBookmark *parent; // @dynamic parent;
@property(retain, nonatomic) GTGitRepository *repository; // @dynamic repository;

@end

