//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FNListManagerDelegate-Protocol.h"

@class FNListManager, GTGitCloneActivityManager, NSArray, NSManagedObjectContext;
@protocol GTCloneActivityItemControllerDelegate;

@interface GTCloneActivityItemController : NSObject <FNListManagerDelegate>
{
    BOOL _reloading;
    BOOL _loading;
    NSManagedObjectContext *_managedObjectContext;
    id <GTCloneActivityItemControllerDelegate> _delegate;
    NSArray *_items;
    NSManagedObjectContext *_context;
    GTGitCloneActivityManager *_cloneActivityManager;
    FNListManager *_listManager;
}

+ (id)controllerWithManagedObjectContext:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) FNListManager *listManager; // @synthesize listManager=_listManager;
@property(retain, nonatomic) GTGitCloneActivityManager *cloneActivityManager; // @synthesize cloneActivityManager=_cloneActivityManager;
@property(getter=isLoading) BOOL loading; // @synthesize loading=_loading;
@property(retain, nonatomic) NSManagedObjectContext *context; // @synthesize context=_context;
@property(readonly, getter=isReloading) BOOL reloading; // @synthesize reloading=_reloading;
@property(retain, nonatomic) NSArray *items; // @synthesize items=_items;
@property(nonatomic) __weak id <GTCloneActivityItemControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) NSManagedObjectContext *managedObjectContext; // @synthesize managedObjectContext=_managedObjectContext;
- (void)controllerDidChangeItems;
- (void)controllerDidUpdateItemsAtIndexes:(id)arg1;
- (void)controllerDidMoveItemAtIndex:(unsigned long long)arg1 toIndex:(unsigned long long)arg2;
- (void)controllerDidInsertItemsAtIndexes:(id)arg1;
- (void)controllerDidDeleteItemsAtIndexes:(id)arg1;
- (void)controllerWillChangeItems;
- (void)controllerDidReloadItems;
- (void)listManagerDidMoveItemAtIndex:(unsigned long long)arg1 toIndex:(unsigned long long)arg2 list:(id)arg3;
- (void)listManagerDidInsertItemsAtIndexPaths:(id)arg1 list:(id)arg2;
- (void)listManagerDidDeleteItemsAtIndexPaths:(id)arg1 list:(id)arg2;
- (id)makeCloneActivityItems;
- (void)reload;
- (id)cloneActivitiesAtItemIndexes:(id)arg1;
- (void)dealloc;
- (id)initWithManagedObjectContext:(id)arg1;
- (id)init;

@end

