//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "GTGitCloneObserving-Protocol.h"
#import "NSPopoverDelegate-Protocol.h"

@class GTCloneActivityViewController, GTGitCloneObserver, GTGitCloningQueueProgress, NSButton, NSPopover, NSString;

@interface GTCloneActivityController : NSObject <GTGitCloneObserving, NSPopoverDelegate>
{
    NSButton *_cloneButton;
    NSPopover *_popover;
    GTCloneActivityViewController *_cloneActivityViewController;
    GTGitCloneObserver *_cloneObserver;
    GTGitCloningQueueProgress *_cloneProgress;
}

- (void).cxx_destruct;
@property(nonatomic) __weak GTGitCloningQueueProgress *cloneProgress; // @synthesize cloneProgress=_cloneProgress;
@property(retain, nonatomic) GTGitCloneObserver *cloneObserver; // @synthesize cloneObserver=_cloneObserver;
@property(retain, nonatomic) GTCloneActivityViewController *cloneActivityViewController; // @synthesize cloneActivityViewController=_cloneActivityViewController;
@property(retain, nonatomic) NSPopover *popover; // @synthesize popover=_popover;
@property(nonatomic) __weak NSButton *cloneButton; // @synthesize cloneButton=_cloneButton;
- (void)popoverDidClose:(id)arg1;
- (void)popoverWillShow:(id)arg1;
- (void)togglePopover:(id)arg1;
- (void)updateCloneButton;
- (void)cloneOverallProgressDidUpdate:(id)arg1;
- (void)stopObservingCloneActivities;
- (void)startObservingCloneActivities;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

