//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTableCellView.h>

@class GTCloneActivityItem, GTGitCloneActivity, NSImage, NSImageView, NSNumber, NSString;

@interface GTCloneActivityActiveCellView : NSTableCellView
{
    NSImageView *_folderImageView;
}

+ (id)keyPathsForValuesAffectingIndeterminate;
+ (id)keyPathsForValuesAffectingProgressValue;
+ (id)keyPathsForValuesAffectingProgressSummary;
+ (id)keyPathsForValuesAffectingTitle;
+ (id)keyPathsForValuesAffectingIcon;
+ (id)keyPathsForValuesAffectingCloneActivity;
+ (id)keyPathsForValuesAffectingCloneActivityItem;
+ (double)height;
- (void).cxx_destruct;
@property(nonatomic) __weak NSImageView *folderImageView; // @synthesize folderImageView=_folderImageView;
- (void)awakeFromNib;
@property(readonly, nonatomic, getter=isIndeterminate) BOOL indeterminate;
@property(readonly, nonatomic) NSNumber *maxProgressValue;
@property(readonly, nonatomic) NSNumber *minProgressValue;
@property(readonly, nonatomic) NSNumber *progressValue;
@property(readonly, nonatomic) NSString *progressSummary;
@property(readonly, nonatomic) NSString *cancelButtonToolTip;
@property(readonly, nonatomic) NSString *title;
@property(readonly, nonatomic) NSImage *icon;
@property(readonly, nonatomic) GTGitCloneActivity *cloneActivity;
@property(readonly, nonatomic) GTCloneActivityItem *cloneActivityItem;

@end

