//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTAutocompleteItem.h"

@class NSURL;

@interface GTCloneRepositoryAutocompleteItem : GTAutocompleteItem
{
    BOOL _progressInfo;
    long long _repositoryType;
    NSURL *_repositoryURL;
}

+ (id)stringRepresentationForCloneRepositoryAutocompleteItemType:(long long)arg1;
+ (id)infoItemWithText:(id)arg1 showsProgress:(BOOL)arg2;
+ (id)gitHubRepositoryItemWithGitHubRepository:(id)arg1;
+ (id)serviceRepositoryItemWithServiceRepository:(id)arg1;
- (void).cxx_destruct;
@property(nonatomic, getter=isProgressInfo) BOOL progressInfo; // @synthesize progressInfo=_progressInfo;
@property(retain, nonatomic) NSURL *repositoryURL; // @synthesize repositoryURL=_repositoryURL;
@property(nonatomic) long long repositoryType; // @synthesize repositoryType=_repositoryType;
- (id)description;
- (id)identifier;
- (BOOL)isEqual:(id)arg1;

@end

