//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTAbstractRepositoryViewController.h"

@class GTDiffImageDetailViewController, GTFileDiffViewController, GTGitFileRevision, GTRepositoryHeaderView, NSImage, NSView, NSViewController;

@interface GTCommitChangesetDiffViewController : GTAbstractRepositoryViewController
{
    GTGitFileRevision *_fileRevision;
    NSView *_contentView;
    GTRepositoryHeaderView *_headerView;
    GTFileDiffViewController *_diffViewController;
    GTDiffImageDetailViewController *_imageDiffViewController;
    NSViewController *_currentViewController;
}

+ (id)keyPathsForValuesAffectingFileIcon;
- (void).cxx_destruct;
@property(retain, nonatomic) NSViewController *currentViewController; // @synthesize currentViewController=_currentViewController;
@property(retain, nonatomic) GTDiffImageDetailViewController *imageDiffViewController; // @synthesize imageDiffViewController=_imageDiffViewController;
@property(retain, nonatomic) GTFileDiffViewController *diffViewController; // @synthesize diffViewController=_diffViewController;
@property(nonatomic) __weak GTRepositoryHeaderView *headerView; // @synthesize headerView=_headerView;
@property(nonatomic) __weak NSView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) GTGitFileRevision *fileRevision; // @synthesize fileRevision=_fileRevision;
- (void)displayViewController:(id)arg1;
- (void)openDiffTool:(id)arg1;
- (void)showFileHistory:(id)arg1;
- (void)showBlameView:(id)arg1;
- (void)showRawFile:(id)arg1;
- (void)updateActionBar;
- (void)updateDiffView;
- (BOOL)needsUpdateActionBar;
- (BOOL)needsUpdateDiffView;
- (void)updateViewComponents;
- (void)updateViewState;
- (void)prepareForUpdate;
- (void)viewWillDisappear;
- (void)viewDidAppear;
- (void)viewDidLoad;
- (void)configureActionBar;
- (void)configureContentView;
- (void)configure;
- (id)fileRevisionKey;
@property(readonly, nonatomic) NSImage *fileIcon;
- (void)dealloc;

@end

