//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "GTApplicationInitializing-Protocol.h"

@class GTCoreDataStore, NSString;

@interface GTCoreDataInitializer : NSObject <GTApplicationInitializing>
{
    BOOL _forceRestoreBackup;
    GTCoreDataStore *_coreDataStore;
}

- (void).cxx_destruct;
@property(retain, nonatomic) GTCoreDataStore *coreDataStore; // @synthesize coreDataStore=_coreDataStore;
@property(nonatomic) BOOL forceRestoreBackup; // @synthesize forceRestoreBackup=_forceRestoreBackup;
- (BOOL)performFailOverForCoreDataStore:(id *)arg1;
- (BOOL)shouldPerformFailOverForCoreDataError:(id)arg1;
- (void)uninitialize;
- (void)configureContexts;
- (BOOL)initialize:(id *)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

