//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTStackView.h"

@class NSArray;

@interface GTContributorsView : GTStackView
{
    NSArray *_contributors;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *contributors; // @synthesize contributors=_contributors;
- (void)update;

@end

