//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface GTCompareToolConfiguration : NSObject
{
    BOOL _supportsMerge;
    BOOL _supportsDiffChangeset;
    NSString *_identifier;
    NSString *_displayName;
    NSString *_applicationName;
    NSString *_applicationIdentifier;
    NSString *_launchScript;
}

+ (id)configurationWithDictionary:(id)arg1;
+ (BOOL)validateConfiguration:(id)arg1 error:(id *)arg2;
- (void).cxx_destruct;
@property(nonatomic) BOOL supportsDiffChangeset; // @synthesize supportsDiffChangeset=_supportsDiffChangeset;
@property(nonatomic) BOOL supportsMerge; // @synthesize supportsMerge=_supportsMerge;
@property(retain, nonatomic) NSString *launchScript; // @synthesize launchScript=_launchScript;
@property(retain, nonatomic) NSString *applicationIdentifier; // @synthesize applicationIdentifier=_applicationIdentifier;
@property(retain, nonatomic) NSString *applicationName; // @synthesize applicationName=_applicationName;
@property(retain, nonatomic) NSString *displayName; // @synthesize displayName=_displayName;
@property(retain, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;

@end

