//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTGPGKeyOperation.h"

@class NSManagedObjectID, NSString;

@interface GTCreateRealGPGKeyOperation : GTGPGKeyOperation
{
    NSString *_username;
    NSString *_email;
    NSString *_password;
    NSManagedObjectID *_createdGPGKeyID;
}

+ (id)operationWithManagedObjectContext:(id)arg1 username:(id)arg2 email:(id)arg3 password:(id)arg4;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSManagedObjectID *createdGPGKeyID; // @synthesize createdGPGKeyID=_createdGPGKeyID;
@property(readonly, nonatomic) NSString *password; // @synthesize password=_password;
@property(readonly, nonatomic) NSString *email; // @synthesize email=_email;
@property(readonly, nonatomic) NSString *username; // @synthesize username=_username;
- (void)execute;
- (id)initWithManagedObjectContext:(id)arg1 username:(id)arg2 email:(id)arg3 password:(id)arg4;

@end

