//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTDialogueViewController.h"

#import "GTGitRepositoryObserving-Protocol.h"
#import "GTUserDefaultsKeyObserving-Protocol.h"

@class GTGitCreateBranchActionValidator, GTGitRepository, GTGitRepositoryObserver, GTUserDefaultsKeyObserver, NSArray, NSButton, NSString;

@interface GTCreateNewBranchViewController : GTDialogueViewController <GTGitRepositoryObserving, GTUserDefaultsKeyObserving>
{
    BOOL _tracksBranch;
    BOOL _workingTreeIsUpdating;
    BOOL _checkOutBranchOptionChecked;
    GTGitRepository *_repository;
    NSArray *_refs;
    NSString *_refName;
    NSString *_startingRevision;
    NSButton *_checkOutBranchCheckbox;
    GTGitCreateBranchActionValidator *_validator;
    GTGitRepositoryObserver *_repositoryObserver;
    GTUserDefaultsKeyObserver *_userDefaultsObserver;
}

+ (id)keyPathsForValuesAffectingValidatesSubmitButton;
+ (id)keyPathsForValuesAffectingCanTrackBranch;
+ (id)keyPathsForValuesAffectingTrackBranchOptionTitle;
- (void).cxx_destruct;
@property(nonatomic) BOOL checkOutBranchOptionChecked; // @synthesize checkOutBranchOptionChecked=_checkOutBranchOptionChecked;
@property(nonatomic) BOOL workingTreeIsUpdating; // @synthesize workingTreeIsUpdating=_workingTreeIsUpdating;
@property(retain, nonatomic) GTUserDefaultsKeyObserver *userDefaultsObserver; // @synthesize userDefaultsObserver=_userDefaultsObserver;
@property(retain, nonatomic) GTGitRepositoryObserver *repositoryObserver; // @synthesize repositoryObserver=_repositoryObserver;
@property(retain, nonatomic) GTGitCreateBranchActionValidator *validator; // @synthesize validator=_validator;
@property(nonatomic) __weak NSButton *checkOutBranchCheckbox; // @synthesize checkOutBranchCheckbox=_checkOutBranchCheckbox;
@property(nonatomic) BOOL tracksBranch; // @synthesize tracksBranch=_tracksBranch;
@property(retain, nonatomic) NSString *startingRevision; // @synthesize startingRevision=_startingRevision;
@property(retain, nonatomic) NSString *refName; // @synthesize refName=_refName;
@property(retain, nonatomic) NSArray *refs; // @synthesize refs=_refs;
@property(retain, nonatomic) GTGitRepository *repository; // @synthesize repository=_repository;
- (void)userDefaultsDidChangeKey:(id)arg1 change:(id)arg2;
- (void)repositoryDidUpdateWorkingTree:(id)arg1;
- (void)repositoryDidUpdateWorkingCopy:(id)arg1;
- (BOOL)submitDialogue:(id *)arg1;
- (void)updateSelection;
- (void)loadRefs;
@property(readonly, nonatomic) NSString *trackedRefName;
- (BOOL)validatesSubmitButton;
- (void)viewWillDisappear;
- (void)viewWillAppear;
- (void)viewDidLoad;
@property(readonly, nonatomic) NSString *trackBranchOptionTitle;
@property(readonly, nonatomic) BOOL canTrackBranch;
@property(readonly, nonatomic) unsigned long long createBranchOptions;
@property(readonly, nonatomic) BOOL checksOutBranch;
- (void)commonInit;
- (id)initWithRepository:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

