//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTableCellView.h>

@class FNGitDiff, GTDiffHeaderContentView, GTDiffSummaryGenerator, NSColor;

@interface GTDiffHeaderCellView : NSTableCellView
{
    GTDiffHeaderContentView *_contentView;
    FNGitDiff *_diff;
    GTDiffSummaryGenerator *_diffSummaryGenerator;
    NSColor *_borderColor;
}

+ (struct CGSize)sizeWithDiff:(id)arg1 maxWidth:(double)arg2;
- (void).cxx_destruct;
@property(retain, nonatomic) NSColor *borderColor; // @synthesize borderColor=_borderColor;
@property(retain, nonatomic) GTDiffSummaryGenerator *diffSummaryGenerator; // @synthesize diffSummaryGenerator=_diffSummaryGenerator;
@property(retain, nonatomic) FNGitDiff *diff; // @synthesize diff=_diff;
@property(retain, nonatomic) GTDiffHeaderContentView *contentView; // @synthesize contentView=_contentView;
- (void)reloadView;
- (void)setObjectValue:(id)arg1;
- (void)commonInit;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

