//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTAbstractViewStyles.h"

@class NSColor, NSFont;

@interface GTDiffImageViewStyles : GTAbstractViewStyles
{
    NSColor *_backgroundColor;
    NSColor *_topLabelColor;
    NSColor *_bottomLabelColor;
    NSColor *_checkerboardSquareColor;
    NSColor *_checkerboardBackgroundColor;
    NSColor *_imageBorderColor;
    NSFont *_topLabelFont;
    NSFont *_bottomLabelFont;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSFont *bottomLabelFont; // @synthesize bottomLabelFont=_bottomLabelFont;
@property(retain, nonatomic) NSFont *topLabelFont; // @synthesize topLabelFont=_topLabelFont;
@property(retain, nonatomic) NSColor *imageBorderColor; // @synthesize imageBorderColor=_imageBorderColor;
@property(retain, nonatomic) NSColor *checkerboardBackgroundColor; // @synthesize checkerboardBackgroundColor=_checkerboardBackgroundColor;
@property(retain, nonatomic) NSColor *checkerboardSquareColor; // @synthesize checkerboardSquareColor=_checkerboardSquareColor;
@property(retain, nonatomic) NSColor *bottomLabelColor; // @synthesize bottomLabelColor=_bottomLabelColor;
@property(retain, nonatomic) NSColor *topLabelColor; // @synthesize topLabelColor=_topLabelColor;
@property(retain, nonatomic) NSColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
- (void)loadViewStyles;

@end

