//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTableCellView.h>

#import "FNViewAppearance-Protocol.h"
#import "GTDiffChunkLineNumbersViewDelegate-Protocol.h"
#import "GTWindowObserving-Protocol.h"

@class FNGitDiffChunk, GTDiffChunkView, GTWindowObserver, NSArray, NSIndexSet, NSString, NSTrackingArea;
@protocol GTDiffChunkContentCellViewDelegate;

@interface GTDiffChunkContentCellView : NSTableCellView <GTWindowObserving, FNViewAppearance, GTDiffChunkLineNumbersViewDelegate>
{
    BOOL _editable;
    BOOL _drawsBackground;
    id <GTDiffChunkContentCellViewDelegate> _delegate;
    FNGitDiffChunk *_diffChunk;
    unsigned long long _diffChunkIndex;
    GTDiffChunkView *_diffChunkView;
    NSIndexSet *_selectedLineIndexes;
    NSArray *_constraints;
    NSTrackingArea *_trackingArea;
    GTWindowObserver *_windowObserver;
}

+ (struct CGSize)sizeWithDiffChunk:(id)arg1 maxWidth:(double)arg2;
- (void).cxx_destruct;
@property(retain, nonatomic) GTWindowObserver *windowObserver; // @synthesize windowObserver=_windowObserver;
@property(retain, nonatomic) NSTrackingArea *trackingArea; // @synthesize trackingArea=_trackingArea;
@property(retain, nonatomic) NSArray *constraints; // @synthesize constraints=_constraints;
@property(retain, nonatomic) NSIndexSet *selectedLineIndexes; // @synthesize selectedLineIndexes=_selectedLineIndexes;
@property(retain, nonatomic) GTDiffChunkView *diffChunkView; // @synthesize diffChunkView=_diffChunkView;
@property(nonatomic) BOOL drawsBackground; // @synthesize drawsBackground=_drawsBackground;
@property(nonatomic, getter=isEditable) BOOL editable; // @synthesize editable=_editable;
@property(nonatomic) unsigned long long diffChunkIndex; // @synthesize diffChunkIndex=_diffChunkIndex;
@property(retain, nonatomic) FNGitDiffChunk *diffChunk; // @synthesize diffChunk=_diffChunk;
@property(nonatomic) __weak id <GTDiffChunkContentCellViewDelegate> delegate; // @synthesize delegate=_delegate;
- (struct CGRect)diffChunkLineNumbersView:(id)arg1 drawingRectForLineContentAtIndex:(unsigned long long)arg2;
- (void)diffChunkLineNumbersView:(id)arg1 didChangeLineSelection:(id)arg2;
- (void)diffChunkLineNumbersView:(id)arg1 didDeselectLinesAtIndexes:(id)arg2;
- (void)diffChunkLineNumbersView:(id)arg1 didSelectLinesAtIndexes:(id)arg2;
- (void)reloadView;
- (void)updateTrackingAreas;
- (void)updateConstraints;
- (void)setLineSelection:(id)arg1;
- (id)lineSelection;
- (BOOL)canApplyLineSelection:(id)arg1;
- (void)mouseMoved:(id)arg1;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)windowDidExitFullScreen:(id)arg1;
- (void)windowDidEnterFullScreen:(id)arg1;
- (void)viewDidMoveToWindow;
- (void)viewWillMoveToWindow:(id)arg1;
- (void)setObjectValue:(id)arg1;
- (void)initChunkView;
- (void)prepareForReuse;
- (void)dealloc;
- (void)commonInit;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

