//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData, NSString;

@interface GTDiffImageData : NSObject
{
    NSString *_addedImageRevision;
    NSString *_deletedImageRevision;
    NSData *_addedImageData;
    NSData *_deletedImageData;
}

+ (id)diffImageDataWithAddedRevision:(id)arg1 deletedRevision:(id)arg2 addedImageData:(id)arg3 deletedImageData:(id)arg4;
- (void).cxx_destruct;
@property(retain, nonatomic) NSData *deletedImageData; // @synthesize deletedImageData=_deletedImageData;
@property(retain, nonatomic) NSData *addedImageData; // @synthesize addedImageData=_addedImageData;
@property(retain, nonatomic) NSString *deletedImageRevision; // @synthesize deletedImageRevision=_deletedImageRevision;
@property(retain, nonatomic) NSString *addedImageRevision; // @synthesize addedImageRevision=_addedImageRevision;
- (id)initWithAddedRevision:(id)arg1 deletedRevision:(id)arg2 addedImageData:(id)arg3 deletedImageData:(id)arg4;

@end

