//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class GTDiffChunkLineNumbersView, NSIndexSet;

@protocol GTDiffChunkLineNumbersViewDelegate <NSObject>
- (struct CGRect)diffChunkLineNumbersView:(GTDiffChunkLineNumbersView *)arg1 drawingRectForLineContentAtIndex:(unsigned long long)arg2;

@optional
- (void)diffChunkLineNumbersView:(GTDiffChunkLineNumbersView *)arg1 didChangeLineSelection:(NSIndexSet *)arg2;
- (void)diffChunkLineNumbersView:(GTDiffChunkLineNumbersView *)arg1 didDeselectLinesAtIndexes:(NSIndexSet *)arg2;
- (void)diffChunkLineNumbersView:(GTDiffChunkLineNumbersView *)arg1 didSelectLinesAtIndexes:(NSIndexSet *)arg2;
@end

