//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTDialogueViewController.h"

#import "GTGitComposeCommitControllerDelegate-Protocol.h"

@class GTGitCommit, GTGitComposeCommitController, GTGitRepository, NSString, NSTextField;

@interface GTEditCommitMessageDialogueViewController : GTDialogueViewController <GTGitComposeCommitControllerDelegate>
{
    GTGitRepository *_repository;
    GTGitCommit *_commit;
    NSTextField *_commitSubjectTextField;
    NSTextField *_commitBodyTextField;
    GTGitComposeCommitController *_composeCommitController;
}

+ (id)keyPathsForValuesAffectingLoading;
+ (id)keyPathsForValuesAffectingValidatesSubmitButton;
- (void).cxx_destruct;
@property(retain, nonatomic) GTGitComposeCommitController *composeCommitController; // @synthesize composeCommitController=_composeCommitController;
@property(nonatomic) __weak NSTextField *commitBodyTextField; // @synthesize commitBodyTextField=_commitBodyTextField;
@property(nonatomic) __weak NSTextField *commitSubjectTextField; // @synthesize commitSubjectTextField=_commitSubjectTextField;
@property(retain, nonatomic) GTGitCommit *commit; // @synthesize commit=_commit;
@property(retain, nonatomic) GTGitRepository *repository; // @synthesize repository=_repository;
- (BOOL)control:(id)arg1 textView:(id)arg2 doCommandBySelector:(SEL)arg3;
- (BOOL)validatesSubmitButton;
- (void)updateTitleAndText;
- (void)update;
- (void)viewDidLoad;
@property(readonly, nonatomic, getter=isLoading) BOOL loading;
@property(readonly, nonatomic) NSString *commitMessage;
- (void)commonInit;
- (id)initWithRepository:(id)arg1 commit:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

