//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTDialogueViewController.h"

@class GTGitRemote, GTGitRepository, NSArray, NSButton, NSUserDefaults;

@interface GTFetchRemoteViewController : GTDialogueViewController
{
    GTGitRepository *_repository;
    NSButton *_pruneObsoleteRemoteBranchesCheckbox;
    NSArray *_remotes;
    GTGitRemote *_selectedRemote;
    NSUserDefaults *_userDefaults;
}

+ (id)keyPathsForValuesAffectingValidatesSubmitButton;
+ (id)keyPathsForValuesAffectingRecursesSubmodules;
+ (id)keyPathsForValuesAffectingPrunesObsoleteRemoteBranches;
+ (id)keyPathsForValuesAffectingFetchesAllTags;
+ (id)keyPathsForValuesAffectingFetchesAllRemotes;
- (void).cxx_destruct;
@property(retain, nonatomic) NSUserDefaults *userDefaults; // @synthesize userDefaults=_userDefaults;
@property(retain, nonatomic) GTGitRemote *selectedRemote; // @synthesize selectedRemote=_selectedRemote;
@property(retain, nonatomic) NSArray *remotes; // @synthesize remotes=_remotes;
@property(nonatomic) __weak NSButton *pruneObsoleteRemoteBranchesCheckbox; // @synthesize pruneObsoleteRemoteBranchesCheckbox=_pruneObsoleteRemoteBranchesCheckbox;
@property(retain, nonatomic) GTGitRepository *repository; // @synthesize repository=_repository;
- (unsigned long long)fetchOptions;
- (void)updateRemotePreselection;
- (void)loadRemotes;
- (BOOL)validatesSubmitButton;
- (void)viewDidDisappear;
- (void)viewDidAppear;
- (void)viewDidLoad;
@property(readonly, nonatomic) BOOL recursesSubmodules;
@property(readonly, nonatomic) BOOL prunesObsoleteRemoteBranches;
@property(readonly, nonatomic) BOOL fetchesAllTags;
@property(readonly, nonatomic) BOOL fetchesAllRemotes;
- (void)commonInit;
- (id)initWithRepository:(id)arg1;

@end

