//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSFont;

@interface GTFileStatusIconDrawer : NSObject
{
    BOOL _highlighted;
    NSFont *_symbolFont;
    double _borderRadiusX;
    double _borderRadiusY;
    unsigned long long _fileStatus;
}

- (void).cxx_destruct;
@property(nonatomic, getter=isHighlighted) BOOL highlighted; // @synthesize highlighted=_highlighted;
@property(nonatomic) unsigned long long fileStatus; // @synthesize fileStatus=_fileStatus;
@property(nonatomic) double borderRadiusY; // @synthesize borderRadiusY=_borderRadiusY;
@property(nonatomic) double borderRadiusX; // @synthesize borderRadiusX=_borderRadiusX;
@property(retain, nonatomic) NSFont *symbolFont; // @synthesize symbolFont=_symbolFont;
- (id)symbolForFileStatus:(unsigned long long)arg1;
- (id)textColorForFileStatus:(unsigned long long)arg1;
- (id)borderColorForFileStatus:(unsigned long long)arg1;
- (id)backgroundColorForFileStatus:(unsigned long long)arg1;
- (id)textAttributesForFileStatus:(unsigned long long)arg1;
- (void)drawBackgroundForFileStatus:(unsigned long long)arg1 inRect:(struct CGRect)arg2;
- (void)drawTextForFileStatus:(unsigned long long)arg1 inRect:(struct CGRect)arg2;
- (void)drawInRect:(struct CGRect)arg1;
- (id)init;

@end

