//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTAbstractRepositoryViewController.h"

#import "GTFileHistoryTimelineViewControllerDelegate-Protocol.h"
#import "GTNavigationComponent-Protocol.h"
#import "GTRepositoryFileHistoryActions-Protocol.h"
#import "NSSplitViewDelegate-Protocol.h"

@class GTBackgroundSession, GTEmptyViewController, GTFileHistoryDetailViewController, GTFileHistoryTimelineViewController, GTGitHistoryManager, GTRepositoryFileHistoryTouchBarController, NSArray, NSSplitView, NSString, NSTimer, NSURL, NSView, NSViewController;

@interface GTFileHistoryViewController : GTAbstractRepositoryViewController <NSSplitViewDelegate, GTFileHistoryTimelineViewControllerDelegate, GTNavigationComponent, GTRepositoryFileHistoryActions>
{
    NSString *_filePath;
    NSString *_revision;
    NSSplitView *_splitView;
    NSView *_masterView;
    NSView *_detailView;
    GTFileHistoryTimelineViewController *_timelineViewController;
    GTFileHistoryDetailViewController *_detailViewController;
    GTEmptyViewController *_emptyViewController;
    NSViewController *_currentViewController;
    GTRepositoryFileHistoryTouchBarController *_touchBarController;
    GTGitHistoryManager *_historyManager;
    NSArray *_selectedRevisions;
    GTBackgroundSession *_backgroundSession;
    NSString *_detailFilePath;
    NSTimer *_touchBarValidationTimer;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSTimer *touchBarValidationTimer; // @synthesize touchBarValidationTimer=_touchBarValidationTimer;
@property(retain, nonatomic) NSString *detailFilePath; // @synthesize detailFilePath=_detailFilePath;
@property(retain, nonatomic) GTBackgroundSession *backgroundSession; // @synthesize backgroundSession=_backgroundSession;
@property(retain, nonatomic) NSArray *selectedRevisions; // @synthesize selectedRevisions=_selectedRevisions;
@property(retain, nonatomic) GTGitHistoryManager *historyManager; // @synthesize historyManager=_historyManager;
@property(retain, nonatomic) GTRepositoryFileHistoryTouchBarController *touchBarController; // @synthesize touchBarController=_touchBarController;
@property(retain, nonatomic) NSViewController *currentViewController; // @synthesize currentViewController=_currentViewController;
@property(retain, nonatomic) GTEmptyViewController *emptyViewController; // @synthesize emptyViewController=_emptyViewController;
@property(retain, nonatomic) GTFileHistoryDetailViewController *detailViewController; // @synthesize detailViewController=_detailViewController;
@property(retain, nonatomic) GTFileHistoryTimelineViewController *timelineViewController; // @synthesize timelineViewController=_timelineViewController;
@property(nonatomic) __weak NSView *detailView; // @synthesize detailView=_detailView;
@property(nonatomic) __weak NSView *masterView; // @synthesize masterView=_masterView;
@property(nonatomic) __weak NSSplitView *splitView; // @synthesize splitView=_splitView;
@property(retain, nonatomic) NSString *revision; // @synthesize revision=_revision;
@property(retain, nonatomic) NSString *filePath; // @synthesize filePath=_filePath;
- (void)displayViewController:(id)arg1;
- (void)repositoryDidUpdateBranches:(id)arg1;
- (id)makeTouchBar;
- (void)fileHistoryTimelineViewControllerDidChangeSelection:(id)arg1;
- (void)splitViewDidResizeSubviews:(id)arg1;
- (void)showDiffToolForFileAtRevision:(id)arg1;
- (void)showRawFileAtRevision:(id)arg1;
- (void)showBlameForRevision:(id)arg1;
- (void)showCommitForRevision:(id)arg1;
- (void)showFileSelector:(id)arg1;
- (void)updateWindowTitle;
- (void)updateDetailView;
- (void)updateTimelineView;
- (void)updateHistoryManager;
- (void)updateNavigationController;
- (BOOL)needsUpdateWindowTitle;
- (BOOL)needsUpdateDetailView;
- (BOOL)needsUpdateTimelineView;
- (BOOL)needsUpdateHistoryManager;
- (BOOL)needsUpdateNavigationController;
- (void)updateViewComponents;
- (void)updateViewState;
- (void)prepareForUpdate;
- (void)windowDidUpdate:(id)arg1;
- (void)viewDidDisappear;
- (void)viewWillDisappear;
- (void)viewDidAppear;
- (void)viewDidLoad;
- (void)configureSplitView;
- (void)configure;
@property(readonly, nonatomic) NSArray *navigationPathComponents;
@property(readonly, nonatomic) NSURL *navigationURL;
@property(readonly, nonatomic) NSString *navigationIdentifier;
@property(readonly, nonatomic) NSString *checkFilePathTaskName;
@property(readonly, nonatomic) NSString *selectedRevisionsKey;
@property(readonly, nonatomic) NSString *detailFilePathKey;
- (id)revisionKey;
@property(readonly, nonatomic) NSString *filePathKey;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

