//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTableCellView.h>

@class GTHistoryDateGroupItem, GTTimelineGraphView, NSColor, NSLayoutConstraint, NSString;

@interface GTFileHistoryTimelineGroupCellView : NSTableCellView
{
    BOOL _drawsTimeline;
    double _lineOffset;
    NSString *_shortMonthName;
    NSLayoutConstraint *_timelineWidthConstraint;
    GTTimelineGraphView *_timelineView;
}

+ (id)keyPathsForValuesAffectingTitle;
+ (id)keyPathsForValuesAffectingItem;
+ (double)height;
- (void).cxx_destruct;
@property(nonatomic) __weak GTTimelineGraphView *timelineView; // @synthesize timelineView=_timelineView;
@property(retain, nonatomic) NSLayoutConstraint *timelineWidthConstraint; // @synthesize timelineWidthConstraint=_timelineWidthConstraint;
@property(readonly, nonatomic) NSString *shortMonthName; // @synthesize shortMonthName=_shortMonthName;
@property(nonatomic) BOOL drawsTimeline; // @synthesize drawsTimeline=_drawsTimeline;
@property(nonatomic) double lineOffset; // @synthesize lineOffset=_lineOffset;
- (id)monthGroupTitle;
- (id)weekGroupTitle;
- (id)dayGroupTitle;
- (void)configureTimelineView;
- (BOOL)needsDrawTimeline;
- (void)prepareForReuse;
- (void)setObjectValue:(id)arg1;
- (void)awakeFromNib;
@property(readonly, nonatomic) NSColor *lineColor;
- (id)fontColor;
- (id)font;
- (id)title;
@property(readonly, nonatomic) GTHistoryDateGroupItem *item;

@end

