//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTableCellView.h>

@class NSColor, NSFont, NSImage, NSString;

@interface GTGettingStartedSidebarCellView : NSTableCellView
{
    BOOL _finished;
    BOOL _done;
    BOOL _usesImageTemplates;
    NSFont *_textFont;
    NSColor *_textColor;
    NSColor *_borderColor;
    double _borderWidth;
}

+ (id)keyPathsForValuesAffectingImage;
+ (id)keyPathsForValuesAffectingTitle;
+ (double)height;
- (void).cxx_destruct;
@property(nonatomic) BOOL usesImageTemplates; // @synthesize usesImageTemplates=_usesImageTemplates;
@property(nonatomic) BOOL done; // @synthesize done=_done;
@property(nonatomic, getter=isFinished) BOOL finished; // @synthesize finished=_finished;
@property(nonatomic) double borderWidth; // @synthesize borderWidth=_borderWidth;
@property(retain, nonatomic) NSColor *borderColor; // @synthesize borderColor=_borderColor;
@property(retain, nonatomic) NSColor *textColor; // @synthesize textColor=_textColor;
@property(retain, nonatomic) NSFont *textFont; // @synthesize textFont=_textFont;
- (void)drawBorderInRect:(struct CGRect)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)setBackgroundStyle:(long long)arg1;
@property(readonly, nonatomic) NSImage *image;
@property(readonly, nonatomic) NSString *title;
- (BOOL)allowsVibrancy;
- (void)awakeFromNib;
- (void)commonInit;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

