//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FNAppKit/FNViewController.h>

#import "FNNavigationViewControllerDelegate-Protocol.h"

@class FNNavigationViewController, GTGettingStartedGitViewController, GTGettingStartedRepositoriesViewController, GTGettingStartedServicesViewController, GTGettingStartedSidebarViewController, GTGettingStartedTourViewController, GTServiceAccountController, NSArray, NSString, NSView;

@interface GTGettingStartedViewController : FNViewController <FNNavigationViewControllerDelegate>
{
    BOOL _canGoBack;
    BOOL _animating;
    NSView *_sidebarView;
    NSView *_detailView;
    NSString *_nextButtonTitle;
    FNNavigationViewController *_navigationController;
    GTGettingStartedSidebarViewController *_sidebarViewController;
    GTGettingStartedGitViewController *_gitViewController;
    GTGettingStartedServicesViewController *_servicesViewController;
    GTGettingStartedRepositoriesViewController *_repositoriesViewController;
    GTGettingStartedTourViewController *_tourViewController;
    GTServiceAccountController *_serviceAccountController;
    NSArray *_controllerStack;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *controllerStack; // @synthesize controllerStack=_controllerStack;
@property(retain, nonatomic) GTServiceAccountController *serviceAccountController; // @synthesize serviceAccountController=_serviceAccountController;
@property(retain, nonatomic) GTGettingStartedTourViewController *tourViewController; // @synthesize tourViewController=_tourViewController;
@property(retain, nonatomic) GTGettingStartedRepositoriesViewController *repositoriesViewController; // @synthesize repositoriesViewController=_repositoriesViewController;
@property(retain, nonatomic) GTGettingStartedServicesViewController *servicesViewController; // @synthesize servicesViewController=_servicesViewController;
@property(retain, nonatomic) GTGettingStartedGitViewController *gitViewController; // @synthesize gitViewController=_gitViewController;
@property(retain, nonatomic) GTGettingStartedSidebarViewController *sidebarViewController; // @synthesize sidebarViewController=_sidebarViewController;
@property(retain, nonatomic) FNNavigationViewController *navigationController; // @synthesize navigationController=_navigationController;
@property(nonatomic, getter=isAnimating) BOOL animating; // @synthesize animating=_animating;
@property(retain, nonatomic) NSString *nextButtonTitle; // @synthesize nextButtonTitle=_nextButtonTitle;
@property(nonatomic) BOOL canGoBack; // @synthesize canGoBack=_canGoBack;
@property(nonatomic) __weak NSView *detailView; // @synthesize detailView=_detailView;
@property(nonatomic) __weak NSView *sidebarView; // @synthesize sidebarView=_sidebarView;
- (void)controllerDidTriggeredPrev;
- (void)controllerDidTriggeredNext;
- (void)setButtonTitleForIndex:(long long)arg1;
- (void)selectionDidChange:(long long)arg1;
- (void)navigationViewController:(id)arg1 willShowViewController:(id)arg2 animated:(BOOL)arg3;
- (void)navigationViewController:(id)arg1 didShowViewController:(id)arg2 animated:(BOOL)arg3;
- (void)next:(id)arg1;
- (void)prev:(id)arg1;
- (void)viewWillDisappear;
- (void)viewDidAppear;
- (void)viewDidLoad;
- (void)commonInit;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

