//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface GTGitBranchInfo : NSObject
{
    NSString *_name;
    NSString *_commitHash;
    NSString *_upstream;
    NSString *_fullRefName;
}

+ (id)branchInfoWithName:(id)arg1 commitHash:(id)arg2 upstream:(id)arg3;
+ (id)branchInfoWithBranch:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *fullRefName; // @synthesize fullRefName=_fullRefName;
@property(retain, nonatomic) NSString *upstream; // @synthesize upstream=_upstream;
@property(retain, nonatomic) NSString *commitHash; // @synthesize commitHash=_commitHash;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
- (id)initWithName:(id)arg1 commitHash:(id)arg2 upstream:(id)arg3;

@end

