//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTGitCloneAction.h"

@class GTBookmark, GTGitRepository, GTGitRepositoryManager, NSArray;

@interface GTGitCancelCloneActivitiesAction : GTGitCloneAction
{
    NSArray *_cloneActivities;
    GTGitRepositoryManager *_repositoryManager;
    GTGitRepository *_repository;
    GTBookmark *_bookmark;
}

- (void).cxx_destruct;
@property(retain, nonatomic) GTBookmark *bookmark; // @synthesize bookmark=_bookmark;
@property(retain, nonatomic) GTGitRepository *repository; // @synthesize repository=_repository;
@property(retain, nonatomic) GTGitRepositoryManager *repositoryManager; // @synthesize repositoryManager=_repositoryManager;
@property(retain, nonatomic) NSArray *cloneActivities; // @synthesize cloneActivities=_cloneActivities;
- (void)actionDidFinish;
- (void)actionDidFailWithError:(id)arg1;
- (void)main;

@end

