//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSError, NSManagedObjectID, NSString;

@interface GTGitRemoteActivityInfo : NSObject
{
    NSString *_identifier;
    NSManagedObjectID *_remoteID;
    NSManagedObjectID *_repositoryID;
    NSString *_remoteURLString;
    long long _status;
    long long _type;
    NSString *_refSpec;
    NSError *_error;
    NSString *_output;
}

+ (id)errorRemoteActivityInfoWithIdentifier:(id)arg1 output:(id)arg2 error:(id)arg3;
+ (id)finishedRemoteActivityInfoWithIdentifier:(id)arg1 output:(id)arg2;
+ (id)cancelledRemoteActivityInfoWithIdentifier:(id)arg1;
+ (id)activeRemoteActivityInfoWithIdentifier:(id)arg1 remoteURLString:(id)arg2 type:(long long)arg3 refSpec:(id)arg4 repositoryID:(id)arg5;
+ (id)activeRemoteActivityInfoWithIdentifier:(id)arg1 remoteID:(id)arg2 type:(long long)arg3 refSpec:(id)arg4;
+ (id)refSpecFromRemoteOperation:(id)arg1;
+ (id)remoteActivityInfoWithRemoteOperation:(id)arg1;
+ (id)refSpecFromRemoteURLOperation:(id)arg1;
+ (id)remoteActivityInfoWithRemoteURLOperation:(id)arg1;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *output; // @synthesize output=_output;
@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
@property(copy, nonatomic) NSString *refSpec; // @synthesize refSpec=_refSpec;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(nonatomic) long long status; // @synthesize status=_status;
@property(copy, nonatomic) NSString *remoteURLString; // @synthesize remoteURLString=_remoteURLString;
@property(retain, nonatomic) NSManagedObjectID *repositoryID; // @synthesize repositoryID=_repositoryID;
@property(retain, nonatomic) NSManagedObjectID *remoteID; // @synthesize remoteID=_remoteID;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;

@end

