//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, NSDictionary, NSError, NSManagedObjectID, NSString;

@interface GTGitRepositoryActivityInfo : NSObject
{
    NSString *_identifier;
    NSString *_name;
    NSDate *_dateStarted;
    NSDate *_dateFinished;
    NSDictionary *_parameters;
    long long _status;
    long long _operationType;
    NSManagedObjectID *_repositoryID;
    NSError *_error;
    NSString *_output;
}

+ (id)repositoryActivityInfoWithRepositoryOperation:(id)arg1;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *output; // @synthesize output=_output;
@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
@property(retain, nonatomic) NSManagedObjectID *repositoryID; // @synthesize repositoryID=_repositoryID;
@property(nonatomic) long long operationType; // @synthesize operationType=_operationType;
@property(nonatomic) long long status; // @synthesize status=_status;
@property(copy, nonatomic) NSDictionary *parameters; // @synthesize parameters=_parameters;
@property(copy, nonatomic) NSDate *dateFinished; // @synthesize dateFinished=_dateFinished;
@property(copy, nonatomic) NSDate *dateStarted; // @synthesize dateStarted=_dateStarted;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;

@end

