//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTGitWorkingCopyAction.h"

@class GTGitRemoteInfo, NSString;
@protocol GTGitPullActionDelegate;

@interface GTGitPullAction : GTGitWorkingCopyAction
{
    id <GTGitPullActionDelegate> _delegate;
    GTGitRemoteInfo *_remoteInfo;
    NSString *_refSpec;
    unsigned long long _options;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned long long options; // @synthesize options=_options;
@property(retain, nonatomic) NSString *refSpec; // @synthesize refSpec=_refSpec;
@property(retain, nonatomic) GTGitRemoteInfo *remoteInfo; // @synthesize remoteInfo=_remoteInfo;
@property(nonatomic) __weak id <GTGitPullActionDelegate> delegate; // @synthesize delegate=_delegate;
- (void)actionDidFinish;
- (void)actionDidAbortWithError:(id)arg1;
- (void)actionDidPerformMainAction;
- (void)actionDidFailToPerformMainActionWithError:(id)arg1;
- (void)actionWillPerformMainAction;
- (void)actionNeedsAutoUpdateSubmodules;
- (void)actionNeedsAutoStash;
- (void)actionDidStart;
- (void)actionWillStart;
- (void)main;
- (id)initWithRepository:(id)arg1;

@end

