//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface GTGitRepositoryFinderPathsManager : NSObject
{
}

+ (id)sharedManager;
- (void)postUpdateNotification;
- (void)removeIgnoredFilePaths:(id)arg1;
- (void)removeIgnoredFilePath:(id)arg1;
- (void)addIgnoredFilePaths:(id)arg1;
- (void)addIgnoredFilePath:(id)arg1;
- (id)ignoredFilePaths;
- (void)removeSearchPaths:(id)arg1;
- (void)removeSearchPath:(id)arg1;
- (void)addSearchPaths:(id)arg1;
- (void)addSearchPath:(id)arg1;
- (id)searchPaths;

@end

