//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTGitRepositoryOperation.h"

@class GTGitHistoryManager, NSArray;

@interface GTGitCalculateRevisionRangesOperation : GTGitRepositoryOperation
{
    NSArray *_revisionRanges;
    GTGitHistoryManager *_historyManager;
}

- (void).cxx_destruct;
@property(retain, nonatomic) GTGitHistoryManager *historyManager; // @synthesize historyManager=_historyManager;
@property(copy, nonatomic) NSArray *revisionRanges; // @synthesize revisionRanges=_revisionRanges;
- (id)title;
- (void)execute;
- (id)groups;

@end

