//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTGitWorkingCopyAction.h"

@class GTGitRemoteBranch, NSString;
@protocol GTGitCheckoutRemoteBranchActionDelegate;

@interface GTGitCheckoutRemoteBranchAction : GTGitWorkingCopyAction
{
    BOOL _didCreateBranch;
    GTGitRemoteBranch *_remoteBranch;
    NSString *_localRefName;
    id <GTGitCheckoutRemoteBranchActionDelegate> _delegate;
}

+ (id)actionWithRemoteBranch:(id)arg1 localRefName:(id)arg2;
- (void).cxx_destruct;
@property(nonatomic) BOOL didCreateBranch; // @synthesize didCreateBranch=_didCreateBranch;
@property(nonatomic) __weak id <GTGitCheckoutRemoteBranchActionDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSString *localRefName; // @synthesize localRefName=_localRefName;
@property(readonly, nonatomic) GTGitRemoteBranch *remoteBranch; // @synthesize remoteBranch=_remoteBranch;
- (void)actionDidFinish;
- (void)actionDidAbortWithError:(id)arg1;
- (void)actionDidPerformMainAction;
- (void)actionDidFailToPerformMainActionWithError:(id)arg1;
- (void)actionWillPerformMainAction;
- (void)actionNeedsAutoUpdateSubmodules;
- (void)actionNeedsAutoStash;
- (void)actionDidStart;
- (void)actionWillStart;
- (void)actionDidCheckoutBranch;
- (void)actionDidCreateAndTrackBranch;
- (void)performCreateNewBranch;
- (void)performMainActionForLocalBranch:(id)arg1;
- (void)main;
- (id)initWithRemoteBranch:(id)arg1 localRefName:(id)arg2;

@end

