//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface GTGitCommitHelpers : NSObject
{
}

+ (id)reversedRevisionsByTopoOrderAndCommitterDateFromCommits:(id)arg1;
+ (id)reversedRevisionsForRevertFromCommits:(id)arg1;
+ (id)reversedRevisionsForCherryPickFromCommits:(id)arg1;
+ (id)shortCommitHashFromCommitHash:(id)arg1;
+ (id)shortRevisionFromRevision:(id)arg1;
+ (BOOL)isCommitHash:(id)arg1;
+ (id)commitFromGitCommit:(id)arg1 withRepository:(id)arg2;
+ (id)commitFromGitCommit:(id)arg1;

@end

