//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface GTGitCredentialManager : NSObject
{
}

+ (BOOL)deleteCredentialsForRemoteURL:(id)arg1 error:(id *)arg2;
+ (BOOL)storePassword:(id)arg1 forRemoteURL:(id)arg2 error:(id *)arg3;
+ (id)passwordForRemoteURL:(id)arg1 error:(id *)arg2;

@end

