//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class GTGitRepository, GTUpdateChangeset, NSArray, NSManagedObjectContext, NSMutableArray;

@interface GTGitTagsUpdater : NSObject
{
    GTGitRepository *_repository;
    GTUpdateChangeset *_changeset;
    NSArray *_gitTags;
    NSManagedObjectContext *_managedObjectContext;
    NSMutableArray *_obsoleteTags;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *obsoleteTags; // @synthesize obsoleteTags=_obsoleteTags;
@property(retain, nonatomic) NSManagedObjectContext *managedObjectContext; // @synthesize managedObjectContext=_managedObjectContext;
@property(retain, nonatomic) NSArray *gitTags; // @synthesize gitTags=_gitTags;
@property(retain, nonatomic) GTUpdateChangeset *changeset; // @synthesize changeset=_changeset;
@property(retain, nonatomic) GTGitRepository *repository; // @synthesize repository=_repository;
- (void)addTagToDeletions:(id)arg1;
- (void)addTagToUpdates:(id)arg1;
- (void)addTagToInsertions:(id)arg1;
- (void)deleteObsoleteTags;
- (void)updateTag:(id)arg1 withGitTag:(id)arg2;
- (void)createOrUpdateTags;
- (BOOL)update:(id *)arg1;
- (id)initWithRepository:(id)arg1 gitTags:(id)arg2;

@end

