//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSIndexSet;

@interface GTGitMergeConflictState : NSObject
{
    BOOL _waitingForMergeTool;
    BOOL _waitingToConfirm;
    long long _mergeResultState;
    NSIndexSet *_chosenSourceFiles;
    NSIndexSet *_hintedSourceFiles;
}

- (void).cxx_destruct;
@property(nonatomic) BOOL waitingToConfirm; // @synthesize waitingToConfirm=_waitingToConfirm;
@property(nonatomic) BOOL waitingForMergeTool; // @synthesize waitingForMergeTool=_waitingForMergeTool;
@property(retain, nonatomic) NSIndexSet *hintedSourceFiles; // @synthesize hintedSourceFiles=_hintedSourceFiles;
@property(retain, nonatomic) NSIndexSet *chosenSourceFiles; // @synthesize chosenSourceFiles=_chosenSourceFiles;
@property(nonatomic) long long mergeResultState; // @synthesize mergeResultState=_mergeResultState;

@end

