//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTGitRepositoryOperation.h"

@class GTGitDiffOptions, GTGitLogOptions, NSArray, NSString;

@interface GTGitDiffsByComparingRevisionsOperation : GTGitRepositoryOperation
{
    NSString *_revision;
    NSString *_toRevision;
    NSArray *_filePaths;
    GTGitLogOptions *_logOptions;
    GTGitDiffOptions *_diffOptions;
    NSArray *_loadedDiffs;
}

+ (id)operationWithManagedObjectContext:(id)arg1 repository:(id)arg2 revision:(id)arg3 toRevision:(id)arg4 filePaths:(id)arg5 logOptions:(id)arg6 diffOptions:(id)arg7;
- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *loadedDiffs; // @synthesize loadedDiffs=_loadedDiffs;
@property(retain, nonatomic) GTGitDiffOptions *diffOptions; // @synthesize diffOptions=_diffOptions;
@property(retain, nonatomic) GTGitLogOptions *logOptions; // @synthesize logOptions=_logOptions;
@property(retain, nonatomic) NSArray *filePaths; // @synthesize filePaths=_filePaths;
@property(retain, nonatomic) NSString *toRevision; // @synthesize toRevision=_toRevision;
@property(retain, nonatomic) NSString *revision; // @synthesize revision=_revision;
- (id)combinedGitOptions;
- (void)execute;
- (id)groups;
- (id)title;
- (id)initWithManagedObjectContext:(id)arg1 repository:(id)arg2 revision:(id)arg3 toRevision:(id)arg4 filePaths:(id)arg5 logOptions:(id)arg6 diffOptions:(id)arg7;

@end

