//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class GTBackupInfo, GTGitMergeStatus, NSArray, NSData, NSString;

@interface GTGitWorkingTreeSnapshot : NSObject
{
    NSString *_revision;
    NSArray *_workingTreeEntries;
    NSData *_workingTreeToIndexPatch;
    NSData *_indexToBasePatch;
    NSData *_workingTreeToIndexSubmodulesPatch;
    NSData *_indexToBaseSubmodulesPatch;
    GTBackupInfo *_backupVolume;
    GTGitMergeStatus *_mergeStatus;
    long long _snapshotMode;
    NSArray *_storedWorkingTreeEntries;
}

+ (id)workingTreeSnapshotWithRevision:(id)arg1 workingTreeEntries:(id)arg2;
- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *storedWorkingTreeEntries; // @synthesize storedWorkingTreeEntries=_storedWorkingTreeEntries;
@property(nonatomic) long long snapshotMode; // @synthesize snapshotMode=_snapshotMode;
@property(retain, nonatomic) GTGitMergeStatus *mergeStatus; // @synthesize mergeStatus=_mergeStatus;
@property(retain, nonatomic) GTBackupInfo *backupVolume; // @synthesize backupVolume=_backupVolume;
@property(retain, nonatomic) NSData *indexToBaseSubmodulesPatch; // @synthesize indexToBaseSubmodulesPatch=_indexToBaseSubmodulesPatch;
@property(retain, nonatomic) NSData *workingTreeToIndexSubmodulesPatch; // @synthesize workingTreeToIndexSubmodulesPatch=_workingTreeToIndexSubmodulesPatch;
@property(retain, nonatomic) NSData *indexToBasePatch; // @synthesize indexToBasePatch=_indexToBasePatch;
@property(retain, nonatomic) NSData *workingTreeToIndexPatch; // @synthesize workingTreeToIndexPatch=_workingTreeToIndexPatch;
@property(retain, nonatomic) NSArray *workingTreeEntries; // @synthesize workingTreeEntries=_workingTreeEntries;
@property(retain, nonatomic) NSString *revision; // @synthesize revision=_revision;
@property(readonly, nonatomic) NSArray *updatableSubmodulePaths;
@property(readonly, nonatomic) NSArray *unstageableFilePaths;
@property(readonly, nonatomic) NSArray *discardableFilePaths;
@property(readonly, nonatomic) NSArray *resettableFilePaths;
@property(readonly, nonatomic) NSArray *unmergedEntries;
- (id)initWithRevision:(id)arg1 workingTreeEntries:(id)arg2;

@end

