//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FNGitSubmoduleIgnoreModeToGTGitSubmoduleIgnoreModeTransformer, FNGitSubmoduleRecurseSubmodulesOptionToGTGitSubmoduleRecurseSubmodulesOptionTransformer, FNGitSubmoduleStatusToGTGitSubmoduleStatusTransformer, FNGitSubmoduleUpdateStrategyToGTGitSubmoduleUpdateStrategyTransformer, GTGitRepository, GTUpdateChangeset, NSArray, NSDictionary, NSManagedObjectContext, NSMutableArray;

@interface GTGitSubmodulesUpdater : NSObject
{
    GTGitRepository *_repository;
    NSArray *_gitSubmodules;
    GTUpdateChangeset *_changeset;
    NSManagedObjectContext *_managedObjectContext;
    NSDictionary *_changes;
    NSMutableArray *_obsoleteSubmodules;
    FNGitSubmoduleStatusToGTGitSubmoduleStatusTransformer *_statusTransformer;
    FNGitSubmoduleIgnoreModeToGTGitSubmoduleIgnoreModeTransformer *_ignoreModeTransformer;
    FNGitSubmoduleUpdateStrategyToGTGitSubmoduleUpdateStrategyTransformer *_updateStrategyTransformer;
    FNGitSubmoduleRecurseSubmodulesOptionToGTGitSubmoduleRecurseSubmodulesOptionTransformer *_recurseSubmodulesOptionTransformer;
}

- (void).cxx_destruct;
@property(retain, nonatomic) FNGitSubmoduleRecurseSubmodulesOptionToGTGitSubmoduleRecurseSubmodulesOptionTransformer *recurseSubmodulesOptionTransformer; // @synthesize recurseSubmodulesOptionTransformer=_recurseSubmodulesOptionTransformer;
@property(retain, nonatomic) FNGitSubmoduleUpdateStrategyToGTGitSubmoduleUpdateStrategyTransformer *updateStrategyTransformer; // @synthesize updateStrategyTransformer=_updateStrategyTransformer;
@property(retain, nonatomic) FNGitSubmoduleIgnoreModeToGTGitSubmoduleIgnoreModeTransformer *ignoreModeTransformer; // @synthesize ignoreModeTransformer=_ignoreModeTransformer;
@property(retain, nonatomic) FNGitSubmoduleStatusToGTGitSubmoduleStatusTransformer *statusTransformer; // @synthesize statusTransformer=_statusTransformer;
@property(retain, nonatomic) NSMutableArray *obsoleteSubmodules; // @synthesize obsoleteSubmodules=_obsoleteSubmodules;
@property(retain, nonatomic) NSDictionary *changes; // @synthesize changes=_changes;
@property(retain, nonatomic) NSManagedObjectContext *managedObjectContext; // @synthesize managedObjectContext=_managedObjectContext;
@property(retain, nonatomic) GTUpdateChangeset *changeset; // @synthesize changeset=_changeset;
@property(retain, nonatomic) NSArray *gitSubmodules; // @synthesize gitSubmodules=_gitSubmodules;
@property(retain, nonatomic) GTGitRepository *repository; // @synthesize repository=_repository;
- (void)addSubmoduleToDeletions:(id)arg1;
- (void)addSubmoduleToUpdates:(id)arg1;
- (void)addSubmoduleToInsertions:(id)arg1;
- (void)deleteObsoleteSubmodules;
- (void)updateSubmoduleCustomConfig:(id)arg1 withGitSubmoduleConfig:(id)arg2;
- (void)updateSubmoduleDefaultConfig:(id)arg1 withGitSubmoduleConfig:(id)arg2;
- (void)updateSubmodule:(id)arg1 withGitSubmodule:(id)arg2;
- (void)createOrUpdateSubmodules;
- (BOOL)update:(id *)arg1;
- (id)initWithRepository:(id)arg1 gitSubmodules:(id)arg2;

@end

