//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface GTGitCommitRefDecorator : NSObject
{
    short _refType;
    NSString *_fullRefName;
    NSString *_refName;
}

- (void).cxx_destruct;
@property(nonatomic) short refType; // @synthesize refType=_refType;
@property(retain, nonatomic) NSString *refName; // @synthesize refName=_refName;
@property(retain, nonatomic) NSString *fullRefName; // @synthesize fullRefName=_fullRefName;
- (short)refTypeForFullRefName:(id)arg1;
- (id)refNameForFullRefName:(id)arg1;
- (id)initWithFullRefName:(id)arg1;
- (id)init;

@end

