//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTGitRepositoryOperation.h"

@class GTGitMergeStatus, NSArray;

@interface GTGitRecreateUnmergedEntriesOperation : GTGitRepositoryOperation
{
    NSArray *_entries;
    GTGitMergeStatus *_mergeStatus;
}

+ (id)operationWithManagedObjectContext:(id)arg1 repository:(id)arg2 entries:(id)arg3 mergeStatus:(id)arg4;
- (void).cxx_destruct;
@property(retain, nonatomic) GTGitMergeStatus *mergeStatus; // @synthesize mergeStatus=_mergeStatus;
@property(retain, nonatomic) NSArray *entries; // @synthesize entries=_entries;
- (void)execute;
- (id)groups;
- (BOOL)isWriteOperation;
- (id)initWithManagedObjectContext:(id)arg1 repositoryDescriptor:(id)arg2 entries:(id)arg3 mergeStatus:(id)arg4;

@end

