//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTGitAction.h"

@class NSArray, NSMutableSet;

@interface GTGitRestoreRemotesAction : GTGitAction
{
    NSArray *_remoteInfos;
    NSMutableSet *_remotesToFetch;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableSet *remotesToFetch; // @synthesize remotesToFetch=_remotesToFetch;
@property(retain, nonatomic) NSArray *remoteInfos; // @synthesize remoteInfos=_remoteInfos;
- (void)actionDidFinish;
- (void)actionDidFailWithError:(id)arg1;
- (void)actionDidFetchRemoteWithInfo:(id)arg1;
- (void)actionDidFinishReloadRemotes;
- (void)actionDidRestoreRemoteConnections;
- (void)actionDidRestoreRemotes;
- (void)main;

@end

