//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTGitOperation.h"

@class GTUpdateChangeset;

@interface GTGitReloadGlobalConfigOperation : GTGitOperation
{
    // Error parsing type: , name: changeset
    // Error parsing type: , name: userID
    // Error parsing type: , name: gpgConfigID
}

- (void).cxx_destruct;
- (id)initWithManagedObjectContext:(id)arg1;
- (void)execute;
- (id)initWithUserID:(id)arg1 gpgConfigID:(id)arg2 managedObjectContext:(id)arg3;
- (id)initWithUser:(id)arg1 gpgConfig:(id)arg2 managedObjectContext:(id)arg3;
@property(nonatomic, retain) GTUpdateChangeset *changeset; // @synthesize changeset;

@end

