//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTGitRepositoryOperation.h"

@class NSArray;

@interface GTGitLoadWorkingTreeEntriesOperation : GTGitRepositoryOperation
{
    unsigned long long _options;
    NSArray *_workingTreeEntries;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *workingTreeEntries; // @synthesize workingTreeEntries=_workingTreeEntries;
@property(nonatomic) unsigned long long options; // @synthesize options=_options;
- (id)gitStatusOptionsFromOptions:(unsigned long long)arg1;
- (void)execute;
- (id)groups;
- (id)title;
- (long long)type;
- (id)initWithManagedObjectContext:(id)arg1 repositoryDescriptor:(id)arg2 options:(unsigned long long)arg3;

@end

