//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTGitManager.h"

@interface GTGitTagManager : GTGitManager
{
}

- (void)verifyGPGSignatureForTagWithName:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (id)verifyGPGSignatureForTagWithName:(id)arg1 error:(id *)arg2;
- (void)deleteTagsWithRefNames:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)deleteTags:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (BOOL)deleteTagsWithRefNames:(id)arg1 error:(id *)arg2;
- (BOOL)deleteTags:(id)arg1 error:(id *)arg2;
- (void)restoreTags:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (BOOL)restoreTags:(id)arg1 error:(id *)arg2;
- (void)createWithTagWithName:(id)arg1 startingRevision:(id)arg2 message:(id)arg3 sign:(BOOL)arg4 gpgKeyFingerprint:(id)arg5 completionHandler:(CDUnknownBlockType)arg6;
- (BOOL)createWithTagWithName:(id)arg1 startingRevision:(id)arg2 message:(id)arg3 sign:(BOOL)arg4 gpgKeyFingerprint:(id)arg5 error:(id *)arg6;
- (void)reloadWithCompletionHandler:(CDUnknownBlockType)arg1;

@end

