//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTGitRepositoryOperation.h"

@class GTGitMergeStatus, GTGitWorkingTreeSnapshot, NSArray, NSString;

@interface GTGitCreateWorkingTreeSnapshotOperation : GTGitRepositoryOperation
{
    NSString *_revision;
    NSArray *_workingTreeEntries;
    long long _snapshotMode;
    GTGitWorkingTreeSnapshot *_snapshot;
    GTGitMergeStatus *_mergeStatus;
}

+ (id)operationWithManagedObjectContext:(id)arg1 repository:(id)arg2 revision:(id)arg3 workingTreeEntries:(id)arg4;
- (void).cxx_destruct;
@property(retain, nonatomic) GTGitMergeStatus *mergeStatus; // @synthesize mergeStatus=_mergeStatus;
@property(retain, nonatomic) GTGitWorkingTreeSnapshot *snapshot; // @synthesize snapshot=_snapshot;
@property(nonatomic) long long snapshotMode; // @synthesize snapshotMode=_snapshotMode;
@property(readonly, nonatomic) NSArray *workingTreeEntries; // @synthesize workingTreeEntries=_workingTreeEntries;
@property(readonly, nonatomic) NSString *revision; // @synthesize revision=_revision;
- (void)execute;
@property(readonly, nonatomic, getter=isDefaultSnapshotMode) BOOL defaultSnapshotMode;
- (id)groups;
- (BOOL)isWriteOperation;
- (id)title;
- (id)initWithManagedObjectContext:(id)arg1 repository:(id)arg2 revision:(id)arg3 workingTreeEntries:(id)arg4;

@end

