//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTGitWorkingCopyAction.h"

@protocol GTGitContinueMergeActionDelegate;

@interface GTGitContinueMergeAction : GTGitWorkingCopyAction
{
    id <GTGitContinueMergeActionDelegate> _delegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <GTGitContinueMergeActionDelegate> delegate; // @synthesize delegate=_delegate;
- (void)actionDidFinish;
- (void)actionDidAbortWithError:(id)arg1;
- (void)actionDidPerformMainAction;
- (void)actionWillPerformMainAction;
- (void)actionNeedsAutoUpdateSubmodules;
- (void)actionDidStart;
- (void)actionWillStart;
- (void)main;
- (id)initWithRepository:(id)arg1;

@end

