//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class GTGitBinary, NSMutableArray;

@interface GTGitBinaryManager : NSObject
{
    GTGitBinary *_defaultGitBinary;
    NSMutableArray *_managedGitBinaries;
}

+ (id)sharedManager;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *managedGitBinaries; // @synthesize managedGitBinaries=_managedGitBinaries;
@property(retain, nonatomic) GTGitBinary *defaultGitBinary; // @synthesize defaultGitBinary=_defaultGitBinary;
- (id)gitBinaryForFileURL:(id)arg1;
- (id)gitBinaryForPath:(id)arg1;
- (id)allGitBinaries;
- (void)removeAllGitBinaries;
- (void)removeGitBinaries:(id)arg1;
- (void)removeGitBinary:(id)arg1;
- (void)addGitBinaries:(id)arg1;
- (void)addGitBinary:(id)arg1;
- (id)init;

@end

