//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTGitRepositoryOperation.h"

@class NSArray, NSString;

@interface GTGitConfigureDiffToolOperation : GTGitRepositoryOperation
{
    // Error parsing type: , name: diffToolName
    // Error parsing type: , name: diffToolPath
    // Error parsing type: , name: supportsDiffChangeset
}

- (void).cxx_destruct;
- (id)initWithManagedObjectContext:(id)arg1 repositoryDescriptor:(id)arg2;
- (id)initWithManagedObjectContext:(id)arg1 repository:(id)arg2;
- (void)execute;
@property(nonatomic, readonly) NSArray *groups;
- (BOOL)isWriteOperation;
- (id)initWithManagedObjectContext:(id)arg1 repositoryDescriptor:(id)arg2 diffToolName:(id)arg3 diffToolPath:(id)arg4;
- (id)initWithManagedObjectContext:(id)arg1 repository:(id)arg2 diffToolName:(id)arg3 diffToolPath:(id)arg4;
@property(nonatomic) BOOL supportsDiffChangeset; // @synthesize supportsDiffChangeset;
@property(nonatomic, readonly) NSString *diffToolPath;
@property(nonatomic, readonly) NSString *diffToolName;

// Remaining properties
@property(nonatomic, readonly) BOOL writeOperation;

@end

