//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class GTGitChangeset, NSArray, NSString;

@interface GTGitChangesetEntry : NSObject
{
    GTGitChangeset *_changeset;
    NSString *_filePath;
    NSString *_oldFilePath;
    unsigned long long _fileStatus;
    unsigned long long _fileStatusSimilarityIndex;
    unsigned long long _fileMode;
    NSArray *_originalFileModes;
    NSString *_objectHash;
    NSArray *_originalObjectHashes;
    unsigned long long _linesAdded;
    unsigned long long _linesDeleted;
}

+ (id)changesetEntryWithChangeset:(id)arg1;
+ (id)changesetEntryWithChangeset:(id)arg1 gitChangesetEntry:(id)arg2;
- (void).cxx_destruct;
@property(nonatomic) unsigned long long linesDeleted; // @synthesize linesDeleted=_linesDeleted;
@property(nonatomic) unsigned long long linesAdded; // @synthesize linesAdded=_linesAdded;
@property(copy, nonatomic) NSArray *originalObjectHashes; // @synthesize originalObjectHashes=_originalObjectHashes;
@property(copy, nonatomic) NSString *objectHash; // @synthesize objectHash=_objectHash;
@property(copy, nonatomic) NSArray *originalFileModes; // @synthesize originalFileModes=_originalFileModes;
@property(nonatomic) unsigned long long fileMode; // @synthesize fileMode=_fileMode;
@property(nonatomic) unsigned long long fileStatusSimilarityIndex; // @synthesize fileStatusSimilarityIndex=_fileStatusSimilarityIndex;
@property(nonatomic) unsigned long long fileStatus; // @synthesize fileStatus=_fileStatus;
@property(copy, nonatomic) NSString *oldFilePath; // @synthesize oldFilePath=_oldFilePath;
@property(copy, nonatomic) NSString *filePath; // @synthesize filePath=_filePath;
@property(nonatomic) __weak GTGitChangeset *changeset; // @synthesize changeset=_changeset;
- (id)initWithChangeset:(id)arg1;
- (id)init;

@end

