//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTGitRef.h"

@class GTGitRemote, GTGitRemoteBranchInfo, NSDictionary, NSSet, NSString;

@interface GTGitRemoteBranch : GTGitRef
{
}

+ (id)remoteBranchWithFullRefName:(id)arg1 remoteName:(id)arg2 managedObjectContext:(id)arg3;
+ (id)remoteBranchWithID:(id)arg1 managedObjectContext:(id)arg2 error:(id *)arg3;
+ (id)fetchAllRemoteBranchesForRepository:(id)arg1 error:(id *)arg2;
+ (id)keyPathsForValuesAffectingLocalFullRefName;
+ (id)keyPathsForValuesAffectingLocalRefName;
- (void)updateLocalRefNamesForRemoteName:(id)arg1;
@property(nonatomic, getter=isHead) BOOL head; // @dynamic head;
- (id)initWithRefType:(short)arg1 fullRefName:(id)arg2 remoteName:(id)arg3 managedObjectContext:(id)arg4;
@property(readonly, nonatomic) NSDictionary *dictionaryRepresentation;
@property(readonly, nonatomic) NSString *forkedPullRequestBranchName;
@property(readonly, nonatomic) GTGitRemoteBranchInfo *remoteBranchInfo;

// Remaining properties
@property(readonly, nonatomic) NSString *localFullRefName; // @dynamic localFullRefName;
@property(readonly, nonatomic) NSString *localRefName; // @dynamic localRefName;
@property(retain, nonatomic) GTGitRemote *remote; // @dynamic remote;
@property(retain, nonatomic) NSSet *trackingSVNBranches; // @dynamic trackingSVNBranches;

@end

