//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTGitCloneAction.h"

@class GTBookmark, GTGitRemoteConnection, GTGitRemoteManager, GTGitRepository, GTGitRepositoryManager, NSDictionary, NSURL;

@interface GTGitCloneRepositoryAction : GTGitCloneAction
{
    GTGitRemoteConnection *_remoteConnection;
    NSURL *_destinationURL;
    NSDictionary *_options;
    GTGitRepositoryManager *_repositoryManager;
    GTGitRemoteManager *_remoteManager;
    GTGitRepository *_repository;
    GTBookmark *_bookmark;
}

- (void).cxx_destruct;
@property(retain, nonatomic) GTBookmark *bookmark; // @synthesize bookmark=_bookmark;
@property(retain, nonatomic) GTGitRepository *repository; // @synthesize repository=_repository;
@property(retain, nonatomic) GTGitRemoteManager *remoteManager; // @synthesize remoteManager=_remoteManager;
@property(retain, nonatomic) GTGitRepositoryManager *repositoryManager; // @synthesize repositoryManager=_repositoryManager;
@property(retain, nonatomic) NSDictionary *options; // @synthesize options=_options;
@property(retain, nonatomic) NSURL *destinationURL; // @synthesize destinationURL=_destinationURL;
@property(retain, nonatomic) GTGitRemoteConnection *remoteConnection; // @synthesize remoteConnection=_remoteConnection;
- (void)cleanup;
- (void)actionDidFinish;
- (void)actionDidFailWithError:(id)arg1;
- (void)actionDidReloadRemotes;
- (void)actionDidReloadRepository;
- (void)actionDidCloneRepository;
- (void)actionDidCreateBookmarkWithID:(id)arg1;
- (void)actionDidCreateRepositoryWithID:(id)arg1;
- (void)main;

@end

