//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTGitRepositoryOperation.h"

@class NSArray;

@interface GTGitAmendRevisionOperation : GTGitRepositoryOperation
{
    // Error parsing type: , name: revision
}

- (void).cxx_destruct;
- (id)initWithManagedObjectContext:(id)arg1 repositoryDescriptor:(id)arg2;
- (id)initWithManagedObjectContext:(id)arg1 repository:(id)arg2;
- (void)execute;
@property(nonatomic, readonly) NSArray *groups;
- (id)initWithRevision:(id)arg1 repository:(id)arg2 managedObjectContext:(id)arg3;

@end

