//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTGitManager.h"

@interface GTGitRefLogEntryManager : GTGitManager
{
}

- (void)loadRefLogEntriesForRefWithName:(id)arg1 options:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (id)loadRefLogEntriesForRefWithName:(id)arg1 options:(id)arg2 error:(id *)arg3;
- (void)loadHEADRefLogEntries:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (id)loadHEADRefLogEntries:(id)arg1 error:(id *)arg2;
- (void)numberOfRefLogEntriesForRefWithName:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (unsigned long long)numberOfRefLogEntriesForRefWithName:(id)arg1 error:(id *)arg2;

@end

