//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class GTGitRepository, NSArray, NSManagedObjectID;

@interface GTGitChangeset : NSObject
{
    NSArray *_entries;
    GTGitRepository *_repository;
    NSManagedObjectID *_repositoryID;
}

+ (id)changesetWithRepository:(id)arg1;
+ (id)changesetWithRepositoryID:(id)arg1 gitChangeset:(id)arg2;
- (void).cxx_destruct;
@property(retain, nonatomic) NSManagedObjectID *repositoryID; // @synthesize repositoryID=_repositoryID;
@property(nonatomic) __weak GTGitRepository *repository; // @synthesize repository=_repository;
@property(copy, nonatomic) NSArray *entries; // @synthesize entries=_entries;
- (id)entryForFilePath:(id)arg1;
@property(readonly, nonatomic) unsigned long long totalLinesDeleted;
@property(readonly, nonatomic) unsigned long long totalLinesAdded;
@property(readonly, nonatomic) unsigned long long totalLinesChanged;
@property(readonly, nonatomic) unsigned long long totalFilesChanged;
- (id)initWithRepositoryID:(id)arg1;

@end

