//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTGitRepositoryOperation.h"

@class NSArray;

@interface GTGitUpdateRepositoryStatsOperation : GTGitRepositoryOperation
{
    NSArray *_loadedTreeEntries;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *loadedTreeEntries; // @synthesize loadedTreeEntries=_loadedTreeEntries;
- (void)execute;
- (id)groups;
- (BOOL)isWriteOperation;
- (id)title;
- (id)initWithManagedObjectContext:(id)arg1 repositoryDescriptor:(id)arg2;

@end

