//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTGitRepositoryOperation.h"

@class NSArray;

@interface GTGitReplayMergeSequenceOperation : GTGitRepositoryOperation
{
    BOOL _appliesAndCommitsLastSnapshot;
    unsigned long long _numberOfSequenceSteps;
    NSArray *_snapshots;
}

+ (id)operationWithManagedObjectContext:(id)arg1 repository:(id)arg2 numberOfSequenceSteps:(unsigned long long)arg3 snapshots:(id)arg4 appliesAndCommitsLastSnapshot:(BOOL)arg5;
+ (id)operationWithManagedObjectContext:(id)arg1 repository:(id)arg2 numberOfSequenceSteps:(unsigned long long)arg3 snapshots:(id)arg4;
- (void).cxx_destruct;
@property(nonatomic) BOOL appliesAndCommitsLastSnapshot; // @synthesize appliesAndCommitsLastSnapshot=_appliesAndCommitsLastSnapshot;
@property(retain, nonatomic) NSArray *snapshots; // @synthesize snapshots=_snapshots;
@property(nonatomic) unsigned long long numberOfSequenceSteps; // @synthesize numberOfSequenceSteps=_numberOfSequenceSteps;
- (BOOL)restoreSnapshot:(id)arg1 error:(id *)arg2;
- (void)continueMerge:(BOOL)arg1;
- (BOOL)commit:(BOOL)arg1;
- (void)execute;
- (id)groups;
- (BOOL)isWriteOperation;
- (id)initWithManagedObjectContext:(id)arg1 repository:(id)arg2 numberOfSequenceSteps:(unsigned long long)arg3 snapshots:(id)arg4 appliesAndCommitsLastSnapshot:(BOOL)arg5;
- (id)initWithManagedObjectContext:(id)arg1 repository:(id)arg2 numberOfSequenceSteps:(unsigned long long)arg3 snapshots:(id)arg4;

@end

