//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTGitController.h"

@class GTGitStashInfo, GTGitStashManager, NSError, NSString;
@protocol GTGitAutoStashControllerDelegate;

@interface GTGitAutoStashController : GTGitController
{
    BOOL _autoStashing;
    BOOL _performingTask;
    id <GTGitAutoStashControllerDelegate> _delegate;
    NSError *_error;
    NSString *_userMessage;
    GTGitStashInfo *_stashInfo;
    NSString *_lastAutoStashMessage;
    GTGitStashManager *_stashManager;
}

- (void).cxx_destruct;
@property(retain, nonatomic) GTGitStashManager *stashManager; // @synthesize stashManager=_stashManager;
@property(retain, nonatomic) NSString *lastAutoStashMessage; // @synthesize lastAutoStashMessage=_lastAutoStashMessage;
@property(nonatomic, getter=isPerformingTask) BOOL performingTask; // @synthesize performingTask=_performingTask;
@property(retain, nonatomic) GTGitStashInfo *stashInfo; // @synthesize stashInfo=_stashInfo;
@property(retain, nonatomic) NSString *userMessage; // @synthesize userMessage=_userMessage;
@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
@property(nonatomic, getter=isAutoStashing) BOOL autoStashing; // @synthesize autoStashing=_autoStashing;
@property(nonatomic) __weak id <GTGitAutoStashControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)waitUntilFinished;
- (void)controllerDidReloadStashes;
- (void)controllerDidFailToApplyStash:(id)arg1;
- (void)controllerDidFailToSaveStash:(id)arg1;
- (void)controllerDidApplyStash;
- (void)controllerDidSaveStash:(id)arg1;
- (id)generateUniqueStashSaveMessage;
- (void)applyAutoStash;
- (void)saveAutoStashWithUserMessage:(id)arg1;
- (BOOL)needsAutoStash;
- (id)initWithRepository:(id)arg1;

@end

