//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTGitRepositoryOperation.h"

@class FNGitSubmoduleConfigManager, NSString;

@interface GTGitSubmoduleConfigOperation : GTGitRepositoryOperation
{
    NSString *_submoduleName;
    long long _configType;
    FNGitSubmoduleConfigManager *_gitConfigManager;
}

- (void).cxx_destruct;
@property(retain, nonatomic) FNGitSubmoduleConfigManager *gitConfigManager; // @synthesize gitConfigManager=_gitConfigManager;
@property(nonatomic) long long configType; // @synthesize configType=_configType;
@property(copy, nonatomic) NSString *submoduleName; // @synthesize submoduleName=_submoduleName;
- (id)groups;
- (id)title;
- (long long)type;
- (id)initWithManagedObjectContext:(id)arg1 submoduleName:(id)arg2 configType:(long long)arg3 submoduleRepositoryDescriptor:(id)arg4;

@end

