//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTAction.h"

@interface GTGitReloadGlobalConfigAction : GTAction
{
    // Error parsing type: , name: configManager
    // Error parsing type: , name: globalUser
    // Error parsing type: , name: globalGPGConfig
}

- (void).cxx_destruct;
- (id)init;
- (void)main;
- (id)initWithGlobalUser:(id)arg1 globalGPGConfig:(id)arg2;

@end

