//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTGitAction.h"

@class GTGitRemoteBranchInfo, NSArray;
@protocol GTGitDeleteBranchesActionDelegate;

@interface GTGitDeleteBranchesAction : GTGitAction
{
    BOOL _aborted;
    BOOL _forcesDeletion;
    BOOL _deletesTrackedBranches;
    id <GTGitDeleteBranchesActionDelegate> _delegate;
    NSArray *_branchRefNames;
    NSArray *_branchRefNamesWithUnmergedChanges;
    GTGitRemoteBranchInfo *_trackedBranchInfo;
}

+ (id)actionWithRepository:(id)arg1 branchRefNames:(id)arg2;
- (void).cxx_destruct;
@property(retain, nonatomic) GTGitRemoteBranchInfo *trackedBranchInfo; // @synthesize trackedBranchInfo=_trackedBranchInfo;
@property(nonatomic) BOOL deletesTrackedBranches; // @synthesize deletesTrackedBranches=_deletesTrackedBranches;
@property(retain, nonatomic) NSArray *branchRefNamesWithUnmergedChanges; // @synthesize branchRefNamesWithUnmergedChanges=_branchRefNamesWithUnmergedChanges;
@property(nonatomic) BOOL forcesDeletion; // @synthesize forcesDeletion=_forcesDeletion;
@property(nonatomic, getter=isAborted) BOOL aborted; // @synthesize aborted=_aborted;
@property(copy, nonatomic) NSArray *branchRefNames; // @synthesize branchRefNames=_branchRefNames;
@property(nonatomic) __weak id <GTGitDeleteBranchesActionDelegate> delegate; // @synthesize delegate=_delegate;
- (void)actionDidAbortWithError:(id)arg1;
- (void)actionDidFinish;
- (void)actionDidFailWithError:(id)arg1;
- (void)actionDidDeleteBranches;
- (void)forceDeleteBranchesWithUnmergedChanges;
- (void)abortWithError:(id)arg1;
- (void)cancel;
- (void)main;
- (id)initWithRepository:(id)arg1 branchRefNames:(id)arg2;

@end

