//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreData/NSManagedObject.h>

@class GTGitRepository, NSString;

@interface GTGitUser : NSManagedObject
{
}

+ (id)gitUserWithManagedObjectContext:(id)arg1;
+ (id)fetchGlobalUserWith:(id)arg1 error:(id *)arg2;
+ (id)fetchGlobalUserAndReturnError:(id *)arg1;
+ (void)setGlobalUser:(id)arg1;
+ (id)globalUser;
@property(readonly, nonatomic) NSString *displayName;
@property(nonatomic) BOOL usesGlobalEmail;
@property(nonatomic) BOOL usesGlobalName;

// Remaining properties
@property(retain, nonatomic) NSString *email; // @dynamic email;
@property(retain, nonatomic) NSString *gpgKeyFingerprint; // @dynamic gpgKeyFingerprint;
@property(retain, nonatomic) NSString *name; // @dynamic name;
@property(retain, nonatomic) GTGitRepository *repository; // @dynamic repository;

@end

