//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTGitActionSenderValidator.h"

@interface GTGitFlowActionSenderValidator : GTGitActionSenderValidator
{
}

- (BOOL)validateFinishGitFlowReleaseBranchWithItem:(id)arg1;
- (BOOL)validateFinishGitFlowHotfixBranchWithItem:(id)arg1;
- (BOOL)validateFinishGitFlowFeatureBranchWithItem:(id)arg1;
- (BOOL)validateCreateGitFlowReleaseBranchWithItem:(id)arg1;
- (BOOL)validateCreateGitFlowHotfixBranchWithItem:(id)arg1;
- (BOOL)validateCreateGitFlowFeatureBranchWithItem:(id)arg1;
- (BOOL)validateConfigureGitFlowWithItem:(id)arg1;
- (BOOL)validateDisableGitFlowWithItem:(id)arg1;
- (BOOL)validateEnableGitFlowWithItem:(id)arg1;
- (void)registerActions;

@end

