//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTDialogueViewController.h"

@class NSString;

@interface GTGPGCreateRealKeyDialogueViewController : GTDialogueViewController
{
    NSString *_username;
    NSString *_email;
    NSString *_password;
    NSString *_repeatedPassword;
}

+ (id)keyPathsForValuesAffectingValidatesSubmitButton;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *repeatedPassword; // @synthesize repeatedPassword=_repeatedPassword;
@property(retain, nonatomic) NSString *password; // @synthesize password=_password;
@property(readonly, nonatomic) NSString *email; // @synthesize email=_email;
@property(readonly, nonatomic) NSString *username; // @synthesize username=_username;
- (BOOL)validatesSubmitButton;
- (void)commonInit;
- (id)initWithUsername:(id)arg1 email:(id)arg2;

@end

