//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FNFoundation/FNCommandOperation.h>

@class GTGPGBinary, NSArray, NSMutableArray, NSString;

@interface GTGPGCommand : FNCommandOperation
{
    BOOL _showsPrivateKeys;
    BOOL _generatesKey;
    GTGPGBinary *_gpgBinary;
    NSArray *_gpgKeyDescriptions;
    NSString *_password;
    NSString *_username;
    NSString *_email;
    NSString *_standardOutputString;
    NSString *_standardErrorString;
    NSMutableArray *_gpgOptions;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *gpgOptions; // @synthesize gpgOptions=_gpgOptions;
@property(retain, nonatomic) NSString *standardErrorString; // @synthesize standardErrorString=_standardErrorString;
@property(retain, nonatomic) NSString *standardOutputString; // @synthesize standardOutputString=_standardOutputString;
@property(retain, nonatomic) NSString *email; // @synthesize email=_email;
@property(retain, nonatomic) NSString *username; // @synthesize username=_username;
@property(retain, nonatomic) NSString *password; // @synthesize password=_password;
@property(retain, nonatomic) NSArray *gpgKeyDescriptions; // @synthesize gpgKeyDescriptions=_gpgKeyDescriptions;
@property(retain, nonatomic) GTGPGBinary *gpgBinary; // @synthesize gpgBinary=_gpgBinary;
@property(nonatomic) BOOL generatesKey; // @synthesize generatesKey=_generatesKey;
@property(nonatomic) BOOL showsPrivateKeys; // @synthesize showsPrivateKeys=_showsPrivateKeys;
- (BOOL)parseOutput:(id *)arg1;
- (id)makeGPGErrorUserInfo;
- (id)makeGPGError;
- (void)commandDidTerminate;
- (void)commandDidFailToLaunch;
- (void)commandWillExecute;
- (void)addOptions:(id)arg1;
- (void)addOption:(id)arg1;
- (BOOL)run:(id *)arg1;
- (id)initWithGPGBinary:(id)arg1;

@end

