//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class GTGPGBinary, NSMutableArray;

@interface GTGPGBinaryManager : NSObject
{
    GTGPGBinary *_defaultGPGBinary;
    NSMutableArray *_managedGPGBinaries;
}

+ (id)sharedManager;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *managedGPGBinaries; // @synthesize managedGPGBinaries=_managedGPGBinaries;
@property(retain, nonatomic) GTGPGBinary *defaultGPGBinary; // @synthesize defaultGPGBinary=_defaultGPGBinary;
- (id)gpgBinaryForFileURL:(id)arg1;
- (id)gpgBinaryForPath:(id)arg1;
- (id)allGPGBinaries;
- (void)removeAllGPGBinaries;
- (void)removeGPGBinaries:(id)arg1;
- (void)removeGPGBinary:(id)arg1;
- (void)addGPGBinaries:(id)arg1;
- (BOOL)addGPGBinary:(id)arg1;
- (id)init;

@end

