//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class GTGPGConfBinary, NSMutableArray;

@interface GTGPGConfBinaryManager : NSObject
{
    GTGPGConfBinary *_defaultGPGConfBinary;
    NSMutableArray *_managedGPGConfBinaries;
}

+ (id)sharedManager;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *managedGPGConfBinaries; // @synthesize managedGPGConfBinaries=_managedGPGConfBinaries;
@property(retain, nonatomic) GTGPGConfBinary *defaultGPGConfBinary; // @synthesize defaultGPGConfBinary=_defaultGPGConfBinary;
- (id)gpgConfBinaryForFileURL:(id)arg1;
- (id)gpgConfBinaryForPath:(id)arg1;
- (id)allGPGConfBinaries;
- (void)removeAllGPGConfBinaries;
- (void)removeGPGConfBinaries:(id)arg1;
- (void)removeGPGConfBinary:(id)arg1;
- (void)addGPGConfBinaries:(id)arg1;
- (void)addGPGConfBinary:(id)arg1;
- (id)init;

@end

