//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTableCellView.h>

@class GTAvatarImageView, GTHistoryCommitItem, GTHistoryCommitListGraphView, GTRefBadgesView, NSArray, NSBox, NSColor, NSImage, NSImageView, NSLayoutConstraint, NSString, NSTextField;

@interface GTHistoryCommitListCellView : NSTableCellView
{
    BOOL _separatorVisible;
    NSTextField *_shortSHATextField;
    NSTextField *_authorTextField;
    NSTextField *_commitDateTextField;
    NSTextField *_subjectTextField;
    NSTextField *_commitMessageTextField;
    GTAvatarImageView *_authorGravatarImageView;
    NSImageView *_aheadBehindArrowImageView;
    GTRefBadgesView *_refBadgesView;
    GTHistoryCommitListGraphView *_graphContainerView;
    NSBox *_separator;
    NSLayoutConstraint *_graphViewLeadingSpaceConstraint;
    NSColor *_backgroundColor;
    NSArray *_horizontalConstraints;
    NSArray *_verticalConstraints;
}

+ (double)height;
+ (id)keyPathsForValuesAffectingCanShowSignature;
+ (id)keyPathsForValuesAffectingHistoryCommitItem;
- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *verticalConstraints; // @synthesize verticalConstraints=_verticalConstraints;
@property(retain, nonatomic) NSArray *horizontalConstraints; // @synthesize horizontalConstraints=_horizontalConstraints;
@property(retain, nonatomic) NSColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(nonatomic, getter=isSeparatorVisible) BOOL separatorVisible; // @synthesize separatorVisible=_separatorVisible;
@property __weak NSLayoutConstraint *graphViewLeadingSpaceConstraint; // @synthesize graphViewLeadingSpaceConstraint=_graphViewLeadingSpaceConstraint;
@property __weak NSBox *separator; // @synthesize separator=_separator;
@property __weak GTHistoryCommitListGraphView *graphContainerView; // @synthesize graphContainerView=_graphContainerView;
@property __weak GTRefBadgesView *refBadgesView; // @synthesize refBadgesView=_refBadgesView;
@property __weak NSImageView *aheadBehindArrowImageView; // @synthesize aheadBehindArrowImageView=_aheadBehindArrowImageView;
@property __weak GTAvatarImageView *authorGravatarImageView; // @synthesize authorGravatarImageView=_authorGravatarImageView;
@property __weak NSTextField *commitMessageTextField; // @synthesize commitMessageTextField=_commitMessageTextField;
@property __weak NSTextField *subjectTextField; // @synthesize subjectTextField=_subjectTextField;
@property __weak NSTextField *commitDateTextField; // @synthesize commitDateTextField=_commitDateTextField;
@property __weak NSTextField *authorTextField; // @synthesize authorTextField=_authorTextField;
@property __weak NSTextField *shortSHATextField; // @synthesize shortSHATextField=_shortSHATextField;
- (void)layout;
- (void)showSignaturePopover:(id)arg1;
- (void)updateSeparatorVisibility;
- (void)updateGraph;
- (void)updateTrackingInfo;
- (void)updateAuthorImage;
- (void)updateCellView;
- (void)viewDidMoveToWindow;
- (void)configureCellView;
@property(readonly, nonatomic) BOOL canShowSignature;
- (void)setBackgroundStyle:(long long)arg1;
- (void)prepareForReuse;
@property(readonly, nonatomic) NSString *dateString;
@property(readonly, nonatomic) NSImage *trackingInfoImage;
@property(readonly, nonatomic) NSString *commitMessage;
@property(readonly, nonatomic) NSString *authorName;
- (void)setObjectValue:(id)arg1;
@property(readonly, nonatomic) GTHistoryCommitItem *historyCommitItem;

@end

