//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol GTHistoryViewSettingsActions <NSObject>
- (void)selectGroupingType:(id)arg1;
- (void)selectCommitViewSize:(id)arg1;
- (void)toggleComparesBranches:(id)arg1;
- (void)toggleVerifiesGPGSignatures:(id)arg1;
- (void)toggleSortByDate:(id)arg1;
- (void)toggleSortByTopoOrder:(id)arg1;
- (void)toggleShowsFirstParentOnly:(id)arg1;
- (void)toggleGraph:(id)arg1;
@end

