//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSUserDefaults;

@interface GTHistoryViewSettingsController : NSObject
{
    NSUserDefaults *_userDefaults;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSUserDefaults *userDefaults; // @synthesize userDefaults=_userDefaults;
- (void)postChangeNotificationWithViewSettings:(id)arg1;
- (void)postChangeNotificationWithCurrentViewSettings;
- (void)setGroupingType:(long long)arg1;
- (long long)groupingType;
- (long long)effectiveCommitViewSize;
- (void)setGraphCommitViewSize:(long long)arg1;
- (long long)graphCommitViewSize;
- (void)setCommitViewSize:(long long)arg1;
- (long long)commitViewSize;
- (void)toggleVerifiesGPGSignatures;
- (void)setVerifiesGPGSignatures:(BOOL)arg1;
- (void)toggleComparesBranches;
- (void)setComparesBranches:(BOOL)arg1;
- (BOOL)comparesBranches;
- (BOOL)verifiesGPGSignatures;
- (void)toggleSortsByDate;
- (void)setSortsByDate:(BOOL)arg1;
- (BOOL)sortsByDate;
- (void)toggleSortsByTopoOrder;
- (void)setSortsByTopoOrder:(BOOL)arg1;
- (BOOL)sortsByTopoOrder;
- (void)toggleShowsFirstParentOnly;
- (void)setShowsFirstParentOnly:(BOOL)arg1;
- (BOOL)showsFirstParentOnly;
- (void)toggleShowsGraph;
- (void)setShowsGraph:(BOOL)arg1;
- (BOOL)showsGraph;
- (id)currentViewSettings;

@end

