//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

@class GTStackView;

@interface GTHistoryCommitActionView : NSView
{
    GTStackView *_itemsContainerView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) GTStackView *itemsContainerView; // @synthesize itemsContainerView=_itemsContainerView;
- (void)updateButtonStyles;
- (void)addActionButtonWithTitle:(id)arg1 action:(SEL)arg2 target:(id)arg3;
- (void)addActionButtonWithTitle:(id)arg1 action:(SEL)arg2;
- (void)removeAllActionButtons;
- (void)updateConstraints;
- (void)initItemsContainerView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

