//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableSet;
@protocol GTKeyEventObserving;

@interface GTKeyEventObserver : NSObject
{
    BOOL _alternateKeyDown;
    BOOL _commandKeyDown;
    id <GTKeyEventObserving> _observer;
    NSMutableSet *_observedKeyEquivalents;
    NSMutableSet *_observedKeyCodes;
    id _eventMonitor;
}

- (void).cxx_destruct;
@property(retain, nonatomic) id eventMonitor; // @synthesize eventMonitor=_eventMonitor;
@property(retain, nonatomic) NSMutableSet *observedKeyCodes; // @synthesize observedKeyCodes=_observedKeyCodes;
@property(retain, nonatomic) NSMutableSet *observedKeyEquivalents; // @synthesize observedKeyEquivalents=_observedKeyEquivalents;
@property(nonatomic, getter=isCommandKeyDown) BOOL commandKeyDown; // @synthesize commandKeyDown=_commandKeyDown;
@property(nonatomic, getter=isAlternateKeyDown) BOOL alternateKeyDown; // @synthesize alternateKeyDown=_alternateKeyDown;
@property(nonatomic) __weak id <GTKeyEventObserving> observer; // @synthesize observer=_observer;
- (void)observedKeyEquivalentPressed:(id)arg1;
- (BOOL)shouldHandleObservedKeyEquivalentEvent:(id)arg1;
- (void)commandKeyUp:(id)arg1;
- (void)commandKeyDown:(id)arg1;
- (void)alternateKeyUp:(id)arg1;
- (void)alternateKeyDown:(id)arg1;
- (void)unregisterObservers;
- (void)registerObservers;
- (void)stopObserving;
- (void)startObserving;
- (id)identifierForKeyCode:(unsigned short)arg1 modifierMask:(unsigned long long)arg2;
- (id)identifierForKeyEquivalent:(id)arg1 modifierMask:(unsigned long long)arg2;
- (BOOL)isObservingKeys;
- (void)removeAllKeyObservers;
- (void)removeObserverForKeyEquivalent:(id)arg1 modifierMask:(unsigned long long)arg2;
- (void)addObserverForKeyEquivalent:(id)arg1 modifierMask:(unsigned long long)arg2;
- (void)removeObserverForKeyCode:(unsigned short)arg1 modifierMask:(unsigned long long)arg2;
- (void)addObserverForKeyCode:(unsigned short)arg1 modifierMask:(unsigned long long)arg2;
- (void)dealloc;
- (id)initWithObserver:(id)arg1;
- (id)init;

@end

