//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTDialogueViewController.h"

@class GTGitRemote, GTGitRepository, NSArray;

@interface GTLFSPushRemoteViewController : GTDialogueViewController
{
    GTGitRepository *_repository;
    NSArray *_remotes;
    GTGitRemote *_selectedRemote;
}

+ (id)keyPathsForValuesAffectingValidatesSubmitButton;
- (void).cxx_destruct;
@property(retain, nonatomic) GTGitRemote *selectedRemote; // @synthesize selectedRemote=_selectedRemote;
@property(retain, nonatomic) NSArray *remotes; // @synthesize remotes=_remotes;
@property(readonly, nonatomic) GTGitRepository *repository; // @synthesize repository=_repository;
- (void)updateRemotePreselection;
- (void)loadRemotes;
- (BOOL)validatesSubmitButton;
- (void)viewDidLoad;
- (void)commonInit;
- (id)initWithRepository:(id)arg1;

@end

