//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTViewController.h"

#import "FNNavigationBarDelegate-Protocol.h"
#import "GTApplicationStatusObserving-Protocol.h"
#import "GTNavigationObserving-Protocol.h"
#import "GTPathControlDelegate-Protocol.h"

@class GTApplicationStatusObserver, GTCloneActivityController, GTNavigationBarBanderoleItem, GTNavigationBarButtonItem, GTPathControl, GTProductController, GTStackView, GTStateManager, NSBox, NSLayoutConstraint, NSMutableArray, NSString;

@interface GTMainWindowNavigationBarViewController : GTViewController <GTPathControlDelegate, FNNavigationBarDelegate, GTNavigationObserving, GTApplicationStatusObserving>
{
    GTCloneActivityController *_cloneActivityController;
    GTStackView *_leadingStackView;
    GTStackView *_trailingStackView;
    NSBox *_separator;
    NSLayoutConstraint *_separatorHeightConstraint;
    GTPathControl *_pathControl;
    GTNavigationBarBanderoleItem *_licenseBadge;
    GTNavigationBarButtonItem *_servicesButton;
    NSMutableArray *_customConstraints;
    GTStateManager *_viewState;
    GTApplicationStatusObserver *_applicationStatusObserver;
}

- (void).cxx_destruct;
@property(retain, nonatomic) GTApplicationStatusObserver *applicationStatusObserver; // @synthesize applicationStatusObserver=_applicationStatusObserver;
@property(retain, nonatomic) GTStateManager *viewState; // @synthesize viewState=_viewState;
@property(retain, nonatomic) NSMutableArray *customConstraints; // @synthesize customConstraints=_customConstraints;
@property(retain, nonatomic) GTNavigationBarButtonItem *servicesButton; // @synthesize servicesButton=_servicesButton;
@property(retain, nonatomic) GTNavigationBarBanderoleItem *licenseBadge; // @synthesize licenseBadge=_licenseBadge;
@property(retain, nonatomic) GTPathControl *pathControl; // @synthesize pathControl=_pathControl;
@property(nonatomic) __weak NSLayoutConstraint *separatorHeightConstraint; // @synthesize separatorHeightConstraint=_separatorHeightConstraint;
@property(nonatomic) __weak NSBox *separator; // @synthesize separator=_separator;
@property(nonatomic) __weak GTStackView *trailingStackView; // @synthesize trailingStackView=_trailingStackView;
@property(nonatomic) __weak GTStackView *leadingStackView; // @synthesize leadingStackView=_leadingStackView;
@property(retain, nonatomic) GTCloneActivityController *cloneActivityController; // @synthesize cloneActivityController=_cloneActivityController;
- (id)pathControlURLFromNavigationURL;
- (void)setServicesActive:(BOOL)arg1;
- (void)stopObservers;
- (void)startObservers;
- (void)applicationStatusDidChange:(id)arg1;
- (void)navigationPathComponentsDidUpdate:(id)arg1;
- (void)navigationURLDidUpdate:(id)arg1;
- (id)pathControl:(id)arg1 titleForComponentAtIndex:(unsigned long long)arg2;
- (id)pathControl:(id)arg1 imageForComponentAtIndex:(unsigned long long)arg2;
- (void)pathControl:(id)arg1 didSelectComponentAtIndex:(unsigned long long)arg2;
- (void)servicesButtonClicked;
- (void)updateLicenseBadge;
- (BOOL)needsUpdateLicenseBadge;
- (void)updatePathControl;
- (BOOL)needsUpdatePathControl;
- (void)updateViewState;
- (void)update;
- (void)viewWillDisappear;
- (void)viewDidAppear;
- (void)viewDidLoad;
- (void)configureSeparator;
- (void)configureNavigationBar;
- (void)configurePathControl;
- (void)configureLicenseBadge;
- (void)configureServicesButton;
- (void)configureTrailingStackeView;
- (void)configureLeadingStackeView;
- (void)configure;
@property(readonly, nonatomic) GTProductController *productController;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

