//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FNAppKit/FNWindowController.h>

#import "GTMainContentViewControllerDelegate-Protocol.h"
#import "GTMainWindowUIActions-Protocol.h"
#import "GTNavigationControllerDelegate-Protocol.h"
#import "GTNavigationHandler-Protocol.h"
#import "GTNavigationObserving-Protocol.h"
#import "GTQuickActionObjectActionPerforming-Protocol.h"
#import "GTUserDefaultsKeyObserving-Protocol.h"
#import "NSWindowDelegate-Protocol.h"

@class GTGitRepository, GTKeyPathObserver, GTMainContentViewController, GTMainWindowNavigationBarViewController, GTNavigationController, GTSearchController, GTStateManager, GTTitlebarAccessoryViewController, GTToolbarController, GTUserDefaultsKeyObserver, NSArray, NSString, NSUndoManager, NSUserDefaults;

@interface GTMainWindowController : FNWindowController <GTQuickActionObjectActionPerforming, NSWindowDelegate, GTUserDefaultsKeyObserving, GTNavigationObserving, GTNavigationControllerDelegate, GTMainContentViewControllerDelegate, GTMainWindowUIActions, GTNavigationHandler>
{
    GTMainContentViewController *_mainContentViewController;
    GTNavigationController *_navigationController;
    GTToolbarController *_toolbarController;
    GTTitlebarAccessoryViewController *_accessoryViewController;
    GTMainWindowNavigationBarViewController *_navigationBarViewController;
    GTStateManager *_state;
    GTUserDefaultsKeyObserver *_userDefaultsObserver;
    GTKeyPathObserver *_keyPathObserver;
    NSUserDefaults *_userDefaults;
    NSArray *_actionValidators;
    NSUndoManager *_defaultUndoManager;
}

+ (id)keyPathsForValuesAffectingRepository;
+ (void)load;
- (void).cxx_destruct;
@property(retain, nonatomic) NSUndoManager *defaultUndoManager; // @synthesize defaultUndoManager=_defaultUndoManager;
@property(retain, nonatomic) NSArray *actionValidators; // @synthesize actionValidators=_actionValidators;
@property(retain, nonatomic) NSUserDefaults *userDefaults; // @synthesize userDefaults=_userDefaults;
@property(retain, nonatomic) GTKeyPathObserver *keyPathObserver; // @synthesize keyPathObserver=_keyPathObserver;
@property(retain, nonatomic) GTUserDefaultsKeyObserver *userDefaultsObserver; // @synthesize userDefaultsObserver=_userDefaultsObserver;
@property(retain, nonatomic) GTStateManager *state; // @synthesize state=_state;
@property(retain, nonatomic) GTMainWindowNavigationBarViewController *navigationBarViewController; // @synthesize navigationBarViewController=_navigationBarViewController;
@property(retain, nonatomic) GTTitlebarAccessoryViewController *accessoryViewController; // @synthesize accessoryViewController=_accessoryViewController;
@property(retain, nonatomic) GTToolbarController *toolbarController; // @synthesize toolbarController=_toolbarController;
@property(retain, nonatomic) GTNavigationController *navigationController; // @synthesize navigationController=_navigationController;
@property(retain, nonatomic) GTMainContentViewController *mainContentViewController; // @synthesize mainContentViewController=_mainContentViewController;
- (void)restoreStateWithCoder:(id)arg1;
- (void)encodeRestorableStateWithCoder:(id)arg1;
- (BOOL)validateToolbarItem:(id)arg1;
- (BOOL)validateMenuItem:(id)arg1;
- (void)userDefaultsDidChangeKey:(id)arg1 change:(id)arg2;
- (void)contentViewControllerDidChangeContent:(id)arg1;
- (void)navigationControllerDidChangeNavigationURL:(id)arg1;
- (BOOL)navigationController:(id)arg1 shouldOpenNavigationURL:(id)arg2;
- (void)openNavigationURL:(id)arg1;
@property(readonly, nonatomic) NSString *navigationIdentifier;
- (void)newWindowForTab:(id)arg1;
- (void)findInContext:(id)arg1;
- (void)searchInScope:(id)arg1;
- (void)openInTerminalForRepositoryWithUUID:(id)arg1;
- (void)openInFinderForRepositoryWithUUID:(id)arg1;
- (void)showQuickActions:(id)arg1;
- (void)openQuickly:(id)arg1;
- (void)showBookmarkWithID:(id)arg1;
- (void)showBookmarks:(id)arg1;
- (void)showServiceAccountInfoForAccountWithID:(id)arg1;
- (void)showServicePublicKeysForAccountWithID:(id)arg1;
- (void)showServiceRepositoriesForAccountWithID:(id)arg1;
- (void)showServices:(id)arg1;
- (void)showRepository:(id)arg1;
- (void)navigateForward:(id)arg1;
- (void)navigateBack:(id)arg1;
- (void)showCommitForRevision:(id)arg1 repositoryWithUUID:(id)arg2;
- (void)showTreeForFilePath:(id)arg1 revision:(id)arg2 repositoryWithUUID:(id)arg3;
- (void)showRawFileForFilePath:(id)arg1 revision:(id)arg2 repositoryWithUUID:(id)arg3;
- (void)showBlameForFilePath:(id)arg1 revision:(id)arg2 repositoryWithUUID:(id)arg3;
- (void)showFileHistoryForFilePath:(id)arg1 revision:(id)arg2 repositoryWithUUID:(id)arg3;
- (void)showSubmoduleSettingsForSubmoduleWithName:(id)arg1 repositoryWithUUID:(id)arg2;
- (void)showRemoteBranchForRefName:(id)arg1 repositoryWithUUID:(id)arg2;
- (void)showRemoteSettingsForRemoteWithName:(id)arg1 repositoryWithUUID:(id)arg2;
- (void)showTagForRefName:(id)arg1 repositoryWithUUID:(id)arg2;
- (void)showBranchForRefName:(id)arg1 repositoryWithUUID:(id)arg2;
- (void)showRepositorySettingsForRepositoryWithUUID:(id)arg1;
- (void)showPullRequestsForRepositoryWithUUID:(id)arg1;
- (void)showReflogForRepositoryWithUUID:(id)arg1;
- (void)showStashesForRepositoryWithUUID:(id)arg1;
- (void)showHistoryForRepositoryWithUUID:(id)arg1;
- (void)showWorkingCopyForRepositoryWithUUID:(id)arg1;
- (void)showRepositoryWithUUID:(id)arg1;
- (void)updateRepresentedURL;
- (void)updateTitleBarVisibility;
- (BOOL)needsUpdateRepresentedURL;
- (BOOL)needsUpdateTitleBarVisibility;
- (void)updateViewState;
- (void)update;
- (id)windowWillReturnUndoManager:(id)arg1;
- (void)repositoryDidChange;
- (void)windowWillClose:(id)arg1;
- (void)windowDidEnterFullScreen:(id)arg1;
- (void)windowDidResignMain:(id)arg1;
- (void)windowDidBecomeMain:(id)arg1;
- (void)windowDidResignKey:(id)arg1;
- (void)windowDidBecomeKey:(id)arg1;
- (void)windowDidLoad;
- (void)stopObservers;
- (void)startObservers;
- (void)configureToolbar;
- (void)configureTitlebarAccessoryView;
- (void)configureWindow;
@property(readonly, nonatomic) GTGitRepository *repository;
@property(readonly, nonatomic) GTSearchController *searchController;
- (void)dealloc;
- (void)commonInit;
- (void)performThemeActionWithDescription:(id)arg1 item:(id)arg2;
- (void)performUserProfileActionWithDescription:(id)arg1 item:(id)arg2;
- (void)performTreeEntryActionWithDescription:(id)arg1 item:(id)arg2;
- (void)performSubmoduleActionWithDescription:(id)arg1 item:(id)arg2;
- (void)performRemoteActionWithDescription:(id)arg1 item:(id)arg2;
- (void)performRevisionActionWithDescription:(id)arg1 item:(id)arg2;
- (void)performStashActionWithDescription:(id)arg1 item:(id)arg2;
- (void)performTagActionWithDescription:(id)arg1 item:(id)arg2;
- (void)performRemoteBranchActionWithDescription:(id)arg1 item:(id)arg2;
- (void)performBranchActionWithDescription:(id)arg1 item:(id)arg2;
- (void)performCommitActionWithDescription:(id)arg1 item:(id)arg2;
- (void)performNavigationActionWithDescription:(id)arg1 item:(id)arg2;
- (void)performActionWithDescription:(id)arg1 item:(id)arg2;
@property(readonly, nonatomic) NSString *quickActionsIdentifier;
- (void)showViewForViewReferenceURL:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

