//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

@class NSColor, NSFont, NSImageView, NSTextField;

@interface GTMergeViewEmptyItemView : NSView
{
    double _lineWidth;
    double _dashLength;
    double _dashSpaceLength;
    double _dashPhase;
    double _borderRadius;
    NSColor *_lineColor;
    NSColor *_backgroundColor;
    NSColor *_textColor;
    NSFont *_font;
    NSTextField *_label;
    NSImageView *_imageView;
}

- (void).cxx_destruct;
@property(nonatomic) __weak NSImageView *imageView; // @synthesize imageView=_imageView;
@property(nonatomic) __weak NSTextField *label; // @synthesize label=_label;
@property(retain, nonatomic) NSFont *font; // @synthesize font=_font;
@property(retain, nonatomic) NSColor *textColor; // @synthesize textColor=_textColor;
@property(retain, nonatomic) NSColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(retain, nonatomic) NSColor *lineColor; // @synthesize lineColor=_lineColor;
@property(nonatomic) double borderRadius; // @synthesize borderRadius=_borderRadius;
@property(nonatomic) double dashPhase; // @synthesize dashPhase=_dashPhase;
@property(nonatomic) double dashSpaceLength; // @synthesize dashSpaceLength=_dashSpaceLength;
@property(nonatomic) double dashLength; // @synthesize dashLength=_dashLength;
@property(nonatomic) double lineWidth; // @synthesize lineWidth=_lineWidth;
- (void)drawRect:(struct CGRect)arg1;
- (void)awakeFromNib;
- (void)commonInit;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

