//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTMenuGenerator.h"

@class GTGitMergeConflictInfo, GTGitRepository, GTGitWorkingTreeEntry, GTOpenFileWithApplicationMenuGenerator;

@interface GTMergeConflictVersionMenuGenerator : GTMenuGenerator
{
    GTGitRepository *_repository;
    long long _mergeConflictVersion;
    GTGitWorkingTreeEntry *_workingTreeEntry;
    GTGitMergeConflictInfo *_mergeConflictInfo;
    id _target;
    GTOpenFileWithApplicationMenuGenerator *_appMenuGenerator;
}

- (void).cxx_destruct;
@property(retain, nonatomic) GTOpenFileWithApplicationMenuGenerator *appMenuGenerator; // @synthesize appMenuGenerator=_appMenuGenerator;
@property(nonatomic) __weak id target; // @synthesize target=_target;
@property(retain, nonatomic) GTGitMergeConflictInfo *mergeConflictInfo; // @synthesize mergeConflictInfo=_mergeConflictInfo;
@property(retain, nonatomic) GTGitWorkingTreeEntry *workingTreeEntry; // @synthesize workingTreeEntry=_workingTreeEntry;
@property(nonatomic) long long mergeConflictVersion; // @synthesize mergeConflictVersion=_mergeConflictVersion;
@property(retain, nonatomic) GTGitRepository *repository; // @synthesize repository=_repository;
- (id)revisionsForComparingTheirVersionToMyVersion;
- (id)revisionsForComparingMyVersionToTheirVersion;
- (id)revisionsForComparingTheirVersionToBaseVersion;
- (id)revisionsForComparingMyVersionToBaseVersion;
- (void)addCompareTheirsToMineMenuItemWithWorkingTreeEntry:(id)arg1;
- (void)addCompareTheirsToBaseMenuItemWithWorkingTreeEntry:(id)arg1;
- (void)addCompareToMineToTheirsMenuItemWithWorkingTreeEntry:(id)arg1;
- (void)addCompareMineToBaseMenuItemWithWorkingTreeEntry:(id)arg1;
- (void)addSaveMenuItemWithWorkingTreeEntry:(id)arg1;
- (void)addOpenWithMenuItemWithWorkingTreeEntry:(id)arg1;
- (void)addOpenMenuItemWithWorkingTreeEntry:(id)arg1;
- (void)addActionMenuItem;
- (BOOL)isConflictVersionDeleted;
- (BOOL)isConflictVersionMine;
- (void)makeMenuItems;

@end

