//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSVisualEffectView.h>

#import "GTMergeViewActionBarDelegate-Protocol.h"
#import "GTMergeViewBasicItemViewDelegate-Protocol.h"
#import "GTMergeViewMergeProcessViewDelegate-Protocol.h"

@class FNView, GTFullSizeContentView, GTKeyPathObserver, GTMergeViewActionBar, GTMergeViewBasicItem, GTMergeViewMergeProcessView, GTMergeViewMergeResultItemView, GTMergeViewSelectionController, GTMergeViewSourceItemView, NSArray, NSColor, NSIndexSet, NSString;
@protocol GTMergeViewDelegate;

@interface GTMergeView : NSVisualEffectView <GTMergeViewMergeProcessViewDelegate, GTMergeViewBasicItemViewDelegate, GTMergeViewActionBarDelegate>
{
    BOOL _isHoldingOptionKey;
    BOOL _isResolving;
    BOOL _isResolved;
    id <GTMergeViewDelegate> _delegate;
    GTMergeViewSourceItemView *_sourceItemPrototype;
    GTMergeViewMergeResultItemView *_mergeResultItemPrototype;
    FNView *_emptyItemPrototype;
    GTMergeViewBasicItem *_result;
    NSArray *_sourceItems;
    NSArray *_resolveButtonTitles;
    NSString *_mergeToolTitle;
    GTMergeViewSelectionController *_selectionController;
    NSArray *_sourceItemViews;
    FNView *_emptyResultView;
    GTMergeViewMergeResultItemView *_resultView;
    GTMergeViewMergeProcessView *_processView;
    FNView *_mergeProcessContainer;
    FNView *_mergeResultContainer;
    GTMergeViewActionBar *_actionBar;
    NSColor *_backgroundColor;
    GTKeyPathObserver *_keyPathObserver;
    GTFullSizeContentView *_observedFullSizeContentView;
}

- (void).cxx_destruct;
@property(nonatomic) BOOL isResolved; // @synthesize isResolved=_isResolved;
@property(nonatomic) BOOL isResolving; // @synthesize isResolving=_isResolving;
@property(nonatomic) BOOL isHoldingOptionKey; // @synthesize isHoldingOptionKey=_isHoldingOptionKey;
@property(nonatomic) __weak GTFullSizeContentView *observedFullSizeContentView; // @synthesize observedFullSizeContentView=_observedFullSizeContentView;
@property(retain, nonatomic) GTKeyPathObserver *keyPathObserver; // @synthesize keyPathObserver=_keyPathObserver;
@property(retain, nonatomic) NSColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(retain, nonatomic) GTMergeViewActionBar *actionBar; // @synthesize actionBar=_actionBar;
@property(retain, nonatomic) FNView *mergeResultContainer; // @synthesize mergeResultContainer=_mergeResultContainer;
@property(retain, nonatomic) FNView *mergeProcessContainer; // @synthesize mergeProcessContainer=_mergeProcessContainer;
@property(retain, nonatomic) GTMergeViewMergeProcessView *processView; // @synthesize processView=_processView;
@property(retain, nonatomic) GTMergeViewMergeResultItemView *resultView; // @synthesize resultView=_resultView;
@property(retain, nonatomic) FNView *emptyResultView; // @synthesize emptyResultView=_emptyResultView;
@property(retain, nonatomic) NSArray *sourceItemViews; // @synthesize sourceItemViews=_sourceItemViews;
@property(retain, nonatomic) GTMergeViewSelectionController *selectionController; // @synthesize selectionController=_selectionController;
@property(retain, nonatomic) NSString *mergeToolTitle; // @synthesize mergeToolTitle=_mergeToolTitle;
@property(retain, nonatomic) NSArray *resolveButtonTitles; // @synthesize resolveButtonTitles=_resolveButtonTitles;
@property(retain, nonatomic) NSArray *sourceItems; // @synthesize sourceItems=_sourceItems;
@property(retain, nonatomic) GTMergeViewBasicItem *result; // @synthesize result=_result;
@property __weak FNView *emptyItemPrototype; // @synthesize emptyItemPrototype=_emptyItemPrototype;
@property __weak GTMergeViewMergeResultItemView *mergeResultItemPrototype; // @synthesize mergeResultItemPrototype=_mergeResultItemPrototype;
@property __weak GTMergeViewSourceItemView *sourceItemPrototype; // @synthesize sourceItemPrototype=_sourceItemPrototype;
@property __weak id <GTMergeViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) BOOL allowMultiSelection;
- (void)waitForResolving;
- (void)askToConfirm;
- (void)askToResolve;
- (void)mergeViewActionBar:(id)arg1 confirmResolve:(id)arg2;
- (void)mergeViewActionBar:(id)arg1 startOverResolve:(id)arg2;
- (void)mergeViewActionBar:(id)arg1 cancelResolving:(id)arg2;
- (void)mergeViewActionBar:(id)arg1 startResolving:(id)arg2;
- (void)mergeViewBasicItemViewDidBecomeSelected:(id)arg1;
- (void)mergeViewMergeProcessView:(id)arg1 didSelectIndices:(id)arg2;
- (void)setTargetItem:(id)arg1;
- (void)setAllHintedSourceItemsForResultView;
- (void)setAllSourceItemsForResultView;
- (void)setSourceItemIndexForResultView:(long long)arg1;
- (void)setNoSourceItemForResultView;
- (void)updateResultContainer;
- (void)refreshSelection;
- (void)updateResolveButtonTitle;
- (void)flagsChanged:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)updateConstraints;
- (void)addEmptyMergeResult;
- (void)addMergeResult;
- (void)addMergeProcessView;
- (id)addSourceItem:(id)arg1;
- (void)reloadContainerAndContentViews;
@property(readonly, nonatomic) NSIndexSet *hintedSourceItemIndices;
@property(readonly, nonatomic) NSIndexSet *selectedSourceItemIndices;
- (void)setSourceItems:(id)arg1 selectedSourceItemIndices:(id)arg2 hintedSourceItemIndices:(id)arg3;
- (void)fullSizeLayoutContentRectDidChange;
- (void)stopObservingFullSizeContentView;
- (void)startObservingFullSizeContentView;
- (void)viewWillDraw;
- (void)viewDidMoveToWindow;
- (void)viewWillMoveToWindow:(id)arg1;
@property(readonly, nonatomic, getter=isObservingFullSizeContentView) BOOL observingFullSizeContentView;
- (void)dealloc;
- (void)commonInit;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

