//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTBookmarkOperation.h"

@class NSArray, NSManagedObjectID;

@interface GTMoveBookmarksOperation : GTBookmarkOperation
{
    NSArray *_bookmarkIDs;
    NSManagedObjectID *_parentBookmarkID;
    unsigned long long _childIndex;
}

+ (id)operationWithManagedObjectContext:(id)arg1 bookmarkIDs:(id)arg2 parentBookmarkID:(id)arg3 childIndex:(unsigned long long)arg4;
- (void).cxx_destruct;
@property(nonatomic) unsigned long long childIndex; // @synthesize childIndex=_childIndex;
@property(retain, nonatomic) NSManagedObjectID *parentBookmarkID; // @synthesize parentBookmarkID=_parentBookmarkID;
@property(retain, nonatomic) NSArray *bookmarkIDs; // @synthesize bookmarkIDs=_bookmarkIDs;
- (void)execute;
- (id)initWithManagedObjectContext:(id)arg1 bookmarkIDs:(id)arg2 parentBookmarkID:(id)arg3 childIndex:(unsigned long long)arg4;

@end

