//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTRegistrationViewController.h"

@class FNProductNewsletterAPIClient, NSAlert, NSButton, NSString, NSView;

@interface GTNewsletterSubscriptionViewController : GTRegistrationViewController
{
    NSButton *_subscribeButton;
    NSView *_contentInputView;
    NSView *_thankYouView;
    NSButton *_quitButton;
    NSString *_contentText;
    NSString *_email;
    FNProductNewsletterAPIClient *_newsletterAPIClient;
    NSAlert *_alert;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSAlert *alert; // @synthesize alert=_alert;
@property(retain, nonatomic) FNProductNewsletterAPIClient *newsletterAPIClient; // @synthesize newsletterAPIClient=_newsletterAPIClient;
@property(retain, nonatomic) NSString *email; // @synthesize email=_email;
@property(retain, nonatomic) NSString *contentText; // @synthesize contentText=_contentText;
@property(retain, nonatomic) NSButton *quitButton; // @synthesize quitButton=_quitButton;
@property(retain, nonatomic) NSView *thankYouView; // @synthesize thankYouView=_thankYouView;
@property(retain, nonatomic) NSView *contentInputView; // @synthesize contentInputView=_contentInputView;
@property(retain, nonatomic) NSButton *subscribeButton; // @synthesize subscribeButton=_subscribeButton;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)setThankYouView;
- (void)controllerDidSubscribeNewsletter;
- (void)controllerDidFailToSubscribeNewsletterWithError:(id)arg1;
- (void)quit:(id)arg1;
- (void)cancel:(id)arg1;
- (void)startSubscribe:(id)arg1;
- (void)openTowerWebsite:(id)arg1;
- (void)openTwitter:(id)arg1;
- (void)setSubscribeButtonState:(BOOL)arg1;
- (void)configureCancelButton;
- (void)configureCloseButton;
- (void)configureButtons;
- (void)viewDidLoad;
- (void)awakeFromNib;
- (void)dealloc;
- (void)commonInit;

@end

