//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

@class GTStateManager, NSDictionary, NSImage, NSImageView, NSLayoutConstraint, NSMutableArray, NSString, NSTextField;

@interface GTPathView : NSView
{
    BOOL _active;
    NSString *_title;
    NSImage *_image;
    SEL _action;
    id _target;
    GTStateManager *_viewState;
    NSTextField *_labelTextField;
    NSImageView *_imageView;
    NSLayoutConstraint *_widthConstraint;
    NSLayoutConstraint *_textWidthConstraint;
    NSDictionary *_titleAttributes;
    NSImage *_normalImage;
    NSImage *_clickedImage;
    double _padding;
    double _lastWidth;
    NSLayoutConstraint *_revealWidthConstraint;
    NSMutableArray *_customConstraints;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *customConstraints; // @synthesize customConstraints=_customConstraints;
@property(retain, nonatomic) NSLayoutConstraint *revealWidthConstraint; // @synthesize revealWidthConstraint=_revealWidthConstraint;
@property(nonatomic) double lastWidth; // @synthesize lastWidth=_lastWidth;
@property(nonatomic) double padding; // @synthesize padding=_padding;
@property(retain, nonatomic) NSImage *clickedImage; // @synthesize clickedImage=_clickedImage;
@property(retain, nonatomic) NSImage *normalImage; // @synthesize normalImage=_normalImage;
@property(retain, nonatomic) NSDictionary *titleAttributes; // @synthesize titleAttributes=_titleAttributes;
@property(retain, nonatomic) NSLayoutConstraint *textWidthConstraint; // @synthesize textWidthConstraint=_textWidthConstraint;
@property(retain, nonatomic) NSLayoutConstraint *widthConstraint; // @synthesize widthConstraint=_widthConstraint;
@property(nonatomic) __weak NSImageView *imageView; // @synthesize imageView=_imageView;
@property(nonatomic) __weak NSTextField *labelTextField; // @synthesize labelTextField=_labelTextField;
@property(retain, nonatomic) GTStateManager *viewState; // @synthesize viewState=_viewState;
@property(nonatomic) BOOL active; // @synthesize active=_active;
@property(nonatomic) __weak id target; // @synthesize target=_target;
@property(nonatomic) SEL action; // @synthesize action=_action;
@property(retain, nonatomic) NSImage *image; // @synthesize image=_image;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
- (id)description;
- (id)activeImageForImage:(id)arg1;
- (struct CGSize)textSize;
- (struct CGSize)imageSize;
- (struct CGSize)intrinsicContentSize;
- (void)updateConstraints;
- (void)updateImageWithClickedState:(BOOL)arg1;
- (void)updateToolTip;
- (void)updateLabel;
- (void)updateImageView;
- (BOOL)needsUpdateLabel;
- (BOOL)needsUpdateImageView;
- (void)updateViewState;
- (void)update;
- (void)mouseUp:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)configureTrackingArea;
- (void)configureLabel;
- (void)configureImageView;
- (void)configureSubviews;
- (void)configure;
- (void)dealloc;
- (id)initWithTitle:(id)arg1 image:(id)arg2;
- (id)initWithTitle:(id)arg1;

@end

