//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSControl.h>

@class GTStateManager, NSMutableArray, NSTrackingArea, NSURL;
@protocol GTPathControlDelegate;

@interface GTPathControl : NSControl
{
    NSURL *_URL;
    id <GTPathControlDelegate> _delegate;
    GTStateManager *_viewState;
    NSMutableArray *_pathViews;
    NSTrackingArea *_mouseTrackingArea;
    NSMutableArray *_customConstraints;
    long long _activeItemIndex;
    struct CGSize _itemSize;
}

+ (id)baseURL;
- (void).cxx_destruct;
@property(nonatomic) long long activeItemIndex; // @synthesize activeItemIndex=_activeItemIndex;
@property(retain, nonatomic) NSMutableArray *customConstraints; // @synthesize customConstraints=_customConstraints;
@property(retain, nonatomic) NSTrackingArea *mouseTrackingArea; // @synthesize mouseTrackingArea=_mouseTrackingArea;
@property(retain, nonatomic) NSMutableArray *pathViews; // @synthesize pathViews=_pathViews;
@property(retain, nonatomic) GTStateManager *viewState; // @synthesize viewState=_viewState;
@property(nonatomic) struct CGSize itemSize; // @synthesize itemSize=_itemSize;
@property(nonatomic) __weak id <GTPathControlDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSURL *URL; // @synthesize URL=_URL;
- (long long)indexOfPathView:(id)arg1;
- (void)removePathItem:(id)arg1;
- (void)addPathItem:(id)arg1;
- (void)addPathDivider;
- (void)deactivateActivePathComponent;
- (void)activateLastPathComponent;
- (void)activatePathComponentAtIndex:(unsigned long long)arg1;
- (struct CGSize)intrinsicContentSize;
- (void)updateConstraints;
- (void)resetActivePathViews;
- (void)updateActiveItem;
- (void)updatePathComponents;
- (BOOL)needsUpdateActiveItem;
- (BOOL)needsUpdatePathComponents;
- (void)updateViewState;
- (void)update;
- (void)pathControlDidSelectItem:(id)arg1;
- (void)commonInit;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

