//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTPullRequestsChangesetItem.h"

@class FNGitDiffChunk, GTGitChangesetEntry, NSString;

@interface GTPullRequestsChangesetChunkHeaderItem : GTPullRequestsChangesetItem
{
    GTGitChangesetEntry *_changesetEntry;
    NSString *_revision;
    long long _chunkNumber;
}

+ (id)identifierWithChunkNumber:(long long)arg1 changesetEntry:(id)arg2 revision:(id)arg3;
+ (id)chunkHeaderItemWithDiffChunk:(id)arg1 chunkNumber:(long long)arg2 changesetEntry:(id)arg3 revision:(id)arg4;
- (void).cxx_destruct;
@property(nonatomic) long long chunkNumber; // @synthesize chunkNumber=_chunkNumber;
@property(retain, nonatomic) NSString *revision; // @synthesize revision=_revision;
@property(retain, nonatomic) GTGitChangesetEntry *changesetEntry; // @synthesize changesetEntry=_changesetEntry;
- (void)updateWithItem:(id)arg1;
@property(readonly, nonatomic) FNGitDiffChunk *diffChunk;
- (id)initWithDiffChunk:(id)arg1 chunkNumber:(long long)arg2 changesetEntry:(id)arg3 revision:(id)arg4;

@end

