//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTPullRequestsChangesetItem.h"

@class GTGitChangesetEntry, NSString;

@interface GTPullRequestsChangesetFileItem : GTPullRequestsChangesetItem
{
    NSString *_revision;
}

+ (id)identifierForChangesetEntry:(id)arg1 revision:(id)arg2;
+ (id)fileItemWithChangesetEntry:(id)arg1 revision:(id)arg2;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *revision; // @synthesize revision=_revision;
- (void)updateWithItem:(id)arg1;
@property(readonly, nonatomic) GTGitChangesetEntry *changesetEntry;
- (BOOL)isSelectable;
- (id)initWithChangesetEntry:(id)arg1 revision:(id)arg2;

@end

