//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTPullRequestsConversationItem.h"

@class GTGitCommit, NSDate, NSString;

@interface GTPullRequestsConversationCommitItem : GTPullRequestsConversationItem
{
    NSString *_subject;
    NSString *_commitHash;
    NSString *_authorName;
    NSString *_authorEmail;
    NSDate *_committerDate;
}

+ (id)identifierWithCommit:(id)arg1;
+ (id)commitItemWithCommit:(id)arg1;
- (void).cxx_destruct;
@property(copy, nonatomic) NSDate *committerDate; // @synthesize committerDate=_committerDate;
@property(copy, nonatomic) NSString *authorEmail; // @synthesize authorEmail=_authorEmail;
@property(copy, nonatomic) NSString *authorName; // @synthesize authorName=_authorName;
@property(copy, nonatomic) NSString *commitHash; // @synthesize commitHash=_commitHash;
@property(copy, nonatomic) NSString *subject; // @synthesize subject=_subject;
- (void)updateWithCommitItem:(id)arg1;
@property(readonly, nonatomic) GTGitCommit *commit;
- (id)itemDate;
- (id)initWithCommit:(id)arg1;

@end

