//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSFormatter.h>

@interface GTPullRequestsConversationHeaderInfoFormatter : NSFormatter
{
    struct _NSRange _authorRange;
    struct _NSRange _commitsRange;
    struct _NSRange _baseBranchRange;
    struct _NSRange _branchRange;
}

@property(nonatomic) struct _NSRange branchRange; // @synthesize branchRange=_branchRange;
@property(nonatomic) struct _NSRange baseBranchRange; // @synthesize baseBranchRange=_baseBranchRange;
@property(nonatomic) struct _NSRange commitsRange; // @synthesize commitsRange=_commitsRange;
@property(nonatomic) struct _NSRange authorRange; // @synthesize authorRange=_authorRange;
- (id)attributedStringForObjectValue:(id)arg1 withDefaultAttributes:(id)arg2;
- (id)stringForObjectValue:(id)arg1;

@end

