//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTBaseRepositoryViewController.h"

#import "GTGitRepositoryObserving-Protocol.h"
#import "GTPullRequestsConversationItemControllerDelegate-Protocol.h"
#import "GTRepositoryHistoryActions-Protocol.h"
#import "GTRepositoryPullRequestsActions-Protocol.h"
#import "GTSearchControllerDelegate-Protocol.h"
#import "GTServicesObserving-Protocol.h"
#import "GTUserDefaultsKeyObserving-Protocol.h"
#import "NSMenuDelegate-Protocol.h"
#import "NSOutlineViewDataSource-Protocol.h"
#import "NSOutlineViewDelegate-Protocol.h"

@class GTBackgroundSession, GTGitLogOptions, GTHistoryViewSettingsController, GTPullRequestActionSenderValidator, GTPullRequestsConversationItemController, GTPullRequestsConversationMenuGenerator, GTPullRequestsConversationSearchScopeConfiguration, GTSearchController, GTServicePullRequest, GTServicesObserver, NSCache, NSOutlineView, NSString, NSTimer, NSView;

@interface GTPullRequestsConversationViewController : GTBaseRepositoryViewController <NSOutlineViewDelegate, NSOutlineViewDataSource, GTPullRequestsConversationItemControllerDelegate, GTServicesObserving, GTGitRepositoryObserving, GTSearchControllerDelegate, GTRepositoryPullRequestsActions, GTUserDefaultsKeyObserving, NSMenuDelegate, GTRepositoryHistoryActions>
{
    GTServicePullRequest *_pullRequest;
    GTPullRequestsConversationItemController *_itemController;
    NSOutlineView *_outlineView;
    GTServicesObserver *_servicesObserver;
    GTSearchController *_searchController;
    GTPullRequestsConversationSearchScopeConfiguration *_searchScopeConfiguration;
    GTPullRequestsConversationMenuGenerator *_menuGenerator;
    GTPullRequestActionSenderValidator *_pullRequestsActionValidator;
    NSTimer *_tableViewLayoutTimer;
    GTBackgroundSession *_backgroundSession;
    NSCache *_collapsedItemIdentifiersByPullRequest;
    NSCache *_selectedItemsByPullRequest;
    NSCache *_scrollPositionByPullRequest;
    GTHistoryViewSettingsController *_historyViewSettingsController;
}

- (void).cxx_destruct;
@property(retain, nonatomic) GTHistoryViewSettingsController *historyViewSettingsController; // @synthesize historyViewSettingsController=_historyViewSettingsController;
@property(retain, nonatomic) NSCache *scrollPositionByPullRequest; // @synthesize scrollPositionByPullRequest=_scrollPositionByPullRequest;
@property(retain, nonatomic) NSCache *selectedItemsByPullRequest; // @synthesize selectedItemsByPullRequest=_selectedItemsByPullRequest;
@property(retain, nonatomic) NSCache *collapsedItemIdentifiersByPullRequest; // @synthesize collapsedItemIdentifiersByPullRequest=_collapsedItemIdentifiersByPullRequest;
@property(retain, nonatomic) GTBackgroundSession *backgroundSession; // @synthesize backgroundSession=_backgroundSession;
@property(retain, nonatomic) NSTimer *tableViewLayoutTimer; // @synthesize tableViewLayoutTimer=_tableViewLayoutTimer;
@property(retain, nonatomic) GTPullRequestActionSenderValidator *pullRequestsActionValidator; // @synthesize pullRequestsActionValidator=_pullRequestsActionValidator;
@property(retain, nonatomic) GTPullRequestsConversationMenuGenerator *menuGenerator; // @synthesize menuGenerator=_menuGenerator;
@property(retain, nonatomic) GTPullRequestsConversationSearchScopeConfiguration *searchScopeConfiguration; // @synthesize searchScopeConfiguration=_searchScopeConfiguration;
@property(nonatomic) __weak GTSearchController *searchController; // @synthesize searchController=_searchController;
@property(retain, nonatomic) GTServicesObserver *servicesObserver; // @synthesize servicesObserver=_servicesObserver;
@property(nonatomic) __weak NSOutlineView *outlineView; // @synthesize outlineView=_outlineView;
@property(retain, nonatomic) GTPullRequestsConversationItemController *itemController; // @synthesize itemController=_itemController;
@property(retain, nonatomic) GTServicePullRequest *pullRequest; // @synthesize pullRequest=_pullRequest;
- (id)commitAuthorsFromItems;
- (id)commentAuthorsFromItems;
- (id)localBranchForPullRequestBranch:(id)arg1;
- (id)bodyItemForSender:(id)arg1;
- (id)commentItemForSender:(id)arg1;
- (void)restoreSelection;
- (void)storeSelection;
- (void)reloadOutlineView;
- (void)expandItem:(id)arg1;
- (void)expandItemsIfNeeded;
- (id)pullRequestIdentifier;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (BOOL)validateMenuItem:(id)arg1;
- (void)menuNeedsUpdate:(id)arg1;
@property(readonly, nonatomic) NSView *searchControllerKeyView;
- (void)searchControllerDidEndSearching;
- (void)searchControllerDidUpdate;
- (void)windowDidChangeFirstResponder;
- (void)repositoryDidFinishRemoteOperation:(id)arg1;
- (void)repositoryDidUpdate:(id)arg1;
- (void)repositoryDidChange:(id)arg1;
- (void)userDefaultsDidChangeKey:(id)arg1 change:(id)arg2;
- (void)servicePullRequestCommentsDidUpdate:(id)arg1;
- (void)servicePullRequestsDidUpdate:(id)arg1;
- (void)pullRequestsConversationItemControllerWillChangeItems:(id)arg1;
- (void)pullRequestsConversationItemControllerDidChangeItems:(id)arg1;
- (void)pullRequestsConversationItemController:(id)arg1 didUpdateItems:(id)arg2;
- (void)pullRequestsConversationItemController:(id)arg1 didMoveItemAtIndex:(unsigned long long)arg2 inParent:(id)arg3 toIndex:(unsigned long long)arg4 inParent:(id)arg5;
- (void)pullRequestsConversationItemController:(id)arg1 didInsertItemsAtIndexPaths:(id)arg2 inParent:(id)arg3;
- (void)pullRequestsConversationItemController:(id)arg1 didDeleteItemsAtIndexPaths:(id)arg2 inParent:(id)arg3;
- (void)pullRequestsConversationItemControllerDidReloadItems:(id)arg1;
- (id)outlineView:(id)arg1 objectValueForTableColumn:(id)arg2 byItem:(id)arg3;
- (id)outlineView:(id)arg1 child:(long long)arg2 ofItem:(id)arg3;
- (BOOL)outlineView:(id)arg1 isItemExpandable:(id)arg2;
- (long long)outlineView:(id)arg1 numberOfChildrenOfItem:(id)arg2;
- (void)outlineViewItemDidCollapse:(id)arg1;
- (void)outlineViewItemDidExpand:(id)arg1;
- (void)outlineViewSelectionDidChange:(id)arg1;
- (void)outlineViewColumnDidResize:(id)arg1;
- (id)outlineView:(id)arg1 rowViewForItem:(id)arg2;
- (double)outlineView:(id)arg1 heightOfRowByItem:(id)arg2;
- (id)outlineView:(id)arg1 viewForTableColumn:(id)arg2 item:(id)arg3;
- (BOOL)outlineView:(id)arg1 shouldSelectItem:(id)arg2;
- (BOOL)outlineView:(id)arg1 shouldEditTableColumn:(id)arg2 item:(id)arg3;
- (void)repositoryDidChange;
- (void)outlineViewClicked:(id)arg1;
- (void)copyRevisionsToClipboard:(id)arg1;
- (void)showCommits:(id)arg1;
- (void)showCommit:(id)arg1;
- (void)editPullRequestBody:(id)arg1;
- (void)deleteComment:(id)arg1;
- (void)editComment:(id)arg1;
- (void)replyToComment:(id)arg1;
- (void)addComment:(id)arg1;
- (void)updateItemController;
- (void)updateRepositoryProperties;
- (BOOL)needsUpdateRepositoryProperties;
- (BOOL)needsUpdateItemController;
- (void)updateViewComponents;
- (void)updateViewState;
- (void)viewWillDisappear;
- (void)viewDidAppear;
- (void)viewDidLoad;
- (void)invalidateTimers;
- (void)configureUserDefaultsObserver;
- (void)configureOutlineView;
- (void)configure;
@property(readonly, nonatomic) GTGitLogOptions *logOptions;
@property(readonly, nonatomic) NSString *currentPullRequestKey;
- (id)selectedObjects;
- (id)affectedObjects;
- (id)selectedItems;
- (id)affectedItems;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

