//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@interface GTPullRequestStatusControllerState : NSObject <NSCopying>
{
    BOOL _baseBranchMissing;
    BOOL _headCommitHashMissing;
    BOOL _headCommitObjectNotFound;
    BOOL _headCommitHashNotMatching;
    BOOL _headBranchUntracked;
    long long _type;
}

@property(nonatomic, getter=isHeadBranchUntracked) BOOL headBranchUntracked; // @synthesize headBranchUntracked=_headBranchUntracked;
@property(nonatomic, getter=isHeadCommitHashNotMatching) BOOL headCommitHashNotMatching; // @synthesize headCommitHashNotMatching=_headCommitHashNotMatching;
@property(nonatomic, getter=isHeadCommitObjectNotFound) BOOL headCommitObjectNotFound; // @synthesize headCommitObjectNotFound=_headCommitObjectNotFound;
@property(nonatomic, getter=isHeadCommitHashMissing) BOOL headCommitHashMissing; // @synthesize headCommitHashMissing=_headCommitHashMissing;
@property(nonatomic, getter=isBaseBranchMissing) BOOL baseBranchMissing; // @synthesize baseBranchMissing=_baseBranchMissing;
@property(nonatomic) long long type; // @synthesize type=_type;
- (id)description;
- (BOOL)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

