//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTPullRequestsCommitsItem.h"

@class GTGitChangesetEntry, GTGitCommit;

@interface GTPullRequestsCommitsChangesetEntryItem : GTPullRequestsCommitsItem
{
    GTGitCommit *_commit;
}

+ (id)identifierWithChangesetEntry:(id)arg1 commit:(id)arg2;
+ (id)changesetEntryItemWithChangesetEntry:(id)arg1 commit:(id)arg2;
- (void).cxx_destruct;
@property(retain, nonatomic) GTGitCommit *commit; // @synthesize commit=_commit;
- (void)updateWithItem:(id)arg1;
@property(readonly, nonatomic) GTGitChangesetEntry *changesetEntry;
- (id)initWithChangesetEntry:(id)arg1 commit:(id)arg2;

@end

