//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class GTPullRequestsCommitsItem, GTPullRequestsCommitsItemController, NSArray, NSError, NSIndexSet;

@protocol GTPullRequestsCommitsItemControllerDelegate <NSObject>

@optional
- (void)pullRequestsCommitsItemControllerDidLoadChangesetItems:(GTPullRequestsCommitsItemController *)arg1;
- (void)pullRequestsCommitsItemController:(GTPullRequestsCommitsItemController *)arg1 didFailReloading:(NSError *)arg2;
- (void)pullRequestsCommitsItemControllerDidReloadItems:(GTPullRequestsCommitsItemController *)arg1;
- (void)pullRequestsCommitsItemControllerDidChangeItems:(GTPullRequestsCommitsItemController *)arg1;
- (void)pullRequestsCommitsItemController:(GTPullRequestsCommitsItemController *)arg1 didUpdateItems:(NSArray *)arg2;
- (void)pullRequestsCommitsItemController:(GTPullRequestsCommitsItemController *)arg1 didMoveItemAtIndex:(unsigned long long)arg2 inParent:(GTPullRequestsCommitsItem *)arg3 toIndex:(unsigned long long)arg4 inParent:(GTPullRequestsCommitsItem *)arg5;
- (void)pullRequestsCommitsItemController:(GTPullRequestsCommitsItemController *)arg1 didInsertItemsAtIndexPaths:(NSIndexSet *)arg2 inParent:(GTPullRequestsCommitsItem *)arg3;
- (void)pullRequestsCommitsItemController:(GTPullRequestsCommitsItemController *)arg1 didDeleteItemsAtIndexPaths:(NSIndexSet *)arg2 inParent:(GTPullRequestsCommitsItem *)arg3;
- (void)pullRequestsCommitsItemControllerWillChangeItems:(GTPullRequestsCommitsItemController *)arg1;
@end

