//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTPullRequestsConversationItem.h"

@class NSDate;

@interface GTPullRequestsConversationCommitGroupItem : GTPullRequestsConversationItem
{
    NSDate *_date;
    unsigned long long _numberOfCommits;
}

+ (id)identifierWithDate:(id)arg1;
+ (id)commitGroupItemWithDate:(id)arg1;
- (void).cxx_destruct;
@property(nonatomic) unsigned long long numberOfCommits; // @synthesize numberOfCommits=_numberOfCommits;
@property(copy, nonatomic) NSDate *date; // @synthesize date=_date;
- (void)updateWithCommitGroupItem:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)itemDate;
- (id)initWithDate:(id)arg1;

@end

