//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTableCellView.h>

@class GTAvatarImageView, GTGPGSignaturePopoverViewController, GTGitRepository, GTPullRequestsConversationCommitItem, NSButton, NSColor, NSFont, NSImage, NSPopover, NSString, NSTextField;
@protocol GTRepositoryPullRequestsActions;

@interface GTPullRequestsConversationCommitCellView : NSTableCellView
{
    GTGitRepository *_repository;
    id <GTRepositoryPullRequestsActions> _target;
    NSTextField *_subjectLabel;
    GTAvatarImageView *_avatarImageView;
    NSButton *_signatureButton;
    NSPopover *_signaturePopover;
    GTGPGSignaturePopoverViewController *_signatureViewController;
}

+ (double)heightForItem:(id)arg1;
+ (id)keyPathsForValuesAffectingStatusIndicatorImage;
+ (id)keyPathsForValuesAffectingCanShowSignature;
+ (id)keyPathsForValuesAffectingShortCommitHash;
+ (id)keyPathsForValuesAffectingSubject;
+ (id)keyPathsForValuesAffectingItem;
- (void).cxx_destruct;
@property(retain, nonatomic) GTGPGSignaturePopoverViewController *signatureViewController; // @synthesize signatureViewController=_signatureViewController;
@property(retain, nonatomic) NSPopover *signaturePopover; // @synthesize signaturePopover=_signaturePopover;
@property(nonatomic) __weak NSButton *signatureButton; // @synthesize signatureButton=_signatureButton;
@property(nonatomic) __weak GTAvatarImageView *avatarImageView; // @synthesize avatarImageView=_avatarImageView;
@property(nonatomic) __weak NSTextField *subjectLabel; // @synthesize subjectLabel=_subjectLabel;
@property(nonatomic) __weak id <GTRepositoryPullRequestsActions> target; // @synthesize target=_target;
@property(retain, nonatomic) GTGitRepository *repository; // @synthesize repository=_repository;
- (void)showSignaturePopover:(id)arg1;
- (void)updateAvatarImageView;
- (void)update;
@property(readonly, nonatomic) BOOL canShowSignature;
@property(readonly, nonatomic) NSImage *statusIndicatorImage;
@property(readonly, nonatomic) NSColor *secondaryTextColor;
@property(readonly, nonatomic) NSColor *textColor;
@property(readonly, nonatomic) NSFont *commitHashFont;
@property(readonly, nonatomic) NSString *shortCommitHash;
@property(readonly, nonatomic) NSString *subject;
@property(readonly, nonatomic) GTPullRequestsConversationCommitItem *item;
- (void)setObjectValue:(id)arg1;
- (void)setBackgroundStyle:(long long)arg1;

@end

