//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "GTQuickActionObjectItemLoaderDelegate-Protocol.h"

@class GTBackgroundSession, GTGitRepository, GTQuickActionConfiguration, GTQuickActionObjectItem, NSArray, NSDate, NSString;
@protocol GTQuickActionItemControllerDelegate;

@interface GTQuickActionItemController : NSObject <GTQuickActionObjectItemLoaderDelegate>
{
    BOOL _loadsActions;
    NSString *_searchString;
    id <GTQuickActionItemControllerDelegate> _delegate;
    GTQuickActionObjectItem *_item;
    GTQuickActionConfiguration *_configuration;
    GTGitRepository *_repository;
    NSArray *_items;
    GTBackgroundSession *_backgroundSession;
    NSDate *_lastUpdateCall;
}

+ (id)keyPathsForValuesAffectingLoading;
- (void).cxx_destruct;
@property(retain, nonatomic) NSDate *lastUpdateCall; // @synthesize lastUpdateCall=_lastUpdateCall;
@property(retain, nonatomic) GTBackgroundSession *backgroundSession; // @synthesize backgroundSession=_backgroundSession;
@property(retain, nonatomic) NSArray *items; // @synthesize items=_items;
@property(nonatomic) BOOL loadsActions; // @synthesize loadsActions=_loadsActions;
@property(retain, nonatomic) GTGitRepository *repository; // @synthesize repository=_repository;
@property(retain, nonatomic) GTQuickActionConfiguration *configuration; // @synthesize configuration=_configuration;
@property(retain, nonatomic) GTQuickActionObjectItem *item; // @synthesize item=_item;
@property(nonatomic) __weak id <GTQuickActionItemControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSString *searchString; // @synthesize searchString=_searchString;
- (BOOL)quickActionObjectHasSubcontent:(id)arg1;
- (void)controllerDidLoadItems:(id)arg1 loader:(id)arg2 task:(id)arg3;
- (void)loadActions;
- (void)loadObjectsForLoaders:(id)arg1;
- (void)waitUntilLoaded;
- (void)reset;
- (void)cancel;
- (void)reloadExpensiveLoadersOnly;
- (void)reload:(BOOL)arg1;
- (void)reload;
@property(readonly, nonatomic, getter=isLoading) BOOL loading;
@property(readonly, nonatomic) NSArray *loaders;
- (id)initWithConfiguration:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

