//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTableCellView.h>

@class NSColor, NSImage, NSLayoutConstraint, NSString;

@interface GTQuickOpenItemCellView : NSTableCellView
{
    BOOL _showHint;
    NSLayoutConstraint *_leadingConstraint;
    NSLayoutConstraint *_trailingConstraint;
    NSColor *_darkBackgroundForegroundColor;
    NSColor *_foregroundColor;
    NSColor *_emphasizedDarkBackgroundForegroundColor;
    NSColor *_emphasizedForegroundColor;
}

+ (id)keyPathsForValuesAffectingShowsActionIcon;
+ (id)keyPathsForValuesAffectingImage;
+ (id)keyPathsForValuesAffectingRepositoryURL;
+ (id)keyPathsForValuesAffectingTitle;
+ (id)keyPathsForValuesAffectingQuickOpenItem;
+ (double)height;
- (void).cxx_destruct;
@property(nonatomic) BOOL showHint; // @synthesize showHint=_showHint;
@property(retain, nonatomic) NSColor *emphasizedForegroundColor; // @synthesize emphasizedForegroundColor=_emphasizedForegroundColor;
@property(retain, nonatomic) NSColor *emphasizedDarkBackgroundForegroundColor; // @synthesize emphasizedDarkBackgroundForegroundColor=_emphasizedDarkBackgroundForegroundColor;
@property(retain, nonatomic) NSColor *foregroundColor; // @synthesize foregroundColor=_foregroundColor;
@property(retain, nonatomic) NSColor *darkBackgroundForegroundColor; // @synthesize darkBackgroundForegroundColor=_darkBackgroundForegroundColor;
@property(nonatomic) __weak NSLayoutConstraint *trailingConstraint; // @synthesize trailingConstraint=_trailingConstraint;
@property(nonatomic) __weak NSLayoutConstraint *leadingConstraint; // @synthesize leadingConstraint=_leadingConstraint;
- (void)awakeFromNib;
@property(readonly, nonatomic) BOOL showsActionIcon;
@property(readonly, nonatomic) NSImage *image;
@property(readonly, nonatomic) NSColor *repositoryURLTextColor;
- (void)setBackgroundStyle:(long long)arg1;
@property(readonly, nonatomic) NSString *repositoryURL;
@property(readonly, nonatomic) NSString *title;
- (id)quickOpenItem;

@end

