//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class GTQuickOpenItemController, NSIndexSet;

@protocol GTQuickOpenItemControllerDelegate <NSObject>
- (void)quickOpenItemControllerDidChangeItems:(GTQuickOpenItemController *)arg1;
- (void)quickOpenItemController:(GTQuickOpenItemController *)arg1 didUpdateItemsAtIndexes:(NSIndexSet *)arg2;
- (void)quickOpenItemController:(GTQuickOpenItemController *)arg1 didMoveItemAtIndex:(unsigned long long)arg2 toIndex:(unsigned long long)arg3;
- (void)quickOpenItemController:(GTQuickOpenItemController *)arg1 didInsertItemsAtIndexes:(NSIndexSet *)arg2;
- (void)quickOpenItemController:(GTQuickOpenItemController *)arg1 didDeleteItemsAtIndexes:(NSIndexSet *)arg2;
- (void)quickOpenItemControllerWillChangeItems:(GTQuickOpenItemController *)arg1;
- (void)quickOpenItemControllerDidReloadItems:(GTQuickOpenItemController *)arg1;
@end

