//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FNAppKit/FNWindowController.h>

#import "GTWindowObserving-Protocol.h"

@class GTGitRepository, GTQuickActionViewController, GTWindowObserver, NSString;
@protocol GTQuickActionObjectActionPerforming;

@interface GTQuickActionWindowController : FNWindowController <GTWindowObserving>
{
    id <GTQuickActionObjectActionPerforming> _actionControllerDelegate;
    GTGitRepository *_repository;
    GTQuickActionViewController *_quickActionViewController;
    GTWindowObserver *_windowObserver;
}

+ (id)sharedController;
- (void).cxx_destruct;
@property(retain, nonatomic) GTWindowObserver *windowObserver; // @synthesize windowObserver=_windowObserver;
@property(retain, nonatomic) GTQuickActionViewController *quickActionViewController; // @synthesize quickActionViewController=_quickActionViewController;
@property(retain, nonatomic) GTGitRepository *repository; // @synthesize repository=_repository;
@property(nonatomic) __weak id <GTQuickActionObjectActionPerforming> actionControllerDelegate; // @synthesize actionControllerDelegate=_actionControllerDelegate;
- (void)showCenteredOnMainScreen:(id)arg1;
- (void)windowDidResignKey:(id)arg1;
- (void)windowDidLoad;
- (void)configureViewController;
- (void)configureWindow;
- (void)configure;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

