//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FNTreeManagerDelegate-Protocol.h"

@class FNTreeManager, GTGitRepository, GTRepositorySidebarItemLoader, GTTagsSortSettings, NSArray, NSError, NSMapTable, NSMutableArray, NSString;
@protocol GTRepositorySidebarItemsControllerDelegate;

@interface GTRepositorySidebarItemsController : NSObject <FNTreeManagerDelegate>
{
    BOOL _groupsRefItems;
    BOOL _reloading;
    BOOL _showsReflog;
    BOOL _initialReload;
    GTGitRepository *_repository;
    id <GTRepositorySidebarItemsControllerDelegate> _delegate;
    NSError *_lastError;
    GTTagsSortSettings *_tagsSortSettings;
    NSMapTable *_identifierToItemMap;
    GTRepositorySidebarItemLoader *_loader;
    FNTreeManager *_treeManager;
    NSMutableArray *_managedSidebarItems;
}

+ (id)controllerWithRepository:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *managedSidebarItems; // @synthesize managedSidebarItems=_managedSidebarItems;
@property(retain, nonatomic) FNTreeManager *treeManager; // @synthesize treeManager=_treeManager;
@property(retain, nonatomic) GTRepositorySidebarItemLoader *loader; // @synthesize loader=_loader;
@property(nonatomic, getter=isInitialReload) BOOL initialReload; // @synthesize initialReload=_initialReload;
@property(retain, nonatomic) NSMapTable *identifierToItemMap; // @synthesize identifierToItemMap=_identifierToItemMap;
@property(nonatomic) BOOL showsReflog; // @synthesize showsReflog=_showsReflog;
@property(retain, nonatomic) GTTagsSortSettings *tagsSortSettings; // @synthesize tagsSortSettings=_tagsSortSettings;
@property(retain, nonatomic) NSError *lastError; // @synthesize lastError=_lastError;
@property(getter=isReloading) BOOL reloading; // @synthesize reloading=_reloading;
@property(nonatomic) BOOL groupsRefItems; // @synthesize groupsRefItems=_groupsRefItems;
@property(nonatomic) __weak id <GTRepositorySidebarItemsControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) GTGitRepository *repository; // @synthesize repository=_repository;
- (void)controllerDidChangeItems;
- (void)controllerDidUpdateItems:(id)arg1 inParent:(id)arg2;
- (void)controllerDidMoveItemAtIndex:(unsigned long long)arg1 inParent:(id)arg2 toIndex:(unsigned long long)arg3 inParent:(id)arg4;
- (void)controllerDidInsertItemsAtIndexPaths:(id)arg1 inParent:(id)arg2;
- (void)controllerDidDeleteItemsAtIndexPaths:(id)arg1 inParent:(id)arg2;
- (void)controllerWillChangeItems;
- (void)controllerDidReloadItems;
- (void)treeManager:(id)arg1 didMoveItemAtIndex:(unsigned long long)arg2 inParent:(id)arg3 toIndex:(unsigned long long)arg4 inParent:(id)arg5;
- (void)treeManager:(id)arg1 willMoveItemAtIndex:(unsigned long long)arg2 inParent:(id)arg3 toIndex:(unsigned long long)arg4 inParent:(id)arg5;
- (void)treeManager:(id)arg1 didInsertItemsAtIndexPaths:(id)arg2 inParent:(id)arg3;
- (void)treeManager:(id)arg1 didDeleteItemsAtIndexPaths:(id)arg2 inParent:(id)arg3;
- (void)treeManager:(id)arg1 willDeleteItemsAtIndexPaths:(id)arg2 inParent:(id)arg3;
- (void)treeManager:(id)arg1 didUpdateItems:(id)arg2;
- (BOOL)treeManager:(id)arg1 updateItem:(id)arg2 withItem:(id)arg3;
- (void)deleteItemsFromIdentifierMap:(id)arg1;
- (void)updateIdentifierMapWithItems:(id)arg1;
- (void)updateParentNode:(id)arg1 withChildItems:(id)arg2;
- (id)submoduleItemForName:(id)arg1;
- (id)remoteItemForName:(id)arg1;
- (id)remoteBranchItemForRefName:(id)arg1;
- (id)tagItemForRefName:(id)arg1;
- (id)branchItemForRefName:(id)arg1;
- (id)repositorySettingsItem;
- (id)headBranchItem;
- (id)itemAtIndexPath:(id)arg1;
- (id)itemForIdentifier:(id)arg1;
- (id)pullRequestsItem;
- (id)refLogItem;
- (id)stashesItem;
- (id)historyItem;
- (id)workingCopyItem;
- (id)submodulesGroupItem;
- (id)originRemoteItem;
- (id)remotesGroupItem;
- (id)tagsGroupItem;
- (id)branchesGroupItem;
- (id)workspaceGroupItem;
- (void)reloadSubmodulesSection;
- (void)reloadRemotesSection;
- (void)reloadTagsSection;
- (void)reloadBranchesSection;
- (void)reloadWorkspaceSection;
- (void)reloadWithOptions:(long long)arg1;
- (void)reload;
@property(readonly, nonatomic) NSArray *sidebarItems;
- (id)makeSubmodulesGroupItem;
- (id)makeRemotesGroupItem;
- (id)makeTagsGroupItem;
- (id)makeBranchesGroupItem;
- (id)makeWorkspaceGroupItem;
- (id)makeDefaultSidebarItems;
- (id)initWithRepository:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

