//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

@class GTGitRepository, NSArray, NSString;

@interface GTRefBadgesView : NSView
{
    double _preferredMaxLayoutWidth;
    double _preferredMaxLayoutHeight;
    NSArray *_refBadgeItems;
    GTGitRepository *_repository;
    double _interitemSpacing;
    NSString *_currentRefBadgeItemsHashValue;
    struct CGRect _currentRefBadgesFrame;
}

+ (id)refBadgesViewWithRefBadgeItems:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *currentRefBadgeItemsHashValue; // @synthesize currentRefBadgeItemsHashValue=_currentRefBadgeItemsHashValue;
@property(nonatomic) struct CGRect currentRefBadgesFrame; // @synthesize currentRefBadgesFrame=_currentRefBadgesFrame;
@property(nonatomic) double interitemSpacing; // @synthesize interitemSpacing=_interitemSpacing;
@property(retain, nonatomic) GTGitRepository *repository; // @synthesize repository=_repository;
@property(retain, nonatomic) NSArray *refBadgeItems; // @synthesize refBadgeItems=_refBadgeItems;
@property(nonatomic) double preferredMaxLayoutHeight; // @synthesize preferredMaxLayoutHeight=_preferredMaxLayoutHeight;
@property(nonatomic) double preferredMaxLayoutWidth; // @synthesize preferredMaxLayoutWidth=_preferredMaxLayoutWidth;
- (id)hitTest:(struct CGPoint)arg1;
- (void)enumerateRefBadgeRectsForLayoutWidth:(double)arg1 layoutHeight:(double)arg2 usingBlock:(CDUnknownBlockType)arg3;
- (void)makeSubviews;
@property(readonly, nonatomic) BOOL needsUpdateSubviews;
- (void)updateSubviews;
- (void)layout;
- (void)viewDidMoveToWindow;
- (double)contentWidth;
- (struct CGSize)intrinsicContentSize;
- (BOOL)needsMoreRefsView;
- (unsigned long long)maxRefBadges;
- (void)setNeedsDisplay:(BOOL)arg1;
- (void)commonInit;
- (id)initWithRefBadgeItems:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

