//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol GTRepositoryHistoryActions <NSObject>

@optional
- (void)rebaseOnto:(id)arg1;
- (void)selectGroupingType:(id)arg1;
- (void)compareFilesToPreviousRevision:(id)arg1;
- (void)showRevisionInHistory:(id)arg1;
- (void)showCommitForRevision:(id)arg1;
- (void)copyFilePathToClipboard:(id)arg1;
- (void)copyCommitInfoToClipboard:(id)arg1;
- (void)copyRevisionsToClipboard:(id)arg1;
- (void)archiveRevision:(id)arg1;
- (void)exportFilesAtRevision:(id)arg1;
- (void)exportRevision:(id)arg1;
- (void)quickSavePatch:(id)arg1;
- (void)savePatch:(id)arg1;
- (void)showFileHistory:(id)arg1;
- (void)blameAtRevision:(id)arg1;
- (void)blame:(id)arg1;
- (void)rawFileAtRevision:(id)arg1;
@end

