//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface GTReleaseChannelManager : NSObject
{
    NSMutableArray *_managedReleaseChannels;
}

+ (id)sharedManager;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *managedReleaseChannels; // @synthesize managedReleaseChannels=_managedReleaseChannels;
- (void)removeReleaseChannel:(id)arg1;
- (id)releaseChannelForName:(id)arg1;
- (void)setReleaseChannels:(id)arg1;
- (void)addReleaseChannel:(id)arg1;
- (id)allReleaseChannelsForAccessTokens:(id)arg1;
- (id)allReleaseChannels;
- (id)init;

@end

