//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTGitActionSenderValidator.h"

@interface GTRemoteActionSenderValidator : GTGitActionSenderValidator
{
}

- (BOOL)validateRevealRemoteInBrowserActionWithItem:(id)arg1;
- (BOOL)validateTrackRemoteBranchActionWithItem:(id)arg1;
- (BOOL)validateRenameRemoteBranchActionWithItem:(id)arg1;
- (BOOL)validateDeleteRemoteBranchesActionWithItem:(id)arg1;
- (BOOL)validateQuickPushToGerritRemoteActionWithItem:(id)arg1;
- (BOOL)validatePushToGerritRemoteActionWithItem:(id)arg1;
- (BOOL)validateQuickPushActionWithItem:(id)arg1;
- (BOOL)validatePushActionWithItem:(id)arg1;
- (BOOL)validateQuickPullActionWithItem:(id)arg1;
- (BOOL)validatePullActionWithItem:(id)arg1;
- (BOOL)validateAddRemoteActionWithItem:(id)arg1;
- (BOOL)validateRenameRemoteActionWithItem:(id)arg1;
- (BOOL)validateDeleteRemotesActionWithItem:(id)arg1;
- (BOOL)validatePruneActionWithItem:(id)arg1;
- (BOOL)validateFetchActionWithItem:(id)arg1;
- (void)registerActions;

@end

