//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FNAppKit/FNViewController.h>

@class GTRemoteActivityItem, NSString, NSTextView;

@interface GTRemoteActivityDetailViewController : FNViewController
{
    BOOL _drawsBackground;
    BOOL _shouldAutoScroll;
    GTRemoteActivityItem *_item;
    NSTextView *_textView;
    NSString *_lastIdentifier;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *lastIdentifier; // @synthesize lastIdentifier=_lastIdentifier;
@property BOOL shouldAutoScroll; // @synthesize shouldAutoScroll=_shouldAutoScroll;
@property(retain, nonatomic) NSTextView *textView; // @synthesize textView=_textView;
@property(nonatomic) BOOL drawsBackground; // @synthesize drawsBackground=_drawsBackground;
@property(retain, nonatomic) GTRemoteActivityItem *item; // @synthesize item=_item;
- (id)contentForRemoteActivityItem:(id)arg1;
- (void)scrollToBottom;
- (void)scrollToTop;
- (void)userDidScroll:(id)arg1;
- (void)update:(BOOL)arg1;
- (void)update;
- (void)viewWillDisappear;
- (void)viewDidAppear;
- (void)viewDidLoad;
- (void)unregisterScrollViewObserver;
- (void)registerScrollViewObserver;
- (void)unregisterObervers;
- (void)registerObervers;
- (void)configureTextView;
@property(readonly, nonatomic) BOOL supportsAutoScroll;

@end

