//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTRepositoryBaseViewController.h"

#import "GTGPGBinaryObserving-Protocol.h"
#import "GTGPGKeyObserving-Protocol.h"
#import "GTGPGKeySelectionMenuControllerDelegate-Protocol.h"
#import "GTGitUserProfilesObserving-Protocol.h"
#import "NSMenuDelegate-Protocol.h"
#import "NSTableViewDelegate-Protocol.h"

@class GTGPGBinaryObserver, GTGPGKeyObserver, GTGPGKeySelectionItemController, GTGPGKeySelectionMenuController, GTGitRepositoryController, GTGitUserProfile, GTGitUserProfilesController, GTGitUserProfilesObserver, GTStateManager, NSArray, NSArrayController, NSString, NSTableView;

@interface GTRepositoryGeneralSettingsViewController : GTRepositoryBaseViewController <GTGitUserProfilesObserving, GTGPGKeyObserving, GTGPGKeySelectionMenuControllerDelegate, NSMenuDelegate, GTGPGBinaryObserving, NSTableViewDelegate>
{
    NSTableView *_tableView;
    NSArrayController *_settingsItemsController;
    NSArray *_settingsItems;
    GTStateManager *_viewState;
    GTGitRepositoryController *_repositoryController;
    GTGitUserProfilesObserver *_userProfilesObserver;
    GTGPGKeyObserver *_gpgKeyObserver;
    GTGPGBinaryObserver *_gpgBinaryObserver;
    NSArray *_userProfiles;
    GTGitUserProfile *_repositoryUserProfile;
    NSArray *_gpgKeys;
    GTGPGKeySelectionItemController *_keySelectionItemController;
    GTGPGKeySelectionMenuController *_keySelectionMenuController;
}

- (void).cxx_destruct;
@property(retain, nonatomic) GTGPGKeySelectionMenuController *keySelectionMenuController; // @synthesize keySelectionMenuController=_keySelectionMenuController;
@property(retain, nonatomic) GTGPGKeySelectionItemController *keySelectionItemController; // @synthesize keySelectionItemController=_keySelectionItemController;
@property(retain, nonatomic) NSArray *gpgKeys; // @synthesize gpgKeys=_gpgKeys;
@property(retain, nonatomic) GTGitUserProfile *repositoryUserProfile; // @synthesize repositoryUserProfile=_repositoryUserProfile;
@property(retain, nonatomic) NSArray *userProfiles; // @synthesize userProfiles=_userProfiles;
@property(retain, nonatomic) GTGPGBinaryObserver *gpgBinaryObserver; // @synthesize gpgBinaryObserver=_gpgBinaryObserver;
@property(retain, nonatomic) GTGPGKeyObserver *gpgKeyObserver; // @synthesize gpgKeyObserver=_gpgKeyObserver;
@property(retain, nonatomic) GTGitUserProfilesObserver *userProfilesObserver; // @synthesize userProfilesObserver=_userProfilesObserver;
@property(nonatomic) __weak GTGitRepositoryController *repositoryController; // @synthesize repositoryController=_repositoryController;
@property(retain, nonatomic) GTStateManager *viewState; // @synthesize viewState=_viewState;
@property(retain, nonatomic) NSArray *settingsItems; // @synthesize settingsItems=_settingsItems;
@property(retain, nonatomic) NSArrayController *settingsItemsController; // @synthesize settingsItemsController=_settingsItemsController;
@property(nonatomic) __weak NSTableView *tableView; // @synthesize tableView=_tableView;
- (BOOL)validateMenuItem:(id)arg1;
- (void)gpgKeySelectionMenuControllerWantsCreateGPGKey:(id)arg1;
- (void)gpgDefaultBinaryDidUpdate:(id)arg1;
- (void)gpgKeysDidUpdate:(id)arg1;
- (void)gitUserProfilesDidUpdate:(id)arg1;
- (void)repositoryDidChange:(id)arg1;
- (void)repositoryDidUpdate:(id)arg1;
- (void)loadGPGKeys;
- (void)loadUserProfiles;
- (void)createGPGKey:(id)arg1;
- (void)manageUserProfiles:(id)arg1;
- (void)updateUserWithSelectedProfile:(id)arg1;
- (void)addUserProfileWithDescription:(id)arg1;
- (void)unsetUser:(id)arg1;
- (void)editUser:(id)arg1;
- (void)editDescription:(id)arg1;
- (BOOL)tableView:(id)arg1 shouldSelectRow:(long long)arg2;
- (id)tableView:(id)arg1 viewForTableColumn:(id)arg2 row:(long long)arg3;
- (id)tableView:(id)arg1 rowViewForRow:(long long)arg2;
- (double)tableView:(id)arg1 heightOfRow:(long long)arg2;
- (BOOL)tableView:(id)arg1 isGroupRow:(long long)arg2;
- (void)gpgKeySelectionDidChange:(id)arg1;
- (void)gpgSigningOptionClicked:(id)arg1;
- (void)updateKeySelectionMenuController;
- (void)updateSettingsItems;
- (BOOL)needsUpdateKeySelectionMenuController;
- (BOOL)needsUpdateSettingsItems;
- (void)updateSelectedUserProfile;
- (BOOL)needsUpdateSelectedUserProfile;
- (void)updateViewState;
- (void)updateIfNeeded;
- (void)update;
- (void)viewWillDisappear;
- (void)viewDidAppear;
- (void)viewDidLoad;
- (id)makeGPGKeySelectionItem;
- (id)makeGPGSigningOptionItem;
- (id)makeGPGGroupItem;
- (id)makeGitUserItemForUser:(id)arg1;
- (id)makeDescriptionItemForRepository:(id)arg1;
- (id)makePathItemForRepository:(id)arg1;
- (id)makeNameItemForRepository:(id)arg1;
- (id)makeGeneralGroupItem;
- (id)makeSettingsItems;
- (void)configureTableView;
- (void)configure;
@property(readonly, nonatomic) BOOL canSelectGPGKey;
@property(readonly, nonatomic) NSArray *actionSenderValidators;
- (BOOL)needsUpdate;
@property(readonly, nonatomic) GTGitUserProfilesController *userProfilesController;
- (id)initWithRepository:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

