//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface GTRepositorySidebarItemHelpers : NSObject
{
}

+ (BOOL)isItemCollectionOfItemTypeSubmodule:(id)arg1;
+ (BOOL)isItemCollectionOfItemTypeRemoteBranch:(id)arg1;
+ (BOOL)isItemCollectionOfItemTypeRemote:(id)arg1;
+ (BOOL)isItemCollectionOfItemTypeTag:(id)arg1;
+ (BOOL)isItemCollectionOfItemTypeBranch:(id)arg1;
+ (BOOL)isItemCollectionOfIdenticalItemType:(id)arg1;

@end

