//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTActionSenderValidator.h"

@class NSArray;

@interface GTRepositoryActionsValidator : GTActionSenderValidator
{
    NSArray *_repositories;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *repositories; // @synthesize repositories=_repositories;
- (BOOL)validateDeleteRepositoryWithItem:(id)arg1;
- (BOOL)validateDeleteRepositoriesWithItem:(id)arg1;
- (BOOL)validateOpenRepositoryWithItem:(id)arg1;
- (void)registerActions;

@end

