//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTTouchBarController.h"

#import "GTHistoryCommitDayItemControllerDelegate-Protocol.h"
#import "NSScrubberDataSource-Protocol.h"
#import "NSScrubberDelegate-Protocol.h"

@class GTHistoryCommitDayItem, GTHistoryCommitDayItemController, NSPopoverTouchBarItem, NSScrubber, NSString, NSTextField;
@protocol GTRepositoryHistoryTouchBarControllerDelegate, GTRepositoryWorkingCopyActions;

@interface GTRepositoryHistoryTouchBarController : GTTouchBarController <NSScrubberDelegate, NSScrubberDataSource, GTHistoryCommitDayItemControllerDelegate>
{
    id <GTRepositoryWorkingCopyActions> _target;
    id <GTRepositoryHistoryTouchBarControllerDelegate> _historyDelegate;
    GTHistoryCommitDayItemController *_historyCommitDayItemController;
    NSPopoverTouchBarItem *_historyPopover;
    NSScrubber *_historyScrubber;
    GTHistoryCommitDayItem *_selectedItem;
    NSTextField *_dateLabel;
}

+ (id)customizationAllowedItemIdentifiers;
+ (id)customizationRequiredItemIdentifiers;
+ (id)defaultItemIdentifiers;
+ (id)customizationIdentifier;
- (void).cxx_destruct;
@property(retain, nonatomic) NSTextField *dateLabel; // @synthesize dateLabel=_dateLabel;
@property(retain, nonatomic) GTHistoryCommitDayItem *selectedItem; // @synthesize selectedItem=_selectedItem;
@property(retain, nonatomic) NSScrubber *historyScrubber; // @synthesize historyScrubber=_historyScrubber;
@property(retain, nonatomic) NSPopoverTouchBarItem *historyPopover; // @synthesize historyPopover=_historyPopover;
@property(nonatomic) __weak GTHistoryCommitDayItemController *historyCommitDayItemController; // @synthesize historyCommitDayItemController=_historyCommitDayItemController;
@property(nonatomic) __weak id <GTRepositoryHistoryTouchBarControllerDelegate> historyDelegate; // @synthesize historyDelegate=_historyDelegate;
@property(nonatomic) __weak id <GTRepositoryWorkingCopyActions> target; // @synthesize target=_target;
- (id)labelForCommitDayItem:(id)arg1;
- (id)historyPopoverItem:(id)arg1;
- (id)commitDayScrubberLabelItem:(id)arg1;
- (id)commitDayScrubberItem:(id)arg1;
- (id)cherryPickCommitsItem:(id)arg1;
- (id)compareCommitsItem:(id)arg1;
- (id)revertCommitsItem:(id)arg1;
- (id)invokeDiffToolItem:(id)arg1;
- (void)restoreSelection;
- (void)storeSelection;
- (void)updateDateLabel;
- (void)update;
- (void)historyCommitDayItemControllerDidReload:(id)arg1;
- (id)scrubber:(id)arg1 viewForItemAtIndex:(long long)arg2;
- (long long)numberOfItemsForScrubber:(id)arg1;
- (void)scrubber:(id)arg1 didSelectItemAtIndex:(long long)arg2;
- (id)touchBar:(id)arg1 makeItemForIdentifier:(id)arg2;
- (void)configureTouchBar;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

