//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FNListItem-Protocol.h"

@class GTGitRemoteActivity, NSString;

@interface GTRemoteActivityItem : NSObject <FNListItem>
{
    GTGitRemoteActivity *_remoteActivity;
}

+ (id)itemWithRemoteActivity:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) GTGitRemoteActivity *remoteActivity; // @synthesize remoteActivity=_remoteActivity;
- (long long)typeFromRemoteActivityStatus:(long long)arg1;
@property(readonly, nonatomic) NSString *identifier;
@property(readonly, nonatomic) long long type;
- (id)initWithRemoteActivity:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

