//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface GTRepositoryDraggingAction : NSObject
{
    BOOL _respondsToMultipleSourceItems;
    BOOL _respondsToAlternateOperation;
    unsigned long long _source;
    unsigned long long _destination;
    unsigned long long _action;
}

+ (id)draggingActionWithSource:(unsigned long long)arg1 destination:(unsigned long long)arg2 action:(unsigned long long)arg3;
@property(nonatomic) unsigned long long action; // @synthesize action=_action;
@property(nonatomic) BOOL respondsToAlternateOperation; // @synthesize respondsToAlternateOperation=_respondsToAlternateOperation;
@property(nonatomic) BOOL respondsToMultipleSourceItems; // @synthesize respondsToMultipleSourceItems=_respondsToMultipleSourceItems;
@property(nonatomic) unsigned long long destination; // @synthesize destination=_destination;
@property(nonatomic) unsigned long long source; // @synthesize source=_source;
- (id)description;

@end

