//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

@class GTRefControlButton, GTRefControlDividerView, GTStateManager, NSColor, NSDictionary, NSFont, NSMenu, NSString;

@interface GTRefControl : NSView
{
    NSString *_refName;
    NSMenu *_refMenu;
    NSString *_refToolTip;
    NSString *_trackingRefName;
    NSMenu *_trackingRefMenu;
    NSString *_trackingRefToolTip;
    GTRefControlButton *_refButton;
    GTRefControlButton *_trackingRefButton;
    GTRefControlDividerView *_dividerView;
    NSDictionary *_defaultButtonTextAttributes;
    NSDictionary *_refButtonTextAttributes;
    NSDictionary *_trackingRefButtonTextAttributes;
    NSFont *_refTextFont;
    NSColor *_refTextColor;
    double _refButtonMinWidth;
    NSFont *_trackingRefTextFont;
    NSColor *_trackingRefTextColor;
    double _trackingRefButtonMinWidth;
    GTStateManager *_viewState;
}

- (void).cxx_destruct;
@property(retain, nonatomic) GTStateManager *viewState; // @synthesize viewState=_viewState;
@property(nonatomic) double trackingRefButtonMinWidth; // @synthesize trackingRefButtonMinWidth=_trackingRefButtonMinWidth;
@property(retain, nonatomic) NSColor *trackingRefTextColor; // @synthesize trackingRefTextColor=_trackingRefTextColor;
@property(retain, nonatomic) NSFont *trackingRefTextFont; // @synthesize trackingRefTextFont=_trackingRefTextFont;
@property(nonatomic) double refButtonMinWidth; // @synthesize refButtonMinWidth=_refButtonMinWidth;
@property(retain, nonatomic) NSColor *refTextColor; // @synthesize refTextColor=_refTextColor;
@property(retain, nonatomic) NSFont *refTextFont; // @synthesize refTextFont=_refTextFont;
@property(retain, nonatomic) NSDictionary *trackingRefButtonTextAttributes; // @synthesize trackingRefButtonTextAttributes=_trackingRefButtonTextAttributes;
@property(retain, nonatomic) NSDictionary *refButtonTextAttributes; // @synthesize refButtonTextAttributes=_refButtonTextAttributes;
@property(retain, nonatomic) NSDictionary *defaultButtonTextAttributes; // @synthesize defaultButtonTextAttributes=_defaultButtonTextAttributes;
@property(retain, nonatomic) GTRefControlDividerView *dividerView; // @synthesize dividerView=_dividerView;
@property(retain, nonatomic) GTRefControlButton *trackingRefButton; // @synthesize trackingRefButton=_trackingRefButton;
@property(retain, nonatomic) GTRefControlButton *refButton; // @synthesize refButton=_refButton;
@property(retain, nonatomic) NSString *trackingRefToolTip; // @synthesize trackingRefToolTip=_trackingRefToolTip;
@property(retain, nonatomic) NSMenu *trackingRefMenu; // @synthesize trackingRefMenu=_trackingRefMenu;
@property(retain, nonatomic) NSString *trackingRefName; // @synthesize trackingRefName=_trackingRefName;
@property(retain, nonatomic) NSString *refToolTip; // @synthesize refToolTip=_refToolTip;
@property(retain, nonatomic) NSMenu *refMenu; // @synthesize refMenu=_refMenu;
@property(retain, nonatomic) NSString *refName; // @synthesize refName=_refName;
- (void)updateDividerView;
- (BOOL)needsUpdateDividerView;
- (void)updateTrackingRefButton;
- (BOOL)needsUpdateTrackingRefButton;
- (void)updateRefButton;
- (BOOL)needsUpdateRefButton;
- (void)updateSubviews;
- (BOOL)needsUpdateSubviews;
- (void)updateViewState;
- (void)update;
- (double)lastBaselineOffsetFromBottom;
- (double)firstBaselineOffsetFromTop;
- (double)baselineOffsetFromBottom;
- (struct CGSize)intrinsicContentSize;
- (void)updateConstraints;
@property(readonly, nonatomic) BOOL showsButtonMenus;
@property(readonly, nonatomic) BOOL showsTrackingRefButton;
@property(readonly, nonatomic) BOOL showsRefButton;
- (id)initWithFrame:(struct CGRect)arg1;

@end

