//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class GTRepositorySidebarItem, GTRepositorySidebarItemsController, NSArray, NSIndexSet;

@protocol GTRepositorySidebarItemsControllerDelegate <NSObject>

@optional
- (void)repositorySidebarItemsControllerDidReloadItems:(GTRepositorySidebarItemsController *)arg1;
- (void)repositorySidebarItemsControllerDidChangeItems:(GTRepositorySidebarItemsController *)arg1;
- (void)repositorySidebarItemsController:(GTRepositorySidebarItemsController *)arg1 didUpdateItems:(NSArray *)arg2 inParent:(GTRepositorySidebarItem *)arg3;
- (void)repositorySidebarItemsController:(GTRepositorySidebarItemsController *)arg1 didMoveItemAtIndex:(unsigned long long)arg2 inParent:(GTRepositorySidebarItem *)arg3 toIndex:(unsigned long long)arg4 inParent:(GTRepositorySidebarItem *)arg5;
- (void)repositorySidebarItemsController:(GTRepositorySidebarItemsController *)arg1 didInsertItemsAtIndexPaths:(NSIndexSet *)arg2 inParent:(GTRepositorySidebarItem *)arg3;
- (void)repositorySidebarItemsController:(GTRepositorySidebarItemsController *)arg1 didDeleteItemsAtIndexPaths:(NSIndexSet *)arg2 inParent:(GTRepositorySidebarItem *)arg3;
- (void)repositorySidebarItemsControllerWillChangeItems:(GTRepositorySidebarItemsController *)arg1;
@end

