//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol GTRepositoryRemoteActions <NSObject>

@optional
- (void)copyRemoteBranchName:(id)arg1;
- (void)editConnectionSettings:(id)arg1;
- (void)revealRemoteInFinder:(id)arg1;
- (void)revealRemoteInBrowser:(id)arg1;
- (void)trackRemoteBranch:(id)arg1;
- (void)renameRemoteBranch:(id)arg1;
- (void)deleteRemoteBranches:(id)arg1;
- (void)pushRevision:(id)arg1;
- (void)pushAllTags:(id)arg1;
- (void)quickPushToGerritRemote:(id)arg1;
- (void)pushToGerritRemote:(id)arg1;
- (void)quickPush:(id)arg1;
- (void)push:(id)arg1;
- (void)quickPullRemoteBranch:(id)arg1;
- (void)pullRemoteBranch:(id)arg1;
- (void)quickPull:(id)arg1;
- (void)pull:(id)arg1;
- (void)pruneRemote:(id)arg1;
- (void)fetchAllRemotes:(id)arg1;
- (void)fetchRemotes:(id)arg1;
- (void)fetchRemote:(id)arg1;
- (void)quickFetch:(id)arg1;
- (void)fetch:(id)arg1;
- (void)renameRemote:(id)arg1;
- (void)deleteRemotes:(id)arg1;
- (void)addSVNRemote:(id)arg1;
- (void)addRemote:(id)arg1;
@end

