//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTSettingsItem.h"

@class GTGitUserProfile, NSArray, NSString;

@interface GTSettingsGitUserItem : GTSettingsItem
{
    BOOL _globalUserName;
    BOOL _globalUserEmailAddress;
    NSString *_userName;
    NSString *_userEmailAddress;
    NSString *_userGPGKey;
    GTGitUserProfile *_selectedUserProfile;
    NSArray *_userProfiles;
    id _actionTarget;
}

+ (id)itemWithTitle:(id)arg1;
- (void).cxx_destruct;
@property(nonatomic) __weak id actionTarget; // @synthesize actionTarget=_actionTarget;
@property(retain, nonatomic) NSArray *userProfiles; // @synthesize userProfiles=_userProfiles;
@property(retain, nonatomic) GTGitUserProfile *selectedUserProfile; // @synthesize selectedUserProfile=_selectedUserProfile;
@property(nonatomic, getter=isGlobalUserEmailAddress) BOOL globalUserEmailAddress; // @synthesize globalUserEmailAddress=_globalUserEmailAddress;
@property(nonatomic, getter=isGlobalUserName) BOOL globalUserName; // @synthesize globalUserName=_globalUserName;
@property(retain, nonatomic) NSString *userGPGKey; // @synthesize userGPGKey=_userGPGKey;
@property(retain, nonatomic) NSString *userEmailAddress; // @synthesize userEmailAddress=_userEmailAddress;
@property(retain, nonatomic) NSString *userName; // @synthesize userName=_userName;
- (id)initWithTitle:(id)arg1;

@end

