//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class GTServiceAccountCredentials, GTServicesAccountController, NSError;

@protocol GTServicesAccountControllerDelegate <NSObject>
- (void)servicesAccountController:(GTServicesAccountController *)arg1 didFailValidatingCredentialsWithError:(NSError *)arg2;
- (void)servicesAccountController:(GTServicesAccountController *)arg1 didValidateCredentials:(GTServiceAccountCredentials *)arg2;
@end

