//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTServiceUpdateRepositoriesOperation.h"

@class NSString, StashAPIClient, StashAPIRequest;

@interface GTServiceUpdateStashRepositoriesOperation : GTServiceUpdateRepositoriesOperation
{
    StashAPIClient *_apiClient;
    StashAPIRequest *_request;
    long long _serviceAccountType;
    NSString *_accountSlug;
    NSString *_organizationSlug;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *organizationSlug; // @synthesize organizationSlug=_organizationSlug;
@property(retain, nonatomic) NSString *accountSlug; // @synthesize accountSlug=_accountSlug;
@property(nonatomic) long long serviceAccountType; // @synthesize serviceAccountType=_serviceAccountType;
@property(retain, nonatomic) StashAPIRequest *request; // @synthesize request=_request;
@property(retain, nonatomic) StashAPIClient *apiClient; // @synthesize apiClient=_apiClient;
- (void)apiClientDidCancelRequest;
- (void)apiClientDidReceiveResponse:(id)arg1;
- (void)startFetchRequestWithPageOffset:(unsigned long long)arg1;
- (void)cancel;
- (void)performFetchRequest;
- (void)operationWillExecute;

@end

