//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString;

@interface GTServicePullRequestCreationInfo : NSObject
{
    NSString *_title;
    NSString *_body;
    NSString *_branchRefName;
    NSString *_baseBranchRefName;
    NSString *_sourceRepositoryName;
    NSString *_sourceRepositoryID;
    NSString *_sourceUserName;
    NSString *_sourceAccountID;
    NSString *_targetRepositoryName;
    NSString *_targetRepositoryID;
    NSString *_targetUserName;
    NSString *_targetAccountID;
    long long _sourceAccountType;
    long long _targetAccountType;
}

- (void).cxx_destruct;
@property(nonatomic) long long targetAccountType; // @synthesize targetAccountType=_targetAccountType;
@property(nonatomic) long long sourceAccountType; // @synthesize sourceAccountType=_sourceAccountType;
@property(retain, nonatomic) NSString *targetAccountID; // @synthesize targetAccountID=_targetAccountID;
@property(retain, nonatomic) NSString *targetUserName; // @synthesize targetUserName=_targetUserName;
@property(retain, nonatomic) NSString *targetRepositoryID; // @synthesize targetRepositoryID=_targetRepositoryID;
@property(retain, nonatomic) NSString *targetRepositoryName; // @synthesize targetRepositoryName=_targetRepositoryName;
@property(retain, nonatomic) NSString *sourceAccountID; // @synthesize sourceAccountID=_sourceAccountID;
@property(retain, nonatomic) NSString *sourceUserName; // @synthesize sourceUserName=_sourceUserName;
@property(retain, nonatomic) NSString *sourceRepositoryID; // @synthesize sourceRepositoryID=_sourceRepositoryID;
@property(retain, nonatomic) NSString *sourceRepositoryName; // @synthesize sourceRepositoryName=_sourceRepositoryName;
@property(retain, nonatomic) NSString *baseBranchRefName; // @synthesize baseBranchRefName=_baseBranchRefName;
@property(retain, nonatomic) NSString *branchRefName; // @synthesize branchRefName=_branchRefName;
@property(retain, nonatomic) NSString *body; // @synthesize body=_body;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(readonly, nonatomic) NSDictionary *dictionaryRepresentation;

@end

