//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTSettingsItem.h"

@class GTServiceRepository;

@interface GTServicesRepositoryItem : GTSettingsItem
{
}

+ (id)itemWithTitle:(id)arg1 serviceRepository:(id)arg2;
@property(readonly, nonatomic) GTServiceRepository *serviceRepository;
- (id)initWithTitle:(id)arg1 type:(id)arg2 serviceRepository:(id)arg3;
- (id)initWithTitle:(id)arg1 serviceRepository:(id)arg2;

@end

