//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class GTServicesSidebarItemsLoader, NSArray, NSCache, NSManagedObjectContext, NSMutableArray;
@protocol GTServicesSidebarItemControllerDelegate;

@interface GTServicesSidebarItemController : NSObject
{
    BOOL _reloading;
    NSManagedObjectContext *_managedObjectContext;
    id <GTServicesSidebarItemControllerDelegate> _delegate;
    NSArray *_items;
    NSMutableArray *_updatedItems;
    GTServicesSidebarItemsLoader *_loader;
    NSCache *_itemsCache;
}

+ (id)controllerWithManagedObjectContext:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) NSCache *itemsCache; // @synthesize itemsCache=_itemsCache;
@property(retain, nonatomic) GTServicesSidebarItemsLoader *loader; // @synthesize loader=_loader;
@property(retain, nonatomic) NSMutableArray *updatedItems; // @synthesize updatedItems=_updatedItems;
@property(getter=isReloading) BOOL reloading; // @synthesize reloading=_reloading;
@property(retain, nonatomic) NSArray *items; // @synthesize items=_items;
@property(nonatomic) __weak id <GTServicesSidebarItemControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSManagedObjectContext *managedObjectContext; // @synthesize managedObjectContext=_managedObjectContext;
- (void)controllerDidChangeItems;
- (void)controllerDidUpdateItems:(id)arg1;
- (void)controllerDidMoveItemAtIndex:(unsigned long long)arg1 inParent:(id)arg2 toIndex:(unsigned long long)arg3 inParent:(id)arg4;
- (void)controllerDidInsertItemsAtIndexPaths:(id)arg1 inParent:(id)arg2;
- (void)controllerDidDeleteItemsAtIndexPaths:(id)arg1 inParent:(id)arg2;
- (void)controllerWillChangeItems;
- (void)controllerDidReloadItems;
- (void)updateParentItem:(id)arg1 withChildItems:(id)arg2;
- (void)enumerateChildItemsOfItem:(id)arg1 usingBlock:(CDUnknownBlockType)arg2;
- (void)enumerateItemsUsingBlock:(CDUnknownBlockType)arg1;
- (void)cacheItemsRecursively:(id)arg1;
- (void)reload;
- (id)itemForIdentifier:(id)arg1;
- (id)initWithManagedObjectContext:(id)arg1;
- (id)init;

@end

