//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMapTable, NSMutableArray;

@interface GTServiceActivityManager : NSObject
{
    NSMutableArray *_allActivities;
    NSMapTable *_activityLookupTable;
}

+ (id)sharedManager;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMapTable *activityLookupTable; // @synthesize activityLookupTable=_activityLookupTable;
@property(retain, nonatomic) NSMutableArray *allActivities; // @synthesize allActivities=_allActivities;
- (void)removeFinishedServiceActivities;
- (void)removeAllServiceActivities;
- (void)removeServiceActivities:(id)arg1;
- (void)updateProgress:(id)arg1 forServiceActivityWithUUID:(id)arg2;
- (void)finishServiceActivityWithServiceActivityInfo:(id)arg1;
- (void)createOrUpdateServiceActivityWithServiceActivityInfo:(id)arg1;
- (id)activitiesWithIdentifiers:(id)arg1;
- (void)addOperationActivity:(id)arg1;
@property(readonly, nonatomic) NSArray *activities;
- (id)init;
- (BOOL)hasActiveUpdatePullRequestsActivityForServiceRepository:(id)arg1;

@end

