//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTAbstractViewStyles.h"

@class NSColor, NSFont, NSImage, NSString;

@interface GTServicesViewStyles : GTAbstractViewStyles
{
    NSColor *_privateRepositoryBackgroundColor;
    NSImage *_privateRepositoryImage;
    NSFont *_accountLabelTextBoldFont;
    NSFont *_accountLabelTextMediumFont;
    NSFont *_repositoryFont;
    NSFont *_forkedFont;
    NSFont *_descriptionFont;
    NSFont *_attributesFont;
    NSColor *_avatarImageDarkBorderColor;
    NSColor *_workingCopyCommitMergeStatusBackgroundColor;
    NSColor *_accountDetailHeaderLabelHeadlineColor;
    NSColor *_settingsRepositoryColor;
    NSColor *_settingsRepositoryFontColor;
    NSColor *_settingsForkedFontColor;
    NSColor *_settingsDescriptionFontColor;
    NSColor *_settingsAttributesFontColor;
    NSColor *_settingsLocalRepositoriesSubtitleColor;
    NSColor *_settingsHeaderAccountAvatarBorderColor;
    double _settingsHeaderAccountAvatarBorderWidth;
    double _settingsHeaderAccountAvatarBorderRadius;
    NSColor *_settingsOrganizationAvatarBorderColor;
    double _settingsOrganizationAvatarBorderWidth;
    double _settingsOrganizationAvatarBorderRadius;
    NSImage *_accountDefaultAvatar;
    NSImage *_accountDefaultAvatarGitHub;
    NSImage *_accountDefaultAvatarBeanstalk;
    NSImage *_accountDefaultAvatarBitBucket;
    NSColor *_accountAvatarBorderColor;
    double _accountAvatarBorderWidth;
    double _accountAvatarBorderRadius;
    NSString *_repositoryDefaultIconName;
    NSString *_repositoryGitHubIconName;
    NSString *_repositoryBeanstalkIconName;
    NSString *_repositoryBitbucketIconName;
    NSImage *_beanstalkRepositoryImage;
    NSImage *_bitbucketRepositoryImage;
    NSImage *_bitbucketServerRepositoryImage;
    NSImage *_gitHubRepositoryImage;
    NSImage *_gitLabRepositoryImage;
    NSImage *_perforceRepositoryImage;
    NSImage *_azureDevOpsRepositoryImage;
    NSImage *_azureDevOpsServerRepositoryImage;
    NSImage *_customRepositoryImage;
    NSImage *_actionBarAddButtonImage;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSImage *actionBarAddButtonImage; // @synthesize actionBarAddButtonImage=_actionBarAddButtonImage;
@property(retain, nonatomic) NSImage *customRepositoryImage; // @synthesize customRepositoryImage=_customRepositoryImage;
@property(retain, nonatomic) NSImage *azureDevOpsServerRepositoryImage; // @synthesize azureDevOpsServerRepositoryImage=_azureDevOpsServerRepositoryImage;
@property(retain, nonatomic) NSImage *azureDevOpsRepositoryImage; // @synthesize azureDevOpsRepositoryImage=_azureDevOpsRepositoryImage;
@property(retain, nonatomic) NSImage *perforceRepositoryImage; // @synthesize perforceRepositoryImage=_perforceRepositoryImage;
@property(retain, nonatomic) NSImage *gitLabRepositoryImage; // @synthesize gitLabRepositoryImage=_gitLabRepositoryImage;
@property(retain, nonatomic) NSImage *gitHubRepositoryImage; // @synthesize gitHubRepositoryImage=_gitHubRepositoryImage;
@property(retain, nonatomic) NSImage *bitbucketServerRepositoryImage; // @synthesize bitbucketServerRepositoryImage=_bitbucketServerRepositoryImage;
@property(retain, nonatomic) NSImage *bitbucketRepositoryImage; // @synthesize bitbucketRepositoryImage=_bitbucketRepositoryImage;
@property(retain, nonatomic) NSImage *beanstalkRepositoryImage; // @synthesize beanstalkRepositoryImage=_beanstalkRepositoryImage;
@property(retain, nonatomic) NSString *repositoryBitbucketIconName; // @synthesize repositoryBitbucketIconName=_repositoryBitbucketIconName;
@property(retain, nonatomic) NSString *repositoryBeanstalkIconName; // @synthesize repositoryBeanstalkIconName=_repositoryBeanstalkIconName;
@property(retain, nonatomic) NSString *repositoryGitHubIconName; // @synthesize repositoryGitHubIconName=_repositoryGitHubIconName;
@property(retain, nonatomic) NSString *repositoryDefaultIconName; // @synthesize repositoryDefaultIconName=_repositoryDefaultIconName;
@property(nonatomic) double accountAvatarBorderRadius; // @synthesize accountAvatarBorderRadius=_accountAvatarBorderRadius;
@property(nonatomic) double accountAvatarBorderWidth; // @synthesize accountAvatarBorderWidth=_accountAvatarBorderWidth;
@property(retain, nonatomic) NSColor *accountAvatarBorderColor; // @synthesize accountAvatarBorderColor=_accountAvatarBorderColor;
@property(retain, nonatomic) NSImage *accountDefaultAvatarBitBucket; // @synthesize accountDefaultAvatarBitBucket=_accountDefaultAvatarBitBucket;
@property(retain, nonatomic) NSImage *accountDefaultAvatarBeanstalk; // @synthesize accountDefaultAvatarBeanstalk=_accountDefaultAvatarBeanstalk;
@property(retain, nonatomic) NSImage *accountDefaultAvatarGitHub; // @synthesize accountDefaultAvatarGitHub=_accountDefaultAvatarGitHub;
@property(retain, nonatomic) NSImage *accountDefaultAvatar; // @synthesize accountDefaultAvatar=_accountDefaultAvatar;
@property(nonatomic) double settingsOrganizationAvatarBorderRadius; // @synthesize settingsOrganizationAvatarBorderRadius=_settingsOrganizationAvatarBorderRadius;
@property(nonatomic) double settingsOrganizationAvatarBorderWidth; // @synthesize settingsOrganizationAvatarBorderWidth=_settingsOrganizationAvatarBorderWidth;
@property(retain, nonatomic) NSColor *settingsOrganizationAvatarBorderColor; // @synthesize settingsOrganizationAvatarBorderColor=_settingsOrganizationAvatarBorderColor;
@property(nonatomic) double settingsHeaderAccountAvatarBorderRadius; // @synthesize settingsHeaderAccountAvatarBorderRadius=_settingsHeaderAccountAvatarBorderRadius;
@property(nonatomic) double settingsHeaderAccountAvatarBorderWidth; // @synthesize settingsHeaderAccountAvatarBorderWidth=_settingsHeaderAccountAvatarBorderWidth;
@property(retain, nonatomic) NSColor *settingsHeaderAccountAvatarBorderColor; // @synthesize settingsHeaderAccountAvatarBorderColor=_settingsHeaderAccountAvatarBorderColor;
@property(retain, nonatomic) NSColor *settingsLocalRepositoriesSubtitleColor; // @synthesize settingsLocalRepositoriesSubtitleColor=_settingsLocalRepositoriesSubtitleColor;
@property(retain, nonatomic) NSColor *settingsAttributesFontColor; // @synthesize settingsAttributesFontColor=_settingsAttributesFontColor;
@property(retain, nonatomic) NSColor *settingsDescriptionFontColor; // @synthesize settingsDescriptionFontColor=_settingsDescriptionFontColor;
@property(retain, nonatomic) NSColor *settingsForkedFontColor; // @synthesize settingsForkedFontColor=_settingsForkedFontColor;
@property(retain, nonatomic) NSColor *settingsRepositoryFontColor; // @synthesize settingsRepositoryFontColor=_settingsRepositoryFontColor;
@property(retain, nonatomic) NSColor *settingsRepositoryColor; // @synthesize settingsRepositoryColor=_settingsRepositoryColor;
@property(retain, nonatomic) NSColor *accountDetailHeaderLabelHeadlineColor; // @synthesize accountDetailHeaderLabelHeadlineColor=_accountDetailHeaderLabelHeadlineColor;
@property(retain, nonatomic) NSColor *workingCopyCommitMergeStatusBackgroundColor; // @synthesize workingCopyCommitMergeStatusBackgroundColor=_workingCopyCommitMergeStatusBackgroundColor;
@property(retain, nonatomic) NSColor *avatarImageDarkBorderColor; // @synthesize avatarImageDarkBorderColor=_avatarImageDarkBorderColor;
@property(retain, nonatomic) NSFont *attributesFont; // @synthesize attributesFont=_attributesFont;
@property(retain, nonatomic) NSFont *descriptionFont; // @synthesize descriptionFont=_descriptionFont;
@property(retain, nonatomic) NSFont *forkedFont; // @synthesize forkedFont=_forkedFont;
@property(retain, nonatomic) NSFont *repositoryFont; // @synthesize repositoryFont=_repositoryFont;
@property(retain, nonatomic) NSFont *accountLabelTextMediumFont; // @synthesize accountLabelTextMediumFont=_accountLabelTextMediumFont;
@property(retain, nonatomic) NSFont *accountLabelTextBoldFont; // @synthesize accountLabelTextBoldFont=_accountLabelTextBoldFont;
@property(retain, nonatomic) NSImage *privateRepositoryImage; // @synthesize privateRepositoryImage=_privateRepositoryImage;
@property(retain, nonatomic) NSColor *privateRepositoryBackgroundColor; // @synthesize privateRepositoryBackgroundColor=_privateRepositoryBackgroundColor;
- (void)loadViewStyles;

@end

