//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FNKeychain;

@interface GTServiceAccountCredentialsStore : NSObject
{
    FNKeychain *_keychain;
}

+ (id)defaultStore;
+ (id)credentialsStoreURLWithServiceHostURL:(id)arg1 username:(id)arg2;
+ (id)tokenIdentifierWithServiceType:(unsigned long long)arg1 apiURLString:(id)arg2 accountName:(id)arg3 username:(id)arg4 type:(id)arg5;
+ (id)refreshTokenAccountForServiceAccountCredentials:(id)arg1;
+ (id)refreshTokenIdentifierForServiceAccountCredentials:(id)arg1;
+ (id)accessTokenAccountForServiceAccountCredentials:(id)arg1;
+ (id)accessTokenIdentifierForServiceAccountCredentials:(id)arg1;
+ (id)privateKeyGenericPasswordAccountNameForPrivateKeyAtURL:(id)arg1;
+ (id)privateKeyGenericPasswordServiceNameForPrivateKeyAtURL:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) FNKeychain *keychain; // @synthesize keychain=_keychain;
- (BOOL)createOrUpdatePassword:(id)arg1 forPrivateKeyAtURL:(id)arg2 error:(id *)arg3;
- (id)refreshTokenForServiceAccountCredentials:(id)arg1 error:(id *)arg2;
- (id)accessTokenForServiceAccountCredentials:(id)arg1 error:(id *)arg2;
- (BOOL)createOrUpdateRefreshTokenForServiceAccountCredentials:(id)arg1 error:(id *)arg2;
- (BOOL)createOrUpdateAccessTokenForServiceAccountCredentials:(id)arg1 error:(id *)arg2;
- (id)gitRemotePasswordForRemoteURL:(id)arg1 serviceAccountCredentials:(id)arg2 error:(id *)arg3;
- (BOOL)createOrUpdateGitRemotePasswordForRemoteURL:(id)arg1 serviceAccountCredentials:(id)arg2 error:(id *)arg3;
- (id)apiPasswordForServiceAccountCredentials:(id)arg1 error:(id *)arg2;
- (BOOL)createOrUpdateAPIPasswordForServiceAccountCredentials:(id)arg1 error:(id *)arg2;
- (id)initWithKeychain:(id)arg1;
- (id)init;

@end

