//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTServiceRepositoryOperation.h"

@class GTUpdateChangeset, NSManagedObjectID;
@protocol GTServicePullRequestAdapter, GTServiceRepositoryAdapter;

@interface GTServiceUpdatePullRequestOperation : GTServiceRepositoryOperation
{
    GTUpdateChangeset *_changeset;
    id <GTServicePullRequestAdapter> _fetchedPullRequest;
    id <GTServiceRepositoryAdapter> _fetchedHeadBranchRepository;
    id <GTServiceRepositoryAdapter> _fetchedBaseBranchRepository;
    NSManagedObjectID *_servicePullRequestID;
}

+ (id)operationWithManagedObjectContext:(id)arg1 serviceRepository:(id)arg2 account:(id)arg3 servicePullRequest:(id)arg4;
- (void).cxx_destruct;
@property(retain, nonatomic) NSManagedObjectID *servicePullRequestID; // @synthesize servicePullRequestID=_servicePullRequestID;
@property(retain, nonatomic) id <GTServiceRepositoryAdapter> fetchedBaseBranchRepository; // @synthesize fetchedBaseBranchRepository=_fetchedBaseBranchRepository;
@property(retain, nonatomic) id <GTServiceRepositoryAdapter> fetchedHeadBranchRepository; // @synthesize fetchedHeadBranchRepository=_fetchedHeadBranchRepository;
@property(retain, nonatomic) id <GTServicePullRequestAdapter> fetchedPullRequest; // @synthesize fetchedPullRequest=_fetchedPullRequest;
@property(retain, nonatomic) GTUpdateChangeset *changeset; // @synthesize changeset=_changeset;
- (id)updateWithFetchedInformation:(id *)arg1;
- (BOOL)validateUpdatePullRequest;
- (void)performFetchRequest;
- (void)execute;
- (void)operationWillExecute;
- (void)addFetchedBaseBranchRepository:(id)arg1;
- (void)addFetchedHeadBranchRepository:(id)arg1;
- (void)addFetchedPullRequest:(id)arg1;
- (id)title;
- (id)initWithManagedObjectContext:(id)arg1 serviceRepository:(id)arg2 account:(id)arg3 servicePullRequest:(id)arg4;

@end

