//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTServiceOperation.h"

@class GTUpdateChangeset, NSArray;

@interface GTServiceDeleteAccountsOperation : GTServiceOperation
{
    NSArray *_serviceAccountIDs;
    GTUpdateChangeset *_changeset;
}

+ (id)operationWithManagedObjectContext:(id)arg1 serviceAccounts:(id)arg2;
- (void).cxx_destruct;
@property(readonly, nonatomic) GTUpdateChangeset *changeset; // @synthesize changeset=_changeset;
@property(retain, nonatomic) NSArray *serviceAccountIDs; // @synthesize serviceAccountIDs=_serviceAccountIDs;
- (void)execute;
- (id)title;
- (id)initWithManagedObjectContext:(id)arg1 serviceAccountIDs:(id)arg2;

@end

