//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSCollectionViewItem.h>

#import "GTServicesUIActions-Protocol.h"

@class GTServiceAccountController, GTServicesServiceItem, GTStateManager, NSButton, NSColor, NSFont, NSImage, NSString;

@interface GTServicesServiceItemViewController : NSCollectionViewItem <GTServicesUIActions>
{
    NSColor *_serviceTitleColor;
    NSFont *_serviceTitleFont;
    NSButton *_button;
    GTStateManager *_viewState;
    GTServiceAccountController *_serviceAccountController;
}

+ (id)keyPathsForValuesAffectingServiceImage;
+ (id)keyPathsForValuesAffectingServiceTitle;
+ (id)keyPathsForValuesAffectingServiceItem;
- (void).cxx_destruct;
@property(retain, nonatomic) GTServiceAccountController *serviceAccountController; // @synthesize serviceAccountController=_serviceAccountController;
@property(retain, nonatomic) GTStateManager *viewState; // @synthesize viewState=_viewState;
@property(nonatomic) __weak NSButton *button; // @synthesize button=_button;
@property(retain, nonatomic) NSFont *serviceTitleFont; // @synthesize serviceTitleFont=_serviceTitleFont;
@property(retain, nonatomic) NSColor *serviceTitleColor; // @synthesize serviceTitleColor=_serviceTitleColor;
- (void)addAzureDevOpsServerAccount:(id)arg1;
- (void)addAzureDevOpsAccount:(id)arg1;
- (void)addGitSwarmAccount:(id)arg1;
- (void)addGitLabCEEEAccount:(id)arg1;
- (void)addGitLabAccount:(id)arg1;
- (void)addStashAccount:(id)arg1;
- (void)addBitbucketAccount:(id)arg1;
- (void)addBeanstalkAccount:(id)arg1;
- (void)addGitHubEnterpriseAccount:(id)arg1;
- (void)addGitHubAccount:(id)arg1;
- (void)updateButtonAction;
- (BOOL)needsUpdateButtonAction;
- (void)updateServiceItemView;
- (BOOL)needsUpdateServiceItemView;
- (void)updateViewState;
- (void)update;
- (void)awakeFromNib;
- (void)setRepresentedObject:(id)arg1;
@property(readonly, nonatomic) NSImage *serviceImage;
@property(readonly, nonatomic) NSString *serviceTitle;
@property(readonly, nonatomic) GTServicesServiceItem *serviceItem;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

