//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTServicePullRequestAction.h"

@class GTGitRemoteBranch, GTGitRemoteManager, GTGitRepository;

@interface GTServiceFetchPullRequestForkDataAction : GTServicePullRequestAction
{
    GTGitRepository *_repository;
    GTGitRemoteManager *_remoteManager;
    GTGitRemoteBranch *_remoteBranch;
}

+ (id)actionWithServicePullRequest:(id)arg1 account:(id)arg2 repository:(id)arg3;
- (void).cxx_destruct;
@property(retain, nonatomic) GTGitRemoteBranch *remoteBranch; // @synthesize remoteBranch=_remoteBranch;
@property(retain, nonatomic) GTGitRemoteManager *remoteManager; // @synthesize remoteManager=_remoteManager;
@property(retain, nonatomic) GTGitRepository *repository; // @synthesize repository=_repository;
- (void)actionDidFinish;
- (void)actionDidFailWithError:(id)arg1;
- (void)main;
- (id)initWithServicePullRequest:(id)arg1 account:(id)arg2 repository:(id)arg3;

@end

