//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTServiceAccountAction.h"

@class GTServicePullRequestManager, GTServiceRepository;

@interface GTServiceRepositoryAction : GTServiceAccountAction
{
    GTServiceRepository *_serviceRepository;
    GTServicePullRequestManager *_servicePullRequestManager;
}

+ (id)actionWithServiceRepository:(id)arg1 account:(id)arg2;
- (void).cxx_destruct;
@property(retain, nonatomic) GTServicePullRequestManager *servicePullRequestManager; // @synthesize servicePullRequestManager=_servicePullRequestManager;
@property(retain, nonatomic) GTServiceRepository *serviceRepository; // @synthesize serviceRepository=_serviceRepository;
- (id)initWithServiceRepository:(id)arg1 account:(id)arg2;

@end

