//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTDialogueViewController.h"

@class GTCompareTool, GTCompareToolController, NSArray, NSMenu, NSPopUpButton;

@interface GTSelectDiffToolDialogueViewController : GTDialogueViewController
{
    NSPopUpButton *_diffToolsPopUpButton;
    NSArray *_diffTools;
    GTCompareTool *_selectedDiffTool;
    NSMenu *_diffToolMenu;
    GTCompareToolController *_compareToolController;
}

+ (id)keyPathsForValuesAffectingValidatesSubmitButton;
- (void).cxx_destruct;
@property(retain, nonatomic) GTCompareToolController *compareToolController; // @synthesize compareToolController=_compareToolController;
@property(nonatomic) __weak NSMenu *diffToolMenu; // @synthesize diffToolMenu=_diffToolMenu;
@property(retain, nonatomic) GTCompareTool *selectedDiffTool; // @synthesize selectedDiffTool=_selectedDiffTool;
@property(retain, nonatomic) NSArray *diffTools; // @synthesize diffTools=_diffTools;
@property(nonatomic) __weak NSPopUpButton *diffToolsPopUpButton; // @synthesize diffToolsPopUpButton=_diffToolsPopUpButton;
- (void)selectDiffTool:(id)arg1;
- (BOOL)validatesSubmitButton;
- (void)menuNeedsUpdate:(id)arg1;
- (void)loadDiffTools;
- (void)viewDidDisappear;
- (void)viewDidAppear;
- (void)viewDidLoad;
- (void)commonInit;

@end

