//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "GTServicesStashAPIControllerDelegate-Protocol.h"

@class GTServiceAccount, GTServiceRepositoryCreationInfo, NSArray, NSString;

@interface GTServicesStashRepositoryController : NSObject <GTServicesStashAPIControllerDelegate>
{
    GTServiceAccount *_serviceAccount;
    GTServiceAccount *_selectedAccount;
    NSString *_repositoryName;
    GTServiceRepositoryCreationInfo *_serviceRepositoryCreationInfo;
    NSArray *_accounts;
    NSArray *_existingRepositories;
}

+ (id)controllerWithServiceAccount:(id)arg1 serviceRepositoryCreationInfo:(id)arg2;
- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *existingRepositories; // @synthesize existingRepositories=_existingRepositories;
@property(retain, nonatomic) NSArray *accounts; // @synthesize accounts=_accounts;
@property(retain, nonatomic) GTServiceRepositoryCreationInfo *serviceRepositoryCreationInfo; // @synthesize serviceRepositoryCreationInfo=_serviceRepositoryCreationInfo;
@property(retain, nonatomic) NSString *repositoryName; // @synthesize repositoryName=_repositoryName;
@property(retain, nonatomic) GTServiceAccount *selectedAccount; // @synthesize selectedAccount=_selectedAccount;
@property(retain, nonatomic) GTServiceAccount *serviceAccount; // @synthesize serviceAccount=_serviceAccount;
- (BOOL)validateStringNotEmpty:(id)arg1;
- (BOOL)validateUniqueRepositoryName:(id)arg1;
- (BOOL)validateStashRepositoryNameFormat:(id)arg1;
- (id)makeValidationErrorWithMessage:(id)arg1;
- (BOOL)validate:(id *)arg1;
@property(readonly, nonatomic) NSString *sanitizedRepositoryName;
- (id)makeAccountsForServiceAccount:(id)arg1;
- (id)initWithServiceAccount:(id)arg1 serviceRepositoryCreationInfo:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

