//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSNotification;

@protocol GTServicesObserving <NSObject>

@optional
- (void)serviceActivitiesDidUpdate:(NSNotification *)arg1;
- (void)serviceAccountDidAuthorize:(NSNotification *)arg1;
- (void)servicePullRequestCommentsDidUpdate:(NSNotification *)arg1;
- (void)servicePullRequestsDidUpdate:(NSNotification *)arg1;
- (void)serviceRepositoriesDidUpdate:(NSNotification *)arg1;
- (void)serviceAccountsDidUpdate:(NSNotification *)arg1;
- (void)servicesDidUpdate:(NSNotification *)arg1;
@end

