//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTActionSenderValidator.h"

@class NSArray;

@interface GTServiceAccountActionSenderValidator : GTActionSenderValidator
{
    NSArray *_serviceAccounts;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *serviceAccounts; // @synthesize serviceAccounts=_serviceAccounts;
- (id)serviceAccountsForItem:(id)arg1;
- (BOOL)validateCreateServiceRepositoryActionWithItem:(id)arg1;
- (BOOL)validateReloadServiceAccountActionWithItem:(id)arg1;
- (BOOL)validateRemoveServiceAccountsActionWithItem:(id)arg1;
- (BOOL)validateRemoveServiceAccountActionWithItem:(id)arg1;
- (BOOL)validateEditServiceAccountActionWithItem:(id)arg1;
- (BOOL)validateOpenServiceAccountInBrowserActionWithItem:(id)arg1;
- (void)registerActions;

@end

