//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "GTServicesGitLabAPIControllerDelegate-Protocol.h"

@class GTServiceAccount, GTServiceAccountCredentials, GTServiceAccountCredentialsStore, GTServicesGitLabAPIController, GitLabAPICredentials, NSArray, NSData, NSManagedObjectContext, NSNumber, NSString;
@protocol GTServicesGitSwarmAccountControllerDelegate;

@interface GTServicesGitSwarmAccountController : NSObject <GTServicesGitLabAPIControllerDelegate>
{
    BOOL _trustsServer;
    id <GTServicesGitSwarmAccountControllerDelegate> _delegate;
    GTServiceAccount *_serviceAccount;
    NSString *_host;
    NSString *_username;
    NSString *_password;
    NSString *_privateToken;
    NSNumber *_authenticationMethodValue;
    NSArray *_existingGitSwarmAccounts;
    NSString *_accessToken;
    GTServiceAccountCredentials *_originalServiceAccountCredentials;
    GTServiceAccountCredentialsStore *_credentialsStore;
    GTServicesGitLabAPIController *_gitLabAPIController;
    NSData *_serverTrustExceptionCookie;
    NSManagedObjectContext *_managedObjectContext;
    unsigned long long _serverAPIVersion;
}

+ (id)accountControllerWithServiceAccount:(id)arg1;
- (void).cxx_destruct;
@property(nonatomic) unsigned long long serverAPIVersion; // @synthesize serverAPIVersion=_serverAPIVersion;
@property(retain, nonatomic) NSManagedObjectContext *managedObjectContext; // @synthesize managedObjectContext=_managedObjectContext;
@property(retain, nonatomic) NSData *serverTrustExceptionCookie; // @synthesize serverTrustExceptionCookie=_serverTrustExceptionCookie;
@property(retain, nonatomic) GTServicesGitLabAPIController *gitLabAPIController; // @synthesize gitLabAPIController=_gitLabAPIController;
@property(retain, nonatomic) GTServiceAccountCredentialsStore *credentialsStore; // @synthesize credentialsStore=_credentialsStore;
@property(retain, nonatomic) GTServiceAccountCredentials *originalServiceAccountCredentials; // @synthesize originalServiceAccountCredentials=_originalServiceAccountCredentials;
@property(retain, nonatomic) NSString *accessToken; // @synthesize accessToken=_accessToken;
@property(retain, nonatomic) NSArray *existingGitSwarmAccounts; // @synthesize existingGitSwarmAccounts=_existingGitSwarmAccounts;
@property(nonatomic) BOOL trustsServer; // @synthesize trustsServer=_trustsServer;
@property(retain, nonatomic) NSNumber *authenticationMethodValue; // @synthesize authenticationMethodValue=_authenticationMethodValue;
@property(retain, nonatomic) NSString *privateToken; // @synthesize privateToken=_privateToken;
@property(retain, nonatomic) NSString *password; // @synthesize password=_password;
@property(retain, nonatomic) NSString *username; // @synthesize username=_username;
@property(retain, nonatomic) NSString *host; // @synthesize host=_host;
@property(readonly, nonatomic) GTServiceAccount *serviceAccount; // @synthesize serviceAccount=_serviceAccount;
@property(nonatomic) __weak id <GTServicesGitSwarmAccountControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)gitLabAPIController:(id)arg1 didFailWithError:(id)arg2;
- (void)gitLabAPIControllerDidValidateCredentials:(id)arg1;
- (void)cancel;
- (void)validateCredentials;
- (BOOL)validateStringNotEmpty:(id)arg1;
- (BOOL)validateUniqueServiceHost:(id)arg1 username:(id)arg2;
- (BOOL)validateGitLabUsernameFormat:(id)arg1;
- (BOOL)validateHostFormat:(id)arg1;
- (id)makeValidationErrorWithMessage:(id)arg1;
- (BOOL)validate:(id *)arg1;
@property(readonly, nonatomic) GTServiceAccountCredentials *serviceAccountCredentials;
@property(readonly, nonatomic) GitLabAPICredentials *apiCredentials;
@property(readonly, nonatomic) NSString *sanitizedUsername;
- (id)sanitizedHost;
- (id)normalizedAPIURL;
@property(readonly, nonatomic) long long authenticationMethod;
@property(readonly, nonatomic) NSArray *authenticationMethods;
- (void)initOriginalServiceAccountCredentialsWithServiceAccount:(id)arg1;
- (id)initWithServiceAccount:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

