//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class GTServicesGitHubEnterpriseAccountController, NSError, NSString;

@protocol GTServicesGitHubEnterpriseAccountControllerDelegate <NSObject>

@optional
- (void)gitHubEnterpriseAccountController:(GTServicesGitHubEnterpriseAccountController *)arg1 didFailWithError:(NSError *)arg2;
- (void)gitHubEnterpriseAccountController:(GTServicesGitHubEnterpriseAccountController *)arg1 needsAuthenticationCodeWithDeliveryType:(NSString *)arg2;
- (void)gitHubEnterpriseAccountControllerNeedsReauthorization:(GTServicesGitHubEnterpriseAccountController *)arg1;
- (void)gitHubEnterpriseAccountControllerDidAuthorize:(GTServicesGitHubEnterpriseAccountController *)arg1;
- (void)gitHubEnterpriseAccountControllerDidValidateCredentials:(GTServicesGitHubEnterpriseAccountController *)arg1;
@end

