//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class GitHubAPIClient, GitHubAPIRequest, GitHubAPIResponse;
@protocol GTServicesGitHubAPIControllerDelegate;

@interface GTServicesGitHubAPIController : NSObject
{
    id <GTServicesGitHubAPIControllerDelegate> _delegate;
    GitHubAPIResponse *_lastResponse;
    GitHubAPIClient *_apiClient;
    GitHubAPIRequest *_request;
}

+ (id)keyPathsForValuesAffectingLoading;
- (void).cxx_destruct;
@property(retain, nonatomic) GitHubAPIRequest *request; // @synthesize request=_request;
@property(retain, nonatomic) GitHubAPIClient *apiClient; // @synthesize apiClient=_apiClient;
@property(retain, nonatomic) GitHubAPIResponse *lastResponse; // @synthesize lastResponse=_lastResponse;
@property(nonatomic) __weak id <GTServicesGitHubAPIControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)controllerDidCancelRequest;
- (void)controllerDidFailWithError:(id)arg1;
- (void)controllerDidReceiveDeleteAuthorizationAPIResponse:(id)arg1;
- (void)controllerDidReceiveGetOrCreateAuthorizationAPIResponse:(id)arg1;
- (void)controllerDidReceiveFetchAllAuthorizationsAPIResponse:(id)arg1;
- (void)controllerDidReceiveValidateCredentialsAPIResponse:(id)arg1;
- (void)cancel;
- (void)deleteAuthorization:(id)arg1 credentials:(id)arg2;
- (void)getOrCreateAuthorizationWithCredentials:(id)arg1;
- (void)fetchAllAuthorizationsWithCredentials:(id)arg1;
- (void)validateCredentials:(id)arg1;
@property(readonly, nonatomic, getter=isLoading) BOOL loading;
- (id)authorizationForAPICredentials:(id)arg1;

@end

