//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString;

@interface GTServiceRepositoryCreationInfo : NSObject
{
    NSString *_name;
    NSString *_title;
    NSString *_userDescription;
    unsigned long long _accessType;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned long long accessType; // @synthesize accessType=_accessType;
@property(retain, nonatomic) NSString *userDescription; // @synthesize userDescription=_userDescription;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(readonly, nonatomic, getter=isPublic) BOOL public;
@property(readonly, nonatomic, getter=isPrivate) BOOL private;
@property(readonly, nonatomic) NSDictionary *dictionaryRepresentation;

@end

