//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTDialogueViewController.h"

#import "GTServicesAccountControllerDelegate-Protocol.h"
#import "GTServicesAuthorizationControllerDelegate-Protocol.h"

@class GTDialogueWindowController, GTServiceAccount, GTServiceAccountCredentials, GTServiceAuthenticationMethodsController, GTServicesAccountController, GTServicesAuthorizationController, GTStateManager, NSAlert, NSColor, NSPopUpButton, NSString;

@interface GTServicesGitHubAccountViewController : GTDialogueViewController <GTServicesAccountControllerDelegate, GTServicesAuthorizationControllerDelegate>
{
    BOOL _validating;
    GTServiceAccount *_serviceAccount;
    GTServiceAccountCredentials *_serviceAccountCredentials;
    NSPopUpButton *_authenticationMethodsPopUpButton;
    GTServicesAccountController *_accountController;
    GTServicesAuthorizationController *_authorizationController;
    GTServiceAuthenticationMethodsController *_authenticationMethodsController;
    GTDialogueWindowController *_dialogueWindowController;
    GTStateManager *_viewState;
    NSAlert *_alert;
}

+ (id)keyPathsForValuesAffectingValidatesSubmitButton;
+ (id)keyPathsForValuesAffectingNeedsPasswordField;
+ (id)keyPathsForValuesAffectingPasswordLabelText;
+ (id)keyPathsForValuesAffectingPasswordLabelTextColor;
- (void).cxx_destruct;
@property(retain, nonatomic) NSAlert *alert; // @synthesize alert=_alert;
@property(retain, nonatomic) GTStateManager *viewState; // @synthesize viewState=_viewState;
@property(retain, nonatomic) GTDialogueWindowController *dialogueWindowController; // @synthesize dialogueWindowController=_dialogueWindowController;
@property(nonatomic, getter=isValidating) BOOL validating; // @synthesize validating=_validating;
@property(retain, nonatomic) GTServiceAuthenticationMethodsController *authenticationMethodsController; // @synthesize authenticationMethodsController=_authenticationMethodsController;
@property(retain, nonatomic) GTServicesAuthorizationController *authorizationController; // @synthesize authorizationController=_authorizationController;
@property(retain, nonatomic) GTServicesAccountController *accountController; // @synthesize accountController=_accountController;
@property(nonatomic) __weak NSPopUpButton *authenticationMethodsPopUpButton; // @synthesize authenticationMethodsPopUpButton=_authenticationMethodsPopUpButton;
@property(retain, nonatomic) GTServiceAccountCredentials *serviceAccountCredentials; // @synthesize serviceAccountCredentials=_serviceAccountCredentials;
@property(retain, nonatomic) GTServiceAccount *serviceAccount; // @synthesize serviceAccount=_serviceAccount;
- (void)servicesAuthorizationController:(id)arg1 didFailCreatingAuthorizationWithError:(id)arg2;
- (void)servicesAuthorizationController:(id)arg1 didCreateAuthorization:(id)arg2;
- (void)servicesAccountController:(id)arg1 didFailValidatingCredentialsWithError:(id)arg2;
- (void)servicesAccountController:(id)arg1 didValidateCredentials:(id)arg2;
- (void)authorize:(id)arg1;
- (void)validateCredentials:(id)arg1;
- (BOOL)submitDialogue:(id *)arg1;
- (BOOL)cancelDialogue:(id *)arg1;
- (void)authenticationMethodSelectionDidChange:(id)arg1;
- (BOOL)validatesSubmitButton;
- (void)updateSubmitButtonTitle;
- (void)updateTitle;
- (void)updateAuthenticationMethodsMenuController;
- (void)updateViewState;
- (void)update;
- (BOOL)needsUpdate;
- (void)viewWillDisappear;
- (void)viewDidAppear;
- (void)viewWillAppear;
- (void)viewDidLoad;
- (void)configureAuthenticationMethodsMenuController;
@property(readonly, nonatomic) NSString *passwordLabelText;
@property(readonly, nonatomic) NSColor *passwordLabelTextColor;
@property(readonly, nonatomic) BOOL needsPasswordField;
@property(readonly, nonatomic) BOOL needsValidation;
- (void)dealloc;
- (void)commonInit;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

