//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTServiceController.h"

@class GTDialogueWindowController, GTServiceAccountManager, NSMutableSet, NSWindow;

@interface GTServiceAccountController : GTServiceController
{
    NSWindow *_window;
    GTDialogueWindowController *_dialogueWindowController;
    GTServiceAccountManager *_serviceAccountManager;
    NSMutableSet *_accountIdentifiersForReloadOrganizations;
}

+ (id)sharedController;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableSet *accountIdentifiersForReloadOrganizations; // @synthesize accountIdentifiersForReloadOrganizations=_accountIdentifiersForReloadOrganizations;
@property(retain, nonatomic) GTServiceAccountManager *serviceAccountManager; // @synthesize serviceAccountManager=_serviceAccountManager;
@property(retain, nonatomic) GTDialogueWindowController *dialogueWindowController; // @synthesize dialogueWindowController=_dialogueWindowController;
@property(nonatomic) __weak NSWindow *window; // @synthesize window=_window;
- (id)windowForSender:(id)arg1;
- (void)controllerDidPerformServiceAction:(id)arg1;
- (void)controllerDidPerformReloadOrganizationsAction:(id)arg1;
- (void)controllerDidPerformReloadAccountAction:(id)arg1;
- (void)controllerDidPerformUpdateAccountAction:(id)arg1;
- (void)controllerDidPerformCreateAccountAction:(id)arg1;
- (void)reloadOrganizationsForServiceAccount:(id)arg1 forceUpdate:(BOOL)arg2;
- (void)reloadOrganizationsForServiceAccount:(id)arg1;
- (void)reloadAllServiceAccountOrganizationsWithForceUpdate:(BOOL)arg1;
- (void)reloadAllServiceAccountOrganizations;
- (void)reloadServiceAccounts:(id)arg1 forceUpdate:(BOOL)arg2;
- (void)reloadServiceAccounts:(id)arg1;
- (void)reloadServiceAccount:(id)arg1 forceUpdate:(BOOL)arg2;
- (void)reloadServiceAccount:(id)arg1;
- (void)reloadAllServiceAccountsWithForceUpdate:(BOOL)arg1;
- (void)reloadAllUninitializedServiceAccounts;
- (void)reloadAllServiceAccounts;
- (void)performRemoveServiceAccountsActionWithServiceAccounts:(id)arg1;
- (void)removeServiceAccounts:(id)arg1;
- (void)removeServiceAccount:(id)arg1;
- (void)openServiceAccountInBrowser:(id)arg1;
- (void)setPrivateSSHKey:(id)arg1 forServiceAccount:(id)arg2;
- (void)unsetPrivateSSHKeyForServiceAccount:(id)arg1;
- (void)editPrivateSSHKeyForServiceAccount:(id)arg1;
- (void)setPrivateSSHKeyForServiceAccount:(id)arg1;
- (void)setDefaultCloneProtocol:(unsigned long long)arg1 forServiceAccount:(id)arg2;
- (void)updateServiceAccount:(id)arg1 withServiceAccountCredentials:(id)arg2;
- (void)editCustomServiceAccount:(id)arg1;
- (void)editAzureDevOpsServerServiceAccount:(id)arg1;
- (void)editAzureDevOpsServiceAccount:(id)arg1;
- (void)editStashServiceAccount:(id)arg1;
- (void)editGitSwarmServiceAccount:(id)arg1;
- (void)editGitLabCEEEServiceAccount:(id)arg1;
- (void)editGitLabServiceAccount:(id)arg1;
- (void)editBitbucketServiceAccount:(id)arg1;
- (void)editBeanstalkServiceAccount:(id)arg1;
- (void)editGitHubEnterpriseServiceAccount:(id)arg1;
- (void)editGitHubServiceAccount:(id)arg1;
- (void)editServiceAccount:(id)arg1;
- (void)createServiceAccountWithServiceAccountCredentials:(id)arg1;
- (void)addCustomServiceAccount:(id)arg1 remoteURL:(id)arg2;
- (void)addCustomServiceAccount:(id)arg1;
- (void)addAzureDevOpsServerServiceAccount:(id)arg1;
- (void)addAzureDevOpsServiceAccount:(id)arg1;
- (void)addStashServiceAccount:(id)arg1;
- (void)addGitSwarmServiceAccount:(id)arg1;
- (void)addGitLabCEEEServiceAccount:(id)arg1;
- (void)addGitLabServiceAccount:(id)arg1;
- (void)addBitbucketServiceAccount:(id)arg1;
- (void)addBeanstalkServiceAccount:(id)arg1;
- (void)addGitHubEnterpriseServiceAccount:(id)arg1;
- (void)addGitHubServiceAccount:(id)arg1;
- (void)addServiceAccountForServiceType:(unsigned long long)arg1;

@end

