//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTActionSenderValidator.h"

@class GTSearchController;

@interface GTSearchActionSenderValidator : GTActionSenderValidator
{
    GTSearchController *_searchController;
}

- (void).cxx_destruct;
@property(nonatomic) __weak GTSearchController *searchController; // @synthesize searchController=_searchController;
- (BOOL)validateSearchInScope:(id)arg1;
- (void)registerActions;

@end

