//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTServiceFetchRepositoryOperation.h"

@class GTUpdateChangeset, GitLabAPIClient, NSManagedObjectID;

@interface GTServiceFetchGitLabProjectOperation : GTServiceFetchRepositoryOperation
{
    BOOL _loading;
    NSManagedObjectID *_serviceID;
    GTUpdateChangeset *_changeset;
    GitLabAPIClient *_apiClient;
}

- (void).cxx_destruct;
@property(nonatomic, getter=isLoading) BOOL loading; // @synthesize loading=_loading;
@property(retain, nonatomic) GitLabAPIClient *apiClient; // @synthesize apiClient=_apiClient;
@property(retain, nonatomic) GTUpdateChangeset *changeset; // @synthesize changeset=_changeset;
@property(retain, nonatomic) NSManagedObjectID *serviceID; // @synthesize serviceID=_serviceID;
- (id)credentialsForServiceAccount:(id)arg1;
- (void)waitUntilLoaded;
- (id)parentPathForGroupPath:(id)arg1;
- (void)operationDidFetchGroup:(id)arg1;
- (void)operationDidFetchRepository:(id)arg1;
- (void)performFetchGroupWithID:(unsigned long long)arg1;
- (void)performFetchRequest;
- (id)initWithManagedObjectContext:(id)arg1 serviceRepositoryFetchInfo:(id)arg2 serviceID:(id)arg3;

@end

