//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreData/NSManagedObject.h>

@class GTServiceAccount, GTServicePullRequest, GTServiceRepository, NSDate, NSDictionary, NSString;

@interface GTServicePullRequestBranch : NSManagedObject
{
}

+ (id)servicePullRequestBranchWithID:(id)arg1 managedObjectContext:(id)arg2 error:(id *)arg3;
+ (id)servicePullRequestBranchWithRefName:(id)arg1 commitHash:(id)arg2 user:(id)arg3 repository:(id)arg4 managedObjectContext:(id)arg5;
+ (id)makeForkedPullRequestBranchNameWithServiceRepository:(id)arg1 refName:(id)arg2;
- (BOOL)statisticsAvailableForPullRequest:(id)arg1;
- (void)resetStatsIfNecessary;
- (void)updateLastModifiedDate;
- (void)willSave;
- (void)awakeFromInsert;
- (id)localBranchThatTracksCorrectRemoteBranchInRepository:(id)arg1;
- (id)remoteBranchInRepository:(id)arg1;
- (id)commitHashInRepository:(id)arg1;
- (id)matchingRefNameInRepository:(id)arg1;
@property(readonly, nonatomic) NSDictionary *dictionaryRepresentation;

// Remaining properties
@property(retain, nonatomic) GTServicePullRequest *basePullRequest; // @dynamic basePullRequest;
@property(retain, nonatomic) NSString *commitHash; // @dynamic commitHash;
@property(readonly, nonatomic) NSDate *creationDate; // @dynamic creationDate;
@property(retain, nonatomic) GTServicePullRequest *headPullRequest; // @dynamic headPullRequest;
@property(readonly, nonatomic) NSDate *lastModifiedDate; // @dynamic lastModifiedDate;
@property(retain, nonatomic) NSString *refName; // @dynamic refName;
@property(retain, nonatomic) GTServiceRepository *repository; // @dynamic repository;
@property(retain, nonatomic) GTServiceAccount *user; // @dynamic user;
@property(readonly, nonatomic) NSString *uuid; // @dynamic uuid;

@end

