//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTDialogueViewController.h"

@class GTGitRepository, GTServiceAccount, GTServiceAccountsMenuController, GTServicePullRequest, GTServicePullRequestBaseBranchMenuController, GTServicePullRequestBranchMenuController, GTServicePullRequestCreationInfo, GTServicePullRequestRepositoryMenuController, GTServicePullRequestUpdateInfo, GTServiceRepository, GTServicesPullRequestController, GTStateManager, NSPopUpButton, NSTextField;

@interface GTServicesPullRequestViewController : GTDialogueViewController
{
    GTGitRepository *_repository;
    GTServiceRepository *_serviceRepository;
    GTServicePullRequest *_servicePullRequest;
    GTServicesPullRequestController *_pullRequestController;
    GTStateManager *_viewState;
    NSTextField *_subjectTextField;
    NSPopUpButton *_serviceAccountPopUpButton;
    NSPopUpButton *_serviceRepositoryPopUpButton;
    NSPopUpButton *_headBranchPopUpButton;
    NSPopUpButton *_baseBranchPopUpButton;
    GTServiceAccountsMenuController *_serviceAccountMenuController;
    GTServicePullRequestRepositoryMenuController *_serviceRepositoryMenuController;
    GTServicePullRequestBranchMenuController *_headBranchMenuController;
    GTServicePullRequestBaseBranchMenuController *_baseBranchMenuController;
}

+ (id)keyPathsForValuesAffectingValidatesSubmitButton;
- (void).cxx_destruct;
@property(retain, nonatomic) GTServicePullRequestBaseBranchMenuController *baseBranchMenuController; // @synthesize baseBranchMenuController=_baseBranchMenuController;
@property(retain, nonatomic) GTServicePullRequestBranchMenuController *headBranchMenuController; // @synthesize headBranchMenuController=_headBranchMenuController;
@property(retain, nonatomic) GTServicePullRequestRepositoryMenuController *serviceRepositoryMenuController; // @synthesize serviceRepositoryMenuController=_serviceRepositoryMenuController;
@property(retain, nonatomic) GTServiceAccountsMenuController *serviceAccountMenuController; // @synthesize serviceAccountMenuController=_serviceAccountMenuController;
@property(nonatomic) __weak NSPopUpButton *baseBranchPopUpButton; // @synthesize baseBranchPopUpButton=_baseBranchPopUpButton;
@property(nonatomic) __weak NSPopUpButton *headBranchPopUpButton; // @synthesize headBranchPopUpButton=_headBranchPopUpButton;
@property(nonatomic) __weak NSPopUpButton *serviceRepositoryPopUpButton; // @synthesize serviceRepositoryPopUpButton=_serviceRepositoryPopUpButton;
@property(nonatomic) __weak NSPopUpButton *serviceAccountPopUpButton; // @synthesize serviceAccountPopUpButton=_serviceAccountPopUpButton;
@property(nonatomic) __weak NSTextField *subjectTextField; // @synthesize subjectTextField=_subjectTextField;
@property(retain, nonatomic) GTStateManager *viewState; // @synthesize viewState=_viewState;
@property(retain, nonatomic) GTServicesPullRequestController *pullRequestController; // @synthesize pullRequestController=_pullRequestController;
@property(retain, nonatomic) GTServicePullRequest *servicePullRequest; // @synthesize servicePullRequest=_servicePullRequest;
@property(retain, nonatomic) GTServiceRepository *serviceRepository; // @synthesize serviceRepository=_serviceRepository;
@property(retain, nonatomic) GTGitRepository *repository; // @synthesize repository=_repository;
- (BOOL)validatesSubmitButton;
- (void)updateTitleAndText;
- (void)updateBaseBranchMenu;
- (void)updateBranchMenu;
- (void)updateServiceRepositoryMenu;
- (void)updateServiceAccountMenu;
- (void)updateViewComponents;
- (void)updateViewState;
- (void)update;
- (void)headBranchSelectionDidChange:(id)arg1;
- (void)baseBranchSelectionDidChange:(id)arg1;
- (void)serviceRepositorySelectionDidChange:(id)arg1;
- (void)serviceAccountSelectionDidChange:(id)arg1;
- (void)viewDidDisappear;
- (void)viewWillDisappear;
- (void)viewDidAppear;
- (void)viewWillAppear;
- (void)viewDidLoad;
- (void)configureWithRepository:(id)arg1 servicePullRequest:(id)arg2 pullRequestUpdateInfo:(id)arg3;
- (void)configureWithRepository:(id)arg1 serviceRepository:(id)arg2 servicePullRequestInfo:(id)arg3;
- (void)configureWithRepository:(id)arg1 serviceRepository:(id)arg2;
@property(readonly, nonatomic, getter=isEditing) BOOL editing;
@property(readonly, nonatomic) GTServicePullRequestUpdateInfo *servicePullRequestUpdateInfo;
@property(readonly, nonatomic) GTServicePullRequestCreationInfo *servicePullRequestCreationInfo;
@property(readonly, nonatomic) GTServiceAccount *serviceAccount;
- (void)commonInit;

@end

