//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTDialogueViewController.h"

@class GTServicePullRequest, GTServicePullRequestMergeTypeMenuController, NSButton, NSPopUpButton;

@interface GTServicePullRequestMergeViewController : GTDialogueViewController
{
    BOOL _mergeTypePopupEnabled;
    GTServicePullRequest *_pullRequest;
    NSPopUpButton *_mergeTypePopUpButton;
    NSButton *_removeBranchAfterMergeCheckBox;
    GTServicePullRequestMergeTypeMenuController *_mergeTypeMenuController;
}

- (void).cxx_destruct;
@property(nonatomic) BOOL mergeTypePopupEnabled; // @synthesize mergeTypePopupEnabled=_mergeTypePopupEnabled;
@property(nonatomic) __weak GTServicePullRequestMergeTypeMenuController *mergeTypeMenuController; // @synthesize mergeTypeMenuController=_mergeTypeMenuController;
@property(nonatomic) __weak NSButton *removeBranchAfterMergeCheckBox; // @synthesize removeBranchAfterMergeCheckBox=_removeBranchAfterMergeCheckBox;
@property(nonatomic) __weak NSPopUpButton *mergeTypePopUpButton; // @synthesize mergeTypePopUpButton=_mergeTypePopUpButton;
@property(retain, nonatomic) GTServicePullRequest *pullRequest; // @synthesize pullRequest=_pullRequest;
- (void)updateRemovesBranchAfterMergeCheckbox;
- (void)updateMergeTypeMenu;
- (void)updateTitleAndText;
- (void)updateContentView;
- (void)updateIcon;
- (void)update;
- (void)viewDidDisappear;
- (void)viewDidAppear;
- (void)viewDidLoad;
@property(readonly, nonatomic) BOOL removesBranchAfterMerge;
@property(readonly, nonatomic) long long mergeType;
- (void)commonInit;

@end

