//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTServiceDeletePublicKeyOperation.h"

@class BeanstalkAPIClient, BeanstalkAPIRequest, NSString;

@interface GTServiceDeleteBeanstalkPublicKeyOperation : GTServiceDeletePublicKeyOperation
{
    BeanstalkAPIClient *_apiClient;
    BeanstalkAPIRequest *_request;
    long long _publicKeyID;
    NSString *_publicKeyName;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *publicKeyName; // @synthesize publicKeyName=_publicKeyName;
@property(nonatomic) long long publicKeyID; // @synthesize publicKeyID=_publicKeyID;
@property(retain, nonatomic) BeanstalkAPIRequest *request; // @synthesize request=_request;
@property(retain, nonatomic) BeanstalkAPIClient *apiClient; // @synthesize apiClient=_apiClient;
- (void)apiClientDidCancelRequest;
- (void)apiClientDidReceiveResponse:(id)arg1;
- (void)cancel;
- (void)performFetchRequest;
- (void)operationWillExecute;

@end

