//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDate, NSString, NSURL;
@protocol GTServiceAccountAdapter;

@protocol GTServiceRepositoryAdapter <NSObject>
@property(readonly, nonatomic) id <GTServiceAccountAdapter> serviceRepositoryOwner;
@property(readonly, nonatomic) unsigned long long serviceRepositorySCMType;
@property(readonly, nonatomic) unsigned long long serviceRepositoryAccessType;
@property(readonly, nonatomic, getter=isServiceRepositoryForked) BOOL serviceRepositoryForked;
@property(readonly, nonatomic) long long serviceRepositoryWatchers;
@property(readonly, nonatomic) long long serviceRepositoryForks;
@property(readonly, nonatomic) NSString *serviceRepositorySSHURL;
@property(readonly, nonatomic) NSURL *serviceRepositoryWebURL;
@property(readonly, nonatomic) NSURL *serviceRepositoryForkURL;
@property(readonly, nonatomic) NSURL *serviceRepositoryCloneURL;
@property(readonly, nonatomic) NSDate *serviceRepositoryUpdatedDate;
@property(readonly, nonatomic) NSDate *serviceRepositoryCreationDate;
@property(readonly, nonatomic) NSDate *serviceRepositoryLastCommitDate;
@property(retain, nonatomic) NSString *serviceRepositoryDescription;
@property(readonly, nonatomic) NSString *serviceRepositoryTitle;
@property(readonly, nonatomic) NSString *serviceRepositoryName;
@property(readonly, nonatomic) NSString *serviceRepositoryParentRepositoryID;
@property(readonly, nonatomic) NSString *serviceRepositoryID;
@end

