//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTSettingsCellView.h"

@class NSColor, NSFont, NSString, NSURL;

@interface GTSettingsURLCellView : GTSettingsCellView
{
    NSFont *_valueFont;
    NSColor *_valueColor;
}

+ (id)keyPathsForValuesAffectingCanOpenURL;
+ (id)keyPathsForValuesAffectingDisplayName;
+ (id)keyPathsForValuesAffectingUrl;
+ (id)keyPathsForValuesAffectingItem;
- (void).cxx_destruct;
@property(retain, nonatomic) NSColor *valueColor; // @synthesize valueColor=_valueColor;
@property(retain, nonatomic) NSFont *valueFont; // @synthesize valueFont=_valueFont;
- (void)openURL:(id)arg1;
@property(readonly, nonatomic) NSString *displayName;
@property(readonly, nonatomic) NSURL *url;
@property(readonly, nonatomic) BOOL canOpenURL;
- (id)item;
- (void)commonInit;

@end

