//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTServiceAccountOperation.h"

@class GTUpdateChangeset, NSManagedObjectID;
@protocol GTServiceRepositoryAdapter;

@interface GTServiceUpdateRepositoryOperation : GTServiceAccountOperation
{
    id <GTServiceRepositoryAdapter> _fetchedRepository;
    NSManagedObjectID *_serviceRepositoryID;
    GTUpdateChangeset *_changeset;
}

+ (id)operationWithManagedObjectContext:(id)arg1 serviceRepository:(id)arg2;
- (void).cxx_destruct;
@property(retain, nonatomic) GTUpdateChangeset *changeset; // @synthesize changeset=_changeset;
@property(retain, nonatomic) NSManagedObjectID *serviceRepositoryID; // @synthesize serviceRepositoryID=_serviceRepositoryID;
@property(retain) id <GTServiceRepositoryAdapter> fetchedRepository; // @synthesize fetchedRepository=_fetchedRepository;
- (BOOL)updateServiceRepositoryWithFetchedServiceRepository:(id)arg1 error:(id *)arg2;
- (BOOL)validateUpdateRepository;
- (void)performFetchRequest;
- (void)execute;
- (id)title;
- (id)initWithManagedObjectContext:(id)arg1 serviceAccountID:(id)arg2 serviceRepositoryID:(id)arg3;

@end

