//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTServiceAccountOperation.h"

@class GTServicePublicKeyCreationInfo;

@interface GTServiceCreatePublicKeyOperation : GTServiceAccountOperation
{
    GTServicePublicKeyCreationInfo *_servicePublicKeyCreationInfo;
}

+ (id)operationWithManagedObjectContext:(id)arg1 serviceAccount:(id)arg2 servicePublicKeyCreationInfo:(id)arg3;
- (void).cxx_destruct;
@property(retain, nonatomic) GTServicePublicKeyCreationInfo *servicePublicKeyCreationInfo; // @synthesize servicePublicKeyCreationInfo=_servicePublicKeyCreationInfo;
- (BOOL)validateCreatePublicKey;
- (void)performFetchRequest;
- (void)execute;
- (id)parameters;
- (id)title;
- (id)initWithManagedObjectContext:(id)arg1 serviceAccountID:(id)arg2 servicePublicKeyCreationInfo:(id)arg3;

@end

