//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary, NSURL;

@interface GTSSHAgent : NSObject
{
    NSURL *_askpassFileURL;
    NSDictionary *_askpassEnvironmentVariables;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSDictionary *askpassEnvironmentVariables; // @synthesize askpassEnvironmentVariables=_askpassEnvironmentVariables;
@property(retain, nonatomic) NSURL *askpassFileURL; // @synthesize askpassFileURL=_askpassFileURL;
- (BOOL)addPrivateKeyAtURL:(id)arg1 options:(long long)arg2 error:(id *)arg3;
@property(readonly, nonatomic) NSArray *allSSHKeyFingerprints;
- (id)makeEnvironment;

@end

