//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTRepositoryBaseViewController.h"

#import "GTRepositoryStashActions-Protocol.h"
#import "GTSearchControllerDelegate-Protocol.h"
#import "GTStashesItemControllerDelegate-Protocol.h"
#import "GTUserDefaultsKeyObserving-Protocol.h"
#import "NSMenuDelegate-Protocol.h"
#import "NSTableViewDataSource-Protocol.h"
#import "NSTableViewDelegate-Protocol.h"

@class GTGitStashManager, GTSearchController, GTStashesItemController, GTStashesListHeaderViewController, GTStashesMenuGenerator, GTStashesSearchScopeConfiguration, GTUserDefaultsKeyObserver, NSArray, NSIndexSet, NSString, NSTableView, NSView;
@protocol GTStashesListViewControllerDelegate;

@interface GTStashesListViewController : GTRepositoryBaseViewController <GTUserDefaultsKeyObserving, GTSearchControllerDelegate, GTRepositoryStashActions, NSTableViewDelegate, NSTableViewDataSource, NSMenuDelegate, GTStashesItemControllerDelegate>
{
    id <GTStashesListViewControllerDelegate> _delegate;
    NSTableView *_tableView;
    NSView *_containerHeaderView;
    GTStashesListHeaderViewController *_headerViewController;
    GTStashesItemController *_itemController;
    GTSearchController *_searchController;
    GTStashesSearchScopeConfiguration *_searchScopeConfiguration;
    GTUserDefaultsKeyObserver *_standardUserDefaultsObserver;
    NSArray *_selectedCommitHashes;
    NSIndexSet *_selectionIndexes;
    GTStashesMenuGenerator *_menuGenerator;
    GTGitStashManager *_stashManager;
}

- (void).cxx_destruct;
@property(retain, nonatomic) GTGitStashManager *stashManager; // @synthesize stashManager=_stashManager;
@property(retain, nonatomic) GTStashesMenuGenerator *menuGenerator; // @synthesize menuGenerator=_menuGenerator;
@property(retain, nonatomic) NSIndexSet *selectionIndexes; // @synthesize selectionIndexes=_selectionIndexes;
@property(retain, nonatomic) NSArray *selectedCommitHashes; // @synthesize selectedCommitHashes=_selectedCommitHashes;
@property(retain, nonatomic) GTUserDefaultsKeyObserver *standardUserDefaultsObserver; // @synthesize standardUserDefaultsObserver=_standardUserDefaultsObserver;
@property(retain, nonatomic) GTStashesSearchScopeConfiguration *searchScopeConfiguration; // @synthesize searchScopeConfiguration=_searchScopeConfiguration;
@property(nonatomic) __weak GTSearchController *searchController; // @synthesize searchController=_searchController;
@property(retain, nonatomic) GTStashesItemController *itemController; // @synthesize itemController=_itemController;
@property(retain, nonatomic) GTStashesListHeaderViewController *headerViewController; // @synthesize headerViewController=_headerViewController;
@property(nonatomic) __weak NSView *containerHeaderView; // @synthesize containerHeaderView=_containerHeaderView;
@property(nonatomic) __weak NSTableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) __weak id <GTStashesListViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)restoreSelectedStashes;
- (void)storeSelectedStashes;
- (void)delete:(id)arg1;
- (void)apply:(id)arg1;
- (void)deleteStashes:(id)arg1;
- (void)deleteStash:(id)arg1;
- (void)applyStash:(id)arg1;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (void)windowDidChangeFirstResponder;
- (void)userDefaultsDidChangeKey:(id)arg1 change:(id)arg2;
- (void)repositoryDidUpdateStashes:(id)arg1;
- (void)stashesItemControllerDidFinishLoading;
@property(readonly, nonatomic) NSView *searchControllerKeyView;
- (void)searchControllerDidEndSearching;
- (void)searchControllerDidUpdate;
- (void)tableView:(id)arg1 draggingSession:(id)arg2 endedAtPoint:(struct CGPoint)arg3 operation:(unsigned long long)arg4;
- (BOOL)tableView:(id)arg1 acceptDrop:(id)arg2 row:(long long)arg3 dropOperation:(unsigned long long)arg4;
- (void)tableView:(id)arg1 draggingSession:(id)arg2 willBeginAtPoint:(struct CGPoint)arg3 forRowIndexes:(id)arg4;
- (id)tableView:(id)arg1 pasteboardWriterForRow:(long long)arg2;
- (id)tableView:(id)arg1 objectValueForTableColumn:(id)arg2 row:(long long)arg3;
- (long long)numberOfRowsInTableView:(id)arg1;
- (void)tableViewSelectionDidChange:(id)arg1;
- (double)tableView:(id)arg1 heightOfRow:(long long)arg2;
- (id)tableView:(id)arg1 viewForTableColumn:(id)arg2 row:(long long)arg3;
- (void)menuNeedsUpdate:(id)arg1;
- (void)reloadTableView;
- (void)updateWindowTitle;
- (void)reload;
- (void)viewWillDisappear;
- (void)viewDidAppear;
- (void)viewDidLoad;
- (void)configureHeaderView;
- (void)configureTableView;
- (void)configure;
- (id)affectedItems;
@property(readonly, nonatomic) NSArray *selectedStashes;
- (id)selectedItems;
- (void)commonInit;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

