//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTMenuGenerator.h"

@class GTGitBranchManager, GTGitSubmodule, GTGitTagManager;

@interface GTSubmoduleCheckoutMenuGenerator : GTMenuGenerator
{
    GTGitSubmodule *_submodule;
    GTGitBranchManager *_branchManager;
    GTGitTagManager *_tagManager;
}

- (void).cxx_destruct;
@property(retain, nonatomic) GTGitTagManager *tagManager; // @synthesize tagManager=_tagManager;
@property(retain, nonatomic) GTGitBranchManager *branchManager; // @synthesize branchManager=_branchManager;
@property(retain, nonatomic) GTGitSubmodule *submodule; // @synthesize submodule=_submodule;
- (void)menuGeneratorDidFinishReloadingTags;
- (void)menuGeneratorDidFinishReloadingBranches;
- (void)reloadSubmoduleComponents;
- (BOOL)isDetachedHeadRevisionEqualToTagRevisionForSubmodule:(id)arg1;
- (id)makeDetachedHeadRevisionItemIfNeededForSubmodule:(id)arg1;
- (id)makeTagMenuItemsForSubmodule:(id)arg1;
- (id)makeBranchMenuItemsForSubmodule:(id)arg1;
- (void)makeMenuItems;

@end

