//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSMenuDelegate-Protocol.h"
#import "NSOpenSavePanelDelegate-Protocol.h"

@class GTGitRepository, GTSubmoduleDestinationInputValidator, GTSubmodulePathSelectionMenuGenerator, NSPopUpButton, NSString, NSURL;

@interface GTSubmodulePathSelectionController : NSObject <NSMenuDelegate, NSOpenSavePanelDelegate>
{
    NSPopUpButton *_popUpButton;
    GTGitRepository *_repository;
    NSString *_destinationPath;
    NSString *_lastValidDestinationPath;
    GTSubmodulePathSelectionMenuGenerator *_menuGenerator;
    GTSubmoduleDestinationInputValidator *_submoduleDestinationValidator;
}

+ (id)keyPathsForValuesAffectingDestinationFileURL;
- (void).cxx_destruct;
@property(retain, nonatomic) GTSubmoduleDestinationInputValidator *submoduleDestinationValidator; // @synthesize submoduleDestinationValidator=_submoduleDestinationValidator;
@property(retain, nonatomic) GTSubmodulePathSelectionMenuGenerator *menuGenerator; // @synthesize menuGenerator=_menuGenerator;
@property(retain, nonatomic) NSString *lastValidDestinationPath; // @synthesize lastValidDestinationPath=_lastValidDestinationPath;
@property(retain, nonatomic) NSString *destinationPath; // @synthesize destinationPath=_destinationPath;
@property(retain, nonatomic) GTGitRepository *repository; // @synthesize repository=_repository;
@property(nonatomic) __weak NSPopUpButton *popUpButton; // @synthesize popUpButton=_popUpButton;
- (void)update;
- (void)menuNeedsUpdate:(id)arg1;
- (BOOL)panel:(id)arg1 validateURL:(id)arg2 error:(id *)arg3;
- (void)destinationPathSelectionDidChange:(id)arg1;
- (void)awakeFromNib;
@property(readonly, nonatomic) NSURL *destinationFileURL;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

