//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class GTTheme;

@interface GTThemeController : NSObject
{
    // Error parsing type: , name: themes
    // Error parsing type: , name: invalidThemeURLs
    // Error parsing type: , name: nameToTheme
    // Error parsing type: , name: identifierToTheme
    // Error parsing type: , name: queue
    // Error parsing type: , name: isLoading
    // Error parsing type: , name: keyPathObserver
    // Error parsing type: , name: themesObserver
}

+ (id)sharedController;
- (void).cxx_destruct;
- (void)themesDidChangeWithNotification:(id)arg1;
@property(nonatomic, readonly) GTTheme *activeTheme;
- (void)dealloc;
- (id)init;

@end

