//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTGitActionSenderValidator.h"

@class NSArray, NSString;

@interface GTTreeActionSenderValidator : GTGitActionSenderValidator
{
    NSString *_revision;
    NSArray *_treeEntries;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *treeEntries; // @synthesize treeEntries=_treeEntries;
@property(retain, nonatomic) NSString *revision; // @synthesize revision=_revision;
- (BOOL)validateRawFileAtRevisionWithMenuItem:(id)arg1;
- (BOOL)validateBlameActionWithMenuItem:(id)arg1;
- (BOOL)validateShowFileHistoryActionWithMenuItem:(id)arg1;
- (BOOL)validateExportRevisionActionWithMenuItem:(id)arg1;
- (BOOL)validateResetToRevisionActionWithMenuItem:(id)arg1;
- (BOOL)validateOpenActionWithMenuItem:(id)arg1;
- (void)registerActions;

@end

