//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTViewController.h"

#import "GTGitGlobalConfigObserving-Protocol.h"
#import "GTGitUserProfilesObserving-Protocol.h"

@class GTAvatarImageView, GTGitGlobalConfigObserver, GTGitUserProfile, GTGitUserProfilesObserver, GTStateManager, NSColor, NSString;

@interface GTUserPreferencesProfilesDetailViewController : GTViewController <GTGitUserProfilesObserving, GTGitGlobalConfigObserving>
{
    BOOL _ensuresKeyEmailMatchesUserEmail;
    GTGitUserProfile *_userProfile;
    GTAvatarImageView *_avatarImageView;
    GTStateManager *_viewState;
    GTGitUserProfilesObserver *_userProfilesObserver;
    GTGitGlobalConfigObserver *_gitConfigObserver;
}

+ (id)keyPathsForValuesAffectingShowNonMatchingKeyWarning;
+ (id)keyPathsForValuesAffectingHasGPGKey;
+ (id)keyPathsForValuesAffectingGpgUser;
+ (id)keyPathsForValuesAffectingGpgKey;
+ (id)keyPathsForValuesAffectingEmail;
+ (id)keyPathsForValuesAffectingName;
+ (id)keyPathsForValuesAffectingProfileTitle;
- (void).cxx_destruct;
@property(retain, nonatomic) GTGitGlobalConfigObserver *gitConfigObserver; // @synthesize gitConfigObserver=_gitConfigObserver;
@property(retain, nonatomic) GTGitUserProfilesObserver *userProfilesObserver; // @synthesize userProfilesObserver=_userProfilesObserver;
@property(retain, nonatomic) GTStateManager *viewState; // @synthesize viewState=_viewState;
@property(nonatomic) BOOL ensuresKeyEmailMatchesUserEmail; // @synthesize ensuresKeyEmailMatchesUserEmail=_ensuresKeyEmailMatchesUserEmail;
@property(nonatomic) __weak GTAvatarImageView *avatarImageView; // @synthesize avatarImageView=_avatarImageView;
@property(retain, nonatomic) GTGitUserProfile *userProfile; // @synthesize userProfile=_userProfile;
- (void)stopObservers;
- (void)startObservers;
- (void)userDefaultsDidChangeKey:(id)arg1 change:(id)arg2;
- (void)globalConfigDidUpdate:(id)arg1;
- (void)gitUserProfilesDidUpdate:(id)arg1;
- (void)showGPGKeyEmailDoesNotMatchGitUserEmailAlert:(id)arg1;
- (void)editUserProfile:(id)arg1;
- (void)updateEnsuresKeyEmailMatchesUserEmail;
- (BOOL)needsUpdateEnsuresKeyEmailMatchesUserEmail;
- (void)updateAvatarImageView;
- (BOOL)needsUpdateAvatarImageView;
- (void)updateViewComponents;
- (void)updateViewState;
- (void)update;
- (void)viewWillDisappear;
- (void)viewWillAppear;
- (void)viewDidLoad;
@property(readonly, nonatomic) BOOL keyEmailMatchesUserEmail;
@property(readonly, nonatomic) BOOL showNonMatchingKeyWarning;
- (BOOL)isGlobalUser;
@property(readonly, nonatomic) NSColor *secondaryTextColor;
@property(readonly, nonatomic) NSColor *textColor;
@property(readonly, nonatomic) BOOL hasGPGKey;
@property(readonly, nonatomic) NSString *gpgUser;
@property(readonly, nonatomic) NSString *gpgKey;
@property(readonly, nonatomic) NSString *email;
@property(readonly, nonatomic) NSString *name;
@property(readonly, nonatomic) NSString *profileTitle;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

