//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FNFoundation/FNObserver.h>

@protocol GTViewStylesObserving;

@interface GTViewStylesObserver : FNObserver
{
    // Error parsing type: , name: observer
}

- (void).cxx_destruct;
- (id)init;
- (void)registerObservers;
@property(nonatomic, readonly) id invocationTarget;
- (id)initWithObserver:(id)arg1;
@property(nonatomic, readonly) id <GTViewStylesObserving> observer; // @synthesize observer;

@end

