//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FNFoundation/FNObserver.h>

@class NSView;
@protocol GTViewObserving;

@interface GTViewObserver : FNObserver
{
    id <GTViewObserving> _delegate;
    NSView *_observedView;
    NSView *_observedViewNotSupportingWeakReferences;
}

+ (id)observerWithView:(id)arg1 delegate:(id)arg2;
- (void).cxx_destruct;
@property(nonatomic) NSView *observedViewNotSupportingWeakReferences; // @synthesize observedViewNotSupportingWeakReferences=_observedViewNotSupportingWeakReferences;
@property(nonatomic) __weak NSView *observedView; // @synthesize observedView=_observedView;
@property(nonatomic) __weak id <GTViewObserving> delegate; // @synthesize delegate=_delegate;
- (void)registerObservers;
- (id)invocationTarget;
- (id)notificationObject;
@property(readonly, nonatomic) NSView *view;
- (id)initWithView:(id)arg1 delegate:(id)arg2;
- (id)init;

@end

