//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSButton.h>

@class NSAttributedString, NSColor, NSFont;

@interface GTWelcomeRegisterButtonView : NSButton
{
    NSColor *_buttonHeadlineColor;
    NSFont *_buttonHeadlineFont;
    NSAttributedString *_buttonHeadlineText;
    NSColor *_buttonTextColor;
    NSFont *_buttonTextFont;
    NSAttributedString *_buttonText;
    NSColor *_titleColor;
    NSColor *_buttonBackgroundColor;
    double _shadowOffset;
}

- (void).cxx_destruct;
@property(nonatomic) double shadowOffset; // @synthesize shadowOffset=_shadowOffset;
@property(retain, nonatomic) NSColor *buttonBackgroundColor; // @synthesize buttonBackgroundColor=_buttonBackgroundColor;
@property(retain, nonatomic) NSColor *titleColor; // @synthesize titleColor=_titleColor;
@property(retain, nonatomic) NSAttributedString *buttonText; // @synthesize buttonText=_buttonText;
@property(retain, nonatomic) NSFont *buttonTextFont; // @synthesize buttonTextFont=_buttonTextFont;
@property(retain, nonatomic) NSColor *buttonTextColor; // @synthesize buttonTextColor=_buttonTextColor;
@property(retain, nonatomic) NSAttributedString *buttonHeadlineText; // @synthesize buttonHeadlineText=_buttonHeadlineText;
@property(retain, nonatomic) NSFont *buttonHeadlineFont; // @synthesize buttonHeadlineFont=_buttonHeadlineFont;
@property(retain, nonatomic) NSColor *buttonHeadlineColor; // @synthesize buttonHeadlineColor=_buttonHeadlineColor;
- (id)textAttributes;
- (void)drawButtonTitels;
- (void)drawRect:(struct CGRect)arg1;
- (BOOL)isHighlighted;
- (void)commonInit;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

