//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface GTWindowTitleManager : NSObject
{
}

+ (id)displayTitleForStashesViewStatus:(id)arg1;
+ (id)displayTitleForHistoryViewStatus:(id)arg1;
+ (id)displayTitleForWorkingCopyStatusOfRepository:(id)arg1;
+ (id)displayTitleForRepository:(id)arg1;
+ (id)displayTitleForBranch:(id)arg1;
+ (id)displayTitleForRef:(id)arg1;
+ (id)submoduleSettingsWindowSubtitleWithSubmodule:(id)arg1;
+ (id)submoduleSettingsWindowTitleWithSubmodule:(id)arg1;
+ (id)remoteSettingsWindowSubtitleWithRemote:(id)arg1;
+ (id)remoteSettingsWindowTitleWithRemote:(id)arg1;
+ (id)repositorySettingsWindowSubtitleWithRepository:(id)arg1;
+ (id)repositorySettingsWindowTitleWithRepository:(id)arg1;
+ (id)treeWindowSubtitleWithRepository:(id)arg1 revision:(id)arg2;
+ (id)treeWindowTitleWithRepository:(id)arg1 revision:(id)arg2;
+ (id)commitWindowSubtitleWithRepository:(id)arg1 revision:(id)arg2;
+ (id)commitWindowTitleWithRepository:(id)arg1 revision:(id)arg2;
+ (id)blobWindowSubtitleWithRepository:(id)arg1 fileRevision:(id)arg2;
+ (id)blobWindowTitleWithRepository:(id)arg1 fileRevision:(id)arg2;
+ (id)fileHistoryWindowSubtitleWithRepository:(id)arg1 filePath:(id)arg2;
+ (id)fileHistoryWindowTitleWithRepository:(id)arg1 filePath:(id)arg2;
+ (id)pullRequestsWindowSubtitleWithRepository:(id)arg1 remote:(id)arg2;
+ (id)pullRequestsWindowTitleWithRepository:(id)arg1 remote:(id)arg2;
+ (id)reflogWindowSubtitleWithRepository:(id)arg1 ref:(id)arg2;
+ (id)reflogWindowTitleWithRepository:(id)arg1 ref:(id)arg2;
+ (id)stashesWindowSubtitleWithStashesViewStatus:(id)arg1;
+ (id)stashesWindowTitleWithStashesViewStatus:(id)arg1;
+ (id)historyWindowSubtitleWithHistoryViewStatus:(id)arg1;
+ (id)historyWindowTitleWithHistoryViewStatus:(id)arg1;
+ (id)workingCopyWindowSubtitleWithRepository:(id)arg1;
+ (id)workingCopyWindowTitleWithRepository:(id)arg1;
+ (id)servicePublicKeysWindowSubtitleForServiceAccount:(id)arg1;
+ (id)servicePublicKeysWindowTitleForServiceAccount:(id)arg1;
+ (id)serviceRepositoriesWindowSubtitleForServiceAccount:(id)arg1;
+ (id)serviceRepositoriesWindowTitleForServiceAccount:(id)arg1;
+ (id)defaultServicesWindowSubtitleForServiceAccount:(id)arg1;
+ (id)defaultServicesWindowTitleForServiceAccount:(id)arg1;
+ (id)defaultServicesWindowSubtitle;
+ (id)defaultServicesWindowTitle;

@end

