//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTViewController.h"

#import "GTGitRepositoryObserving-Protocol.h"
#import "GTGitWorkingCopyProgressControllerDelegate-Protocol.h"
#import "GTNavigationComponent-Protocol.h"

@class GTGitRepository, GTGitRepositoryObserver, GTGitWorkingCopyProgressController, GTWorkingCopyContainerViewController, GTWorkingCopyProgressViewController, NSArray, NSString, NSURL, NSViewController;

@interface GTWorkingCopyViewController : GTViewController <GTGitWorkingCopyProgressControllerDelegate, GTGitRepositoryObserving, GTNavigationComponent>
{
    GTGitRepository *_repository;
    GTGitRepositoryObserver *_repositoryObserver;
    GTWorkingCopyContainerViewController *_workingCopyContainerViewController;
    GTWorkingCopyProgressViewController *_workingCopyProgressViewController;
    GTGitWorkingCopyProgressController *_workingCopyProgressController;
    NSViewController *_currentViewController;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSViewController *currentViewController; // @synthesize currentViewController=_currentViewController;
@property(retain, nonatomic) GTGitWorkingCopyProgressController *workingCopyProgressController; // @synthesize workingCopyProgressController=_workingCopyProgressController;
@property(retain, nonatomic) GTWorkingCopyProgressViewController *workingCopyProgressViewController; // @synthesize workingCopyProgressViewController=_workingCopyProgressViewController;
@property(retain, nonatomic) GTWorkingCopyContainerViewController *workingCopyContainerViewController; // @synthesize workingCopyContainerViewController=_workingCopyContainerViewController;
@property(retain, nonatomic) GTGitRepositoryObserver *repositoryObserver; // @synthesize repositoryObserver=_repositoryObserver;
@property(retain, nonatomic) GTGitRepository *repository; // @synthesize repository=_repository;
- (void)displayViewController:(id)arg1;
- (void)displayWorkingCopyProgressView;
- (void)displayWorkingCopyView;
- (void)repositoryDidUpdateBranches:(id)arg1;
- (void)repositoryDidUpdateWorkingTree:(id)arg1;
- (void)workingCopyProgressControllerDidFinishReceivingProgress:(id)arg1;
- (void)workingCopyProgressControllerDidStartReceivingProgress:(id)arg1;
- (void)updateComposeCommitMessage:(id)arg1;
- (void)updateWindowTitle;
- (void)update;
- (void)viewWillDisappear;
- (void)viewDidAppear;
- (void)viewWillAppear;
- (void)viewDidLoad;
- (void)loadView;
@property(readonly, nonatomic) NSArray *navigationPathComponents;
@property(readonly, nonatomic) NSURL *navigationURL;
@property(readonly, nonatomic) NSString *navigationIdentifier;
- (void)dealloc;
- (void)commonInit;
- (id)initWithCoder:(id)arg1;
- (id)initWithRepository:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

