//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FNAppKit/FNViewController.h>

#import "GTGitRepositoryObserving-Protocol.h"
#import "GTRepositoryBranchActions-Protocol.h"
#import "GTRepositoryWorkingCopyActions-Protocol.h"
#import "NSMenuDelegate-Protocol.h"

@class GTBranchActionSenderValidator, GTGitMergeStatusController, GTGitRepository, GTGitRepositoryController, GTGitRepositoryObserver, GTRefControl, GTStateManager, GTWorkingCopyChangeTrackingMenuGenerator, GTWorkingCopyCheckoutMenuGenerator, GTWorkingCopyDefaultStatusHeaderView, GTWorkingCopyMergeStatusHeaderView, NSImage, NSLayoutConstraint, NSMenu, NSNumber, NSSegmentedControl, NSString;

@interface GTWorkingCopyStatusHeaderViewController : FNViewController <GTGitRepositoryObserving, NSMenuDelegate, GTRepositoryBranchActions, GTRepositoryWorkingCopyActions>
{
    BOOL _changeTrackingMenuGeneratorNeedsUpdate;
    BOOL _abortMergeButtonEnabled;
    GTGitRepository *_repository;
    GTWorkingCopyDefaultStatusHeaderView *_defaultStatusView;
    GTWorkingCopyMergeStatusHeaderView *_mergeStatusView;
    NSSegmentedControl *_actionButtonControl;
    NSNumber *_selectedActionValue;
    NSImage *_icon;
    GTRefControl *_gitRefControl;
    GTGitRepositoryObserver *_repositoryObserver;
    GTGitMergeStatusController *_mergeStatusController;
    GTGitRepositoryController *_repositoryController;
    GTBranchActionSenderValidator *_branchActionsValidator;
    GTWorkingCopyCheckoutMenuGenerator *_checkoutMenuGenerator;
    GTWorkingCopyChangeTrackingMenuGenerator *_changeTrackingMenuGenerator;
    GTStateManager *_viewState;
    NSString *_mergeStatusHeaderLabel;
    NSLayoutConstraint *_defaultImageToRefYAxisAlignmentConstraint;
    NSLayoutConstraint *_mergeImageToRefYAxisAlignmentConstraint;
}

+ (id)keyPathsForValuesAffectingSelectedAction;
- (void).cxx_destruct;
@property(nonatomic) __weak NSLayoutConstraint *mergeImageToRefYAxisAlignmentConstraint; // @synthesize mergeImageToRefYAxisAlignmentConstraint=_mergeImageToRefYAxisAlignmentConstraint;
@property(nonatomic) __weak NSLayoutConstraint *defaultImageToRefYAxisAlignmentConstraint; // @synthesize defaultImageToRefYAxisAlignmentConstraint=_defaultImageToRefYAxisAlignmentConstraint;
@property(nonatomic, getter=isAbortMergeButtonEnabled) BOOL abortMergeButtonEnabled; // @synthesize abortMergeButtonEnabled=_abortMergeButtonEnabled;
@property(nonatomic) BOOL changeTrackingMenuGeneratorNeedsUpdate; // @synthesize changeTrackingMenuGeneratorNeedsUpdate=_changeTrackingMenuGeneratorNeedsUpdate;
@property(retain, nonatomic) NSString *mergeStatusHeaderLabel; // @synthesize mergeStatusHeaderLabel=_mergeStatusHeaderLabel;
@property(retain, nonatomic) GTStateManager *viewState; // @synthesize viewState=_viewState;
@property(retain, nonatomic) GTWorkingCopyChangeTrackingMenuGenerator *changeTrackingMenuGenerator; // @synthesize changeTrackingMenuGenerator=_changeTrackingMenuGenerator;
@property(retain, nonatomic) GTWorkingCopyCheckoutMenuGenerator *checkoutMenuGenerator; // @synthesize checkoutMenuGenerator=_checkoutMenuGenerator;
@property(retain, nonatomic) GTBranchActionSenderValidator *branchActionsValidator; // @synthesize branchActionsValidator=_branchActionsValidator;
@property(retain, nonatomic) GTGitRepositoryController *repositoryController; // @synthesize repositoryController=_repositoryController;
@property(retain, nonatomic) GTGitMergeStatusController *mergeStatusController; // @synthesize mergeStatusController=_mergeStatusController;
@property(retain, nonatomic) GTGitRepositoryObserver *repositoryObserver; // @synthesize repositoryObserver=_repositoryObserver;
@property(nonatomic) __weak GTRefControl *gitRefControl; // @synthesize gitRefControl=_gitRefControl;
@property(retain, nonatomic) NSImage *icon; // @synthesize icon=_icon;
@property(retain, nonatomic) NSNumber *selectedActionValue; // @synthesize selectedActionValue=_selectedActionValue;
@property(nonatomic) __weak NSSegmentedControl *actionButtonControl; // @synthesize actionButtonControl=_actionButtonControl;
@property(retain, nonatomic) GTWorkingCopyMergeStatusHeaderView *mergeStatusView; // @synthesize mergeStatusView=_mergeStatusView;
@property(retain, nonatomic) GTWorkingCopyDefaultStatusHeaderView *defaultStatusView; // @synthesize defaultStatusView=_defaultStatusView;
@property(retain, nonatomic) GTGitRepository *repository; // @synthesize repository=_repository;
- (void)updateAbortContinueMergeButtonState;
- (BOOL)validateMenuItem:(id)arg1;
- (void)menuNeedsUpdate:(id)arg1;
- (void)actionButtonSelectionDidChange:(id)arg1;
- (void)continueMerge:(id)arg1;
- (void)abortMerge:(id)arg1;
- (void)unsetUpstreamBranch:(id)arg1;
- (void)setUpstreamBranch:(id)arg1;
- (id)theirsRefName;
- (id)mineRefName;
- (id)theirsRefNameOrRevision;
- (id)mineRefNameOrRevision;
- (id)trackedBranchName;
- (BOOL)headBranchHasTracking;
- (id)headBranchDisplayName;
- (void)displayMergeStatusHeaderView;
- (void)displayDefaultStatusHeaderView;
- (void)updateRefControl;
- (BOOL)needsUpdateRefControl;
- (void)updateIconAndTitle;
- (BOOL)needsUpdateIconAndTitle;
- (void)updateActionButtonControl;
- (BOOL)needsUpdateActionButtonControl;
- (void)updateHeaderView;
- (BOOL)needsUpdateHeaderView;
- (void)updateTrackingMenu;
- (BOOL)needsUpdateTrackingMenu;
- (void)updateCheckoutMenu;
- (BOOL)needsUpdateCheckoutMenu;
- (void)updateViewState;
- (void)update;
- (void)repositoryDidUpdateRemotes:(id)arg1;
- (void)repositoryDidUpdateBranches:(id)arg1;
- (void)repositoryDidUpdateWorkingTree:(id)arg1;
- (void)repositoryDidUpdateWorkingCopy:(id)arg1;
- (void)repositoryWillUpdateWorkingCopy:(id)arg1;
- (void)viewWillDisappear;
- (void)viewWillAppear;
- (void)viewDidLoad;
- (void)configureActionButtonControl;
@property(readonly, nonatomic) long long selectedAction;
@property(readonly, nonatomic) NSMenu *changeTrackingMenu;
@property(readonly, nonatomic) NSMenu *checkoutMenu;
- (void)dealloc;
- (void)commonInit;
- (id)initWithRepository:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

