//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTWorkingCopyConflictResolutionStatusViewController.h"

@class NSString;

@interface GTWorkingCopyMergeStatusViewController : GTWorkingCopyConflictResolutionStatusViewController
{
    NSString *_statusTitleText;
    NSString *_statusDescriptionText;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *statusDescriptionText; // @synthesize statusDescriptionText=_statusDescriptionText;
@property(retain, nonatomic) NSString *statusTitleText; // @synthesize statusTitleText=_statusTitleText;
- (void)updateStatusDescriptionText;
- (void)updateStatusTitleText;
- (void)update;

@end

