//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface GTWorkingTreeViewSettings : NSObject
{
    BOOL _showsNonModifiedFiles;
    BOOL _showsIgnoredFiles;
    BOOL _showsAssumeUnchangedFiles;
    long long _viewMode;
}

+ (id)currentViewSettings;
@property(nonatomic) long long viewMode; // @synthesize viewMode=_viewMode;
@property(nonatomic) BOOL showsAssumeUnchangedFiles; // @synthesize showsAssumeUnchangedFiles=_showsAssumeUnchangedFiles;
@property(nonatomic) BOOL showsIgnoredFiles; // @synthesize showsIgnoredFiles=_showsIgnoredFiles;
@property(nonatomic) BOOL showsNonModifiedFiles; // @synthesize showsNonModifiedFiles=_showsNonModifiedFiles;

@end

