//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTViewController.h"

#import "GTGitRepositoryObserving-Protocol.h"
#import "GTOpenFileActions-Protocol.h"
#import "GTRepositoryHistoryActions-Protocol.h"
#import "GTRepositoryWorkingTreeActions-Protocol.h"
#import "GTSearchControllerDelegate-Protocol.h"
#import "GTUserDefaultsKeyObserving-Protocol.h"
#import "GTWindowObserving-Protocol.h"
#import "GTWorkingTreeItemControllerDelegate-Protocol.h"
#import "NSMenuDelegate-Protocol.h"
#import "NSOpenSavePanelDelegate-Protocol.h"
#import "NSOutlineViewDataSource-Protocol.h"
#import "NSOutlineViewDelegate-Protocol.h"
#import "QLPreviewPanelDataSource-Protocol.h"
#import "QLPreviewPanelDelegate-Protocol.h"

@class GTGitMergeToolController, GTGitRepository, GTGitRepositoryController, GTGitRepositoryObserver, GTSearchController, GTStashActionSenderValidator, GTWorkingCopyOutlineView, GTWorkingCopySearchScopeConfiguration, GTWorkingTreeActionSenderValidator, GTWorkingTreeItemController, GTWorkingTreeMenuGenerator, GTWorkingTreeViewSettings, NSArray, NSIndexSet, NSString, NSView;
@protocol GTWorkingCopyFileListViewControllerDelegate;

@interface GTWorkingCopyFileListViewController : GTViewController <NSOpenSavePanelDelegate, NSMenuDelegate, GTWorkingTreeItemControllerDelegate, GTSearchControllerDelegate, NSOutlineViewDataSource, NSOutlineViewDelegate, QLPreviewPanelDataSource, QLPreviewPanelDelegate, GTUserDefaultsKeyObserving, GTGitRepositoryObserving, GTWindowObserving, GTRepositoryWorkingTreeActions, GTOpenFileActions, GTRepositoryHistoryActions>
{
    BOOL _locked;
    BOOL _restoringSelection;
    GTGitRepository *_repository;
    id <GTWorkingCopyFileListViewControllerDelegate> _delegate;
    GTWorkingCopyOutlineView *_outlineView;
    GTGitRepositoryController *_repositoryController;
    GTGitMergeToolController *_mergeToolController;
    GTWorkingTreeItemController *_workingTreeItemController;
    GTSearchController *_searchController;
    GTWorkingCopySearchScopeConfiguration *_searchScopeConfiguration;
    GTGitRepositoryObserver *_repositoryObserver;
    NSArray *_storedSelectedItems;
    NSIndexSet *_selectedItemIndexes;
    GTWorkingTreeMenuGenerator *_menuGenerator;
    GTWorkingTreeActionSenderValidator *_workingTreeActionsValidator;
    GTStashActionSenderValidator *_stashActionsValidator;
    GTWorkingTreeViewSettings *_viewSettings;
    NSArray *_quickLookItems;
    NSArray *_quickLookSelectionItems;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *quickLookSelectionItems; // @synthesize quickLookSelectionItems=_quickLookSelectionItems;
@property(retain, nonatomic) NSArray *quickLookItems; // @synthesize quickLookItems=_quickLookItems;
@property(retain, nonatomic) GTWorkingTreeViewSettings *viewSettings; // @synthesize viewSettings=_viewSettings;
@property(retain, nonatomic) GTStashActionSenderValidator *stashActionsValidator; // @synthesize stashActionsValidator=_stashActionsValidator;
@property(retain, nonatomic) GTWorkingTreeActionSenderValidator *workingTreeActionsValidator; // @synthesize workingTreeActionsValidator=_workingTreeActionsValidator;
@property(retain, nonatomic) GTWorkingTreeMenuGenerator *menuGenerator; // @synthesize menuGenerator=_menuGenerator;
@property(nonatomic, getter=isRestoringSelection) BOOL restoringSelection; // @synthesize restoringSelection=_restoringSelection;
@property(retain, nonatomic) NSIndexSet *selectedItemIndexes; // @synthesize selectedItemIndexes=_selectedItemIndexes;
@property(retain, nonatomic) NSArray *storedSelectedItems; // @synthesize storedSelectedItems=_storedSelectedItems;
@property(retain, nonatomic) GTGitRepositoryObserver *repositoryObserver; // @synthesize repositoryObserver=_repositoryObserver;
@property(retain, nonatomic) GTWorkingCopySearchScopeConfiguration *searchScopeConfiguration; // @synthesize searchScopeConfiguration=_searchScopeConfiguration;
@property(nonatomic) __weak GTSearchController *searchController; // @synthesize searchController=_searchController;
@property(retain, nonatomic) GTWorkingTreeItemController *workingTreeItemController; // @synthesize workingTreeItemController=_workingTreeItemController;
@property(retain, nonatomic) GTGitMergeToolController *mergeToolController; // @synthesize mergeToolController=_mergeToolController;
@property(retain, nonatomic) GTGitRepositoryController *repositoryController; // @synthesize repositoryController=_repositoryController;
@property(nonatomic, getter=isLocked) BOOL locked; // @synthesize locked=_locked;
@property(nonatomic) __weak GTWorkingCopyOutlineView *outlineView; // @synthesize outlineView=_outlineView;
@property(nonatomic) __weak id <GTWorkingCopyFileListViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) GTGitRepository *repository; // @synthesize repository=_repository;
- (BOOL)validateToolbarItem:(id)arg1;
- (BOOL)validateMenuItem:(id)arg1;
- (void)menuNeedsUpdate:(id)arg1;
@property(readonly, nonatomic) NSView *searchControllerKeyView;
- (void)searchControllerDidEndSearching;
- (void)searchControllerDidUpdate;
- (void)markRowViewForDisplay:(id)arg1;
- (void)updateRowView:(id)arg1 item:(id)arg2;
- (void)markRowsAtIndexes:(id)arg1 withOptions:(unsigned long long)arg2;
- (id)affectedWorkingTreeEntries;
- (id)affectedItems;
- (void)unsetAssumeUnchangedBitForEntries:(id)arg1 atRowIndexes:(id)arg2;
- (void)setAssumeUnchangedBitForEntries:(id)arg1 atRowIndexes:(id)arg2;
- (void)discardLocalChangesForEntries:(id)arg1 atRowIndexes:(id)arg2;
- (void)untrackEntries:(id)arg1 atRowIndexes:(id)arg2;
- (void)deleteEntries:(id)arg1 atRowIndexes:(id)arg2;
- (void)unstageEntries:(id)arg1 atRowIndexes:(id)arg2;
- (void)stageEntries:(id)arg1 atRowIndexes:(id)arg2;
- (BOOL)previewPanel:(id)arg1 handleEvent:(id)arg2;
- (id)previewPanel:(id)arg1 previewItemAtIndex:(long long)arg2;
- (long long)numberOfPreviewItemsInPreviewPanel:(id)arg1;
- (void)endPreviewPanelControl:(id)arg1;
- (void)beginPreviewPanelControl:(id)arg1;
- (BOOL)acceptsPreviewPanelControl:(id)arg1;
- (void)updateQuickLookPreviewPanelIfNeeded;
- (void)updateQuickLookItemsWithCurrentSelection;
- (void)quickSavePartialStash:(id)arg1;
- (void)savePartialStash:(id)arg1;
- (void)saveStash:(id)arg1;
- (void)showFileHistory:(id)arg1;
- (void)blame:(id)arg1;
- (void)rawFileAtRevision:(id)arg1;
- (void)openItemInTerminal:(id)arg1;
- (void)openItemsInFinder:(id)arg1;
- (void)openItemsInQuickLook:(id)arg1;
- (void)openItemsWithOtherApplication:(id)arg1;
- (void)openItemsWithApplication:(id)arg1;
- (void)openItemsWithDefaultApplication:(id)arg1;
- (void)openInFinder:(id)arg1;
- (void)openInTerminal:(id)arg1;
- (void)compareTheirsToMergeBase:(id)arg1;
- (void)compareMineToMergeBase:(id)arg1;
- (void)compareMineToTheirs:(id)arg1;
- (void)compareIndexToBase:(id)arg1;
- (void)compareWorkingTreeToIndex:(id)arg1;
- (void)unsetAssumeUnchangedForItems:(id)arg1;
- (void)setAssumeUnchangedForItems:(id)arg1;
- (void)createLFSTrackedFilePatternFromItem:(id)arg1;
- (void)addLFSTrackAllPatternsForItems:(id)arg1;
- (void)addLFSTrackedFilePatternsForItems:(id)arg1;
- (void)createExcludePatternFromItem:(id)arg1;
- (void)addExcludeAllPatternsForItemsWithType:(id)arg1;
- (void)addExcludeAllPatternsForItems:(id)arg1;
- (void)addExcludePatternsForItems:(id)arg1;
- (void)createIgnorePatternFromItem:(id)arg1;
- (void)addIgnoreAllPatternsForItemsWithType:(id)arg1;
- (void)addIgnoreAllPatternsForItems:(id)arg1;
- (void)addIgnorePatternsForItems:(id)arg1;
- (void)openItemInMergeTool:(id)arg1;
- (void)restoreAncestorVersionForItems:(id)arg1;
- (void)restoreTheirVersionForItems:(id)arg1;
- (void)restoreMyVersionForItems:(id)arg1;
- (void)restoreUnmergedVersionForItems:(id)arg1;
- (void)resolveItemsUsingTheirVersion:(id)arg1;
- (void)resolveItemsUsingMyVersion:(id)arg1;
- (void)markItemsAsResolved:(id)arg1;
- (void)revertItemsToRevision:(id)arg1;
- (void)discardLocalChangesForItems:(id)arg1;
- (void)renameItem:(id)arg1;
- (void)deleteItems:(id)arg1;
- (void)delete:(id)arg1;
- (void)untrackItems:(id)arg1;
- (void)unstageItems:(id)arg1;
- (void)stageItems:(id)arg1;
- (void)toggleStaging;
- (void)spaceKeyPressed:(id)arg1;
- (void)deleteKeyPressed:(id)arg1;
- (void)openSubmodule:(id)arg1;
- (void)tableRowDoubleClicked:(id)arg1;
- (void)stagingCheckboxClicked:(id)arg1;
- (void)keyDown:(id)arg1;
- (id)selectedObjects;
- (id)selectedItems;
- (void)windowDidChangeFirstResponder;
- (void)windowDidResignMain:(id)arg1;
- (void)windowDidBecomeMain:(id)arg1;
- (void)windowDidResignKey:(id)arg1;
- (void)windowDidBecomeKey:(id)arg1;
- (void)workingTreeItemController:(id)arg1 didFailReloading:(id)arg2;
- (void)workingTreeItemControllerDidChangeItems:(id)arg1;
- (void)workingTreeItemController:(id)arg1 didUpdateItems:(id)arg2;
- (void)workingTreeItemController:(id)arg1 didMoveItemAtIndex:(unsigned long long)arg2 inParent:(id)arg3 toIndex:(unsigned long long)arg4 inParent:(id)arg5;
- (void)workingTreeItemController:(id)arg1 didInsertItemsAtIndexPaths:(id)arg2 inParent:(id)arg3;
- (void)workingTreeItemController:(id)arg1 didDeleteItemsAtIndexPaths:(id)arg2 inParent:(id)arg3;
- (void)workingTreeItemControllerWillChangeItems:(id)arg1;
- (void)workingTreeItemControllerDidReloadItems:(id)arg1;
- (BOOL)outlineView:(id)arg1 writeItems:(id)arg2 toPasteboard:(id)arg3;
- (void)outlineView:(id)arg1 sortDescriptorsDidChange:(id)arg2;
- (void)outlineView:(id)arg1 didAddRowView:(id)arg2 forRow:(long long)arg3;
- (id)outlineView:(id)arg1 objectValueForTableColumn:(id)arg2 byItem:(id)arg3;
- (id)outlineView:(id)arg1 child:(long long)arg2 ofItem:(id)arg3;
- (BOOL)outlineView:(id)arg1 isItemExpandable:(id)arg2;
- (long long)outlineView:(id)arg1 numberOfChildrenOfItem:(id)arg2;
- (void)outlineViewSelectionDidChange:(id)arg1;
- (BOOL)outlineView:(id)arg1 shouldShowOutlineCellForItem:(id)arg2;
- (id)outlineView:(id)arg1 viewForTableColumn:(id)arg2 item:(id)arg3;
- (void)outlineViewItemDidCollapse:(id)arg1;
- (void)outlineViewItemWillExpand:(id)arg1;
- (void)updateRowViewForItem:(id)arg1;
- (void)restoreSelection;
- (void)storeCurrentSelection;
- (void)unlockView;
- (void)lockView;
- (void)repositoryDidUpdateWorkingCopy:(id)arg1;
- (void)repositoryWillUpdateWorkingCopy:(id)arg1;
- (void)repositoryDidFinishCommit:(id)arg1;
- (void)repositoryDidUpdateWorkingTree:(id)arg1;
- (void)workingTreeViewSettingsDidChange:(id)arg1;
- (void)unregisterWorkingTreeViewSettingsObserver;
- (void)registerWorkingTreeViewSettingsObserver;
- (void)userDefaultsDidChangeKey:(id)arg1 change:(id)arg2;
- (void)updateWorkingTreeItemsControllerConfiguration;
- (void)configureWorkingTreeItemsControllerFromViewSettings;
- (void)configureWorkingTreeItemsController;
- (void)updateOutlineViewConfiguration;
- (void)updateViewSettings;
- (void)configureOutlineViewInteraction;
- (void)configureOutlineViewColumnSortDescriptors;
- (void)configureOutlineViewCellViewIndendation;
- (void)registerNibsForOutlineView;
- (void)configureOutlineView;
- (void)viewWillDisappear;
- (void)viewDidAppear;
- (void)viewDidLoad;
- (void)dealloc;
- (void)commonInit;
- (id)initWithRepository:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

