//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSError.h>

@class NSString;

@interface NSError (GTGitErrors)
+ (void)loadDefinitionsForAppGitErrorDomain;
+ (id)appGitMultipleErrorsErrorWithErrors:(id)arg1 userInfo:(id)arg2;
+ (id)appGitErrorWithCode:(long long)arg1 userInfo:(id)arg2;
+ (id)appGitErrorWithFNGitError:(id)arg1;
+ (void)load;
@property(readonly, nonatomic, getter=isGitUnknownRevisionError) BOOL gitUnknownRevisionError;
@property(readonly, nonatomic, getter=isGitRemoteRepositoryNotFoundError) BOOL gitRemoteRepositoryNotFoundError;
@property(readonly, nonatomic, getter=isGitMergeConflictError) BOOL gitMergeConflictError;
@property(readonly, nonatomic, getter=isGitRemoteAuthenticationError) BOOL gitRemoteAuthenticationError;
@property(readonly, nonatomic, getter=isGitRemoteConnectionError) BOOL gitRemoteConnectionError;
@property(readonly, nonatomic, getter=isGitSVNInstallationError) BOOL gitSVNInstallationError;
@property(readonly, nonatomic, getter=isGitParseError) BOOL gitParseError;
@property(readonly, nonatomic, getter=isGitInvalidRepositoryError) BOOL gitInvalidRepositoryError;
@property(readonly, nonatomic, getter=isGitErrorDomain) BOOL gitErrorDomain;
@property(readonly, nonatomic) NSString *gitSubmodulePath;
@property(readonly, nonatomic) NSString *gitSubmoduleName;
@property(readonly, nonatomic) NSString *gitRepositoryPath;
@end

