//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSError.h>

@interface NSError (GTGPG)
+ (void)loadDefinitionsForGPGCommandErrorDomain;
+ (void)loadDefinitionsForGPGErrorDomain;
+ (id)gpgErrorWithCommand:(id)arg1 userInfo:(id)arg2;
+ (id)appGPGErrorWithGPGCommandError:(id)arg1 userInfo:(id)arg2;
+ (id)appGPGErrorWithCode:(long long)arg1 userInfo:(id)arg2;
+ (id)errorMappings;
+ (void)load;
@end

